// Default rankings: Justin Boone's 2026 Fantasy Football Top 300 (Yahoo Sports)
// Source: https://sports.yahoo.com/fantasy/article/2026-fantasy-football-rankings-justin-boone-top-300-players-155300098.html
// These load on startup and are replaced when a user uploads their own CSV.

export const DEFAULT_RANKINGS_NAME = "Justin Boone Top 300"

// Compact tuples: [rank, name, team, position]
const RAW: [number, string, string, string][] = [
  [1, "Bijan Robinson", "ATL", "RB"],
  [2, "Jahmyr Gibbs", "DET", "RB"],
  [3, "Ja'Marr Chase", "CIN", "WR"],
  [4, "Jaxon Smith-Njigba", "SEA", "WR"],
  [5, "Puka Nacua", "LAR", "WR"],
  [6, "Jonathan Taylor", "IND", "RB"],
  [7, "Christian McCaffrey", "SF", "RB"],
  [8, "CeeDee Lamb", "DAL", "WR"],
  [9, "Amon-Ra St. Brown", "DET", "WR"],
  [10, "James Cook III", "BUF", "RB"],
  [11, "Ashton Jeanty", "LV", "RB"],
  [12, "Justin Jefferson", "MIN", "WR"],
  [13, "Chase Brown", "CIN", "RB"],
  [14, "De'Von Achane", "MIA", "RB"],
  [15, "Omarion Hampton", "LAC", "RB"],
  [16, "Saquon Barkley", "PHI", "RB"],
  [17, "Jeremiyah Love", "ARI", "RB"],
  [18, "Kenneth Walker III", "KC", "RB"],
  [19, "Drake London", "ATL", "WR"],
  [20, "Brock Bowers", "LV", "TE"],
  [21, "Nico Collins", "HOU", "WR"],
  [22, "George Pickens", "DAL", "WR"],
  [23, "Derrick Henry", "BAL", "RB"],
  [24, "DeVonta Smith", "PHI", "WR"],
  [25, "A.J. Brown", "NE", "WR"],
  [26, "Trey McBride", "ARI", "TE"],
  [27, "Josh Allen", "BUF", "QB"],
  [28, "Chris Olave", "NO", "WR"],
  [29, "Rashee Rice", "KC", "WR"],
  [30, "Kyren Williams", "LAR", "RB"],
  [31, "Cam Skattebo", "NYG", "RB"],
  [32, "Javonte Williams", "DAL", "RB"],
  [33, "Travis Etienne Jr.", "NO", "RB"],
  [34, "Tetairoa McMillan", "CAR", "WR"],
  [35, "Zay Flowers", "BAL", "WR"],
  [36, "Tee Higgins", "CIN", "WR"],
  [37, "Luther Burden III", "CHI", "WR"],
  [38, "Garrett Wilson", "NYJ", "WR"],
  [39, "Ladd McConkey", "LAC", "WR"],
  [40, "Breece Hall", "NYJ", "RB"],
  [41, "Terry McLaurin", "WAS", "WR"],
  [42, "Jaylen Waddle", "DEN", "WR"],
  [43, "D'Andre Swift", "CHI", "RB"],
  [44, "Colston Loveland", "CHI", "TE"],
  [45, "Josh Jacobs", "GB", "RB"],
  [46, "Lamar Jackson", "BAL", "QB"],
  [47, "Christian Watson", "GB", "WR"],
  [48, "David Montgomery", "HOU", "RB"],
  [49, "Quinshon Judkins", "CLE", "RB"],
  [50, "Malik Nabers", "NYG", "WR"],
  [51, "TreVeyon Henderson", "NE", "RB"],
  [52, "Carnell Tate", "TEN", "WR"],
  [53, "Bhayshul Tuten", "JAC", "RB"],
  [54, "Emeka Egbuka", "TB", "WR"],
  [55, "Davante Adams", "LAR", "WR"],
  [56, "Jameson Williams", "DET", "WR"],
  [57, "Chuba Hubbard", "CAR", "RB"],
  [58, "Jadarian Price", "SEA", "RB"],
  [59, "DJ Moore", "BUF", "WR"],
  [60, "Makai Lemon", "PHI", "WR"],
  [61, "Rome Odunze", "CHI", "WR"],
  [62, "Jayden Daniels", "WAS", "QB"],
  [63, "Drake Maye", "NE", "QB"],
  [64, "Tyler Warren", "IND", "TE"],
  [65, "Jordyn Tyson", "NO", "WR"],
  [66, "Parker Washington", "JAC", "WR"],
  [67, "Mike Evans", "SF", "WR"],
  [68, "Joe Burrow", "CIN", "QB"],
  [69, "Justin Herbert", "LAC", "QB"],
  [70, "Jalen Hurts", "PHI", "QB"],
  [71, "Tucker Kraft", "GB", "TE"],
  [72, "Bucky Irving", "TB", "RB"],
  [73, "Rhamondre Stevenson", "NE", "RB"],
  [74, "Marvin Harrison Jr.", "ARI", "WR"],
  [75, "Alec Pierce", "IND", "WR"],
  [76, "Caleb Williams", "CHI", "QB"],
  [77, "Chris Godwin Jr.", "TB", "WR"],
  [78, "Courtland Sutton", "DEN", "WR"],
  [79, "DK Metcalf", "PIT", "WR"],
  [80, "Jayden Reed", "GB", "WR"],
  [81, "Ricky Pearsall", "SF", "WR"],
  [82, "Brian Thomas Jr.", "JAC", "WR"],
  [83, "Jaylen Warren", "PIT", "RB"],
  [84, "Rico Dowdle", "PIT", "RB"],
  [85, "Tony Pollard", "TEN", "RB"],
  [86, "Kenneth Gainwell", "TB", "RB"],
  [87, "Jaxson Dart", "NYG", "QB"],
  [88, "Kyle Monangai", "CHI", "RB"],
  [89, "Blake Corum", "LAR", "RB"],
  [90, "Dak Prescott", "DAL", "QB"],
  [91, "Trevor Lawrence", "JAC", "QB"],
  [92, "RJ Harvey", "DEN", "RB"],
  [93, "Harold Fannin Jr.", "CLE", "TE"],
  [94, "Sam LaPorta", "DET", "TE"],
  [95, "Kyle Pitts Sr.", "ATL", "TE"],
  [96, "Bo Nix", "DEN", "QB"],
  [97, "George Kittle", "SF", "TE"],
  [98, "Jordan Addison", "MIN", "WR"],
  [99, "J.K. Dobbins", "DEN", "RB"],
  [100, "Jonathon Brooks", "CAR", "RB"],
  [101, "Jakobi Meyers", "JAC", "WR"],
  [102, "KC Concepcion", "CLE", "WR"],
  [103, "Jacory Croskey-Merritt", "WAS", "RB"],
  [104, "Rachaad White", "WAS", "RB"],
  [105, "Dalton Kincaid", "BUF", "TE"],
  [106, "Michael Wilson", "ARI", "WR"],
  [107, "Quentin Johnston", "LAC", "WR"],
  [108, "Wan'Dale Robinson", "TEN", "WR"],
  [109, "Josh Downs", "IND", "WR"],
  [110, "Brock Purdy", "SF", "QB"],
  [111, "Aaron Jones Sr.", "MIN", "RB"],
  [112, "Jordan Mason", "MIN", "RB"],
  [113, "Xavier Worthy", "KC", "WR"],
  [114, "Michael Pittman Jr.", "PIT", "WR"],
  [115, "Kyler Murray", "MIN", "QB"],
  [116, "Travis Kelce", "KC", "TE"],
  [117, "Isaiah Likely", "NYG", "TE"],
  [118, "Tyrone Tracy Jr.", "NYG", "RB"],
  [119, "Jalen Coker", "CAR", "WR"],
  [120, "Omar Cooper Jr.", "NYJ", "WR"],
  [121, "Jayden Higgins", "HOU", "WR"],
  [122, "Stefon Diggs", "FA", "WR"],
  [123, "Patrick Mahomes II", "KC", "QB"],
  [124, "Romeo Doubs", "NE", "WR"],
  [125, "Jonah Coleman", "DEN", "RB"],
  [126, "Chris Rodriguez Jr.", "JAC", "RB"],
  [127, "Mark Andrews", "BAL", "TE"],
  [128, "Keaton Mitchell", "LAC", "RB"],
  [129, "Isiah Pacheco", "DET", "RB"],
  [130, "Brian Robinson Jr.", "ATL", "RB"],
  [131, "Tyler Allgeier", "ARI", "RB"],
  [132, "Emmett Johnson", "KC", "RB"],
  [133, "Zach Charbonnet", "SEA", "RB"],
  [134, "Nicholas Singleton", "TEN", "RB"],
  [135, "Jalen McMillan", "TB", "WR"],
  [136, "Dallas Goedert", "PHI", "TE"],
  [137, "Chig Okonkwo", "WAS", "TE"],
  [138, "Antonio Williams", "WAS", "WR"],
  [139, "Kaytron Allen", "WAS", "RB"],
  [140, "Dylan Sampson", "CLE", "RB"],
  [141, "Woody Marks", "HOU", "RB"],
  [142, "Braelon Allen", "NYJ", "RB"],
  [143, "Tank Bigsby", "PHI", "RB"],
  [144, "Jake Ferguson", "DAL", "TE"],
  [145, "Travis Hunter", "JAC", "WR"],
  [146, "Denzel Boston", "CLE", "WR"],
  [147, "Khalil Shakir", "BUF", "WR"],
  [148, "Hunter Henry", "NE", "TE"],
  [149, "Matthew Stafford", "LAR", "QB"],
  [150, "Tyler Shough", "NO", "QB"],
  [151, "Ray Davis", "BUF", "RB"],
  [152, "Tyjae Spears", "TEN", "RB"],
  [153, "Matthew Golden", "GB", "WR"],
  [154, "Rashid Shaheed", "SEA", "WR"],
  [155, "Emanuel Wilson", "SEA", "RB"],
  [156, "Sean Tucker", "TB", "RB"],
  [157, "Jalen Nailor", "LV", "WR"],
  [158, "Tre Tucker", "LV", "WR"],
  [159, "Jauan Jennings", "MIN", "WR"],
  [160, "Deebo Samuel Sr.", "FA", "WR"],
  [161, "Jared Goff", "DET", "QB"],
  [162, "Malik Willis", "MIA", "QB"],
  [163, "Baker Mayfield", "TB", "QB"],
  [164, "Jordan Love", "GB", "QB"],
  [165, "Brenton Strange", "JAC", "TE"],
  [166, "Demond Claiborne", "MIN", "RB"],
  [167, "Oronde Gadsden II", "LAC", "TE"],
  [168, "Mike Washington Jr.", "LV", "RB"],
  [169, "Jordan James", "SF", "RB"],
  [170, "Alvin Kamara", "NO", "RB"],
  [171, "Chris Brooks", "GB", "RB"],
  [172, "James Conner", "ARI", "RB"],
  [173, "Jerry Jeudy", "CLE", "WR"],
  [174, "Houston Texans", "HOU", "DST"],
  [175, "Kaelon Black", "SF", "RB"],
  [176, "Isaac TeSlaa", "DET", "WR"],
  [177, "Malik Washington", "MIA", "WR"],
  [178, "Ryan Flournoy", "DAL", "WR"],
  [179, "Tre' Harris", "LAC", "WR"],
  [180, "Zachariah Branch", "ATL", "WR"],
  [181, "Darnell Mooney", "NYG", "WR"],
  [182, "Jaylen Wright", "MIA", "RB"],
  [183, "Justice Hill", "BAL", "RB"],
  [184, "Seattle Seahawks", "SEA", "DST"],
  [185, "Brandon Aubrey", "DAL", "K"],
  [186, "Najee Harris", "LAC", "RB"],
  [187, "Jaydon Blue", "DAL", "RB"],
  [188, "Sam Darnold", "SEA", "QB"],
  [189, "Los Angeles Rams", "LAR", "DST"],
  [190, "Adonai Mitchell", "NYJ", "WR"],
  [191, "Kenyon Sadiq", "NYJ", "TE"],
  [192, "Juwan Johnson", "NO", "TE"],
  [193, "Dalton Schultz", "HOU", "TE"],
  [194, "Adam Randall", "BAL", "RB"],
  [195, "Kimani Vidal", "LAC", "RB"],
  [196, "Kendre Miller", "NO", "RB"],
  [197, "Devin Neal", "NO", "RB"],
  [198, "MarShawn Lloyd", "GB", "RB"],
  [199, "Ollie Gordon II", "MIA", "RB"],
  [200, "DJ Giddens", "IND", "RB"],
  [201, "C.J. Stroud", "HOU", "QB"],
  [202, "Denver Broncos", "DEN", "DST"],
  [203, "Philadelphia Eagles", "PHI", "DST"],
  [204, "Ka'imi Fairbairn", "HOU", "K"],
  [205, "Cam Ward", "TEN", "QB"],
  [206, "Daniel Jones", "IND", "QB"],
  [207, "Bryce Young", "CAR", "QB"],
  [208, "AJ Barner", "SEA", "TE"],
  [209, "George Holani", "SEA", "RB"],
  [210, "Malik Davis", "DAL", "RB"],
  [211, "LeQuint Allen Jr.", "JAC", "RB"],
  [212, "Malachi Fields", "NYG", "WR"],
  [213, "Germie Bernard", "PIT", "WR"],
  [214, "Calvin Ridley", "TEN", "WR"],
  [215, "De'Zhaun Stribling", "SF", "WR"],
  [216, "Ted Hurst III", "TB", "WR"],
  [217, "Tank Dell", "HOU", "WR"],
  [218, "Chris Bell", "MIA", "WR"],
  [219, "Pat Bryant", "DEN", "WR"],
  [220, "Troy Franklin", "DEN", "WR"],
  [221, "Brandon Aiyuk", "SF", "WR"],
  [222, "Tyreek Hill", "FA", "WR"],
  [223, "Jaylin Noel", "HOU", "WR"],
  [224, "Tory Horton", "SEA", "WR"],
  [225, "Elijah Sarratt", "BAL", "WR"],
  [226, "Ja'Kobi Lane", "BAL", "WR"],
  [227, "Fernando Mendoza", "LV", "QB"],
  [228, "T.J. Hockenson", "MIN", "TE"],
  [229, "New England Patriots", "NE", "DST"],
  [230, "Cam Little", "JAC", "K"],
  [231, "Pittsburgh Steelers", "PIT", "DST"],
  [232, "Gunnar Helm", "TEN", "TE"],
  [233, "Geno Smith", "NYJ", "QB"],
  [234, "Aaron Rodgers", "PIT", "QB"],
  [235, "Greg Dulcich", "MIA", "TE"],
  [236, "Eli Stowers", "PHI", "TE"],
  [237, "Terrance Ferguson", "LAR", "TE"],
  [238, "Skyler Bell", "BUF", "WR"],
  [239, "Cameron Dicker", "LAC", "K"],
  [240, "Jason Myers", "SEA", "K"],
  [241, "Jacksonville Jaguars", "JAC", "DST"],
  [242, "Eddy Pineiro", "SF", "K"],
  [243, "Dontayvion Wicks", "PHI", "WR"],
  [244, "Jahan Dotson", "ATL", "WR"],
  [245, "Hollywood Brown", "PHI", "WR"],
  [246, "Tyquan Thornton", "KC", "WR"],
  [247, "Keon Coleman", "BUF", "WR"],
  [248, "Rashod Bateman", "BAL", "WR"],
  [249, "Marvin Mims Jr.", "DEN", "WR"],
  [250, "Jalen Tolbert", "MIA", "WR"],
  [251, "Christian Kirk", "SF", "WR"],
  [252, "Treylon Burks", "WAS", "WR"],
  [253, "Konata Mumpfield", "LAR", "WR"],
  [254, "Harrison Mevis", "LAR", "K"],
  [255, "Minnesota Vikings", "MIN", "DST"],
  [256, "Baltimore Ravens", "BAL", "DST"],
  [257, "Detroit Lions", "DET", "DST"],
  [258, "Cairo Santos", "CHI", "K"],
  [259, "Buffalo Bills", "BUF", "DST"],
  [260, "Will Reichard", "MIN", "K"],
  [261, "Tyler Loop", "BAL", "K"],
  [262, "Jack Bech", "LV", "WR"],
  [263, "Chris Brazzell II", "CAR", "WR"],
  [264, "Caleb Douglas", "MIA", "WR"],
  [265, "Cooper Kupp", "SEA", "WR"],
  [266, "Jake Bates", "DET", "K"],
  [267, "Pat Freiermuth", "PIT", "TE"],
  [268, "Cade Otton", "TB", "TE"],
  [269, "David Njoku", "LAC", "TE"],
  [270, "Mike Gesicki", "CIN", "TE"],
  [271, "Jake Tonges", "SF", "TE"],
  [272, "Jacoby Brissett", "ARI", "QB"],
  [273, "Michael Penix Jr.", "ATL", "QB"],
  [274, "Deshaun Watson", "CLE", "QB"],
  [275, "Tua Tagovailoa", "ATL", "QB"],
  [276, "Shedeur Sanders", "CLE", "QB"],
  [277, "Isaiah Davis", "NYJ", "RB"],
  [278, "Tahj Brooks", "CIN", "RB"],
  [279, "Trey Benson", "ARI", "RB"],
  [280, "Will Shipley", "PHI", "RB"],
  [281, "Devin Singletary", "NYG", "RB"],
  [282, "Emari Demercado", "KC", "RB"],
  [283, "Kaleb Johnson", "PIT", "RB"],
  [284, "Samaje Perine", "CIN", "RB"],
  [285, "Eli Heidenreich", "PIT", "RB"],
  [286, "Trevor Etienne", "CAR", "RB"],
  [287, "Seth McGowan", "IND", "RB"],
  [288, "Carson Beck", "ARI", "QB"],
  [289, "Darius Slayton", "NYG", "WR"],
  [290, "Nick Westbrook-Ikhine", "IND", "WR"],
  [291, "Dyami Brown", "WAS", "WR"],
  [292, "Kirk Cousins", "LV", "QB"],
  [293, "Kayshon Boutte", "NE", "WR"],
  [294, "Jalen Royals", "KC", "WR"],
  [295, "Brenen Thompson", "LAC", "WR"],
  [296, "Keenan Allen", "LAC", "WR"],
  [297, "Savion Williams", "GB", "WR"],
  [298, "KaVontae Turpin", "DAL", "WR"],
  [299, "Brashard Smith", "KC", "RB"],
  [300, "Ty Johnson", "BUF", "RB"],
  [301, "Phil Mafah", "DAL", "RB"],
]

export const DEFAULT_RANKINGS = RAW.map(([rank, name, team, position]) => {
  const nameParts = name.split(" ")
  const firstName = nameParts.shift() || ""
  const lastName = nameParts.join(" ")
  return {
    id: `boone-${rank}`,
    name,
    firstName,
    lastName,
    position,
    team,
    adp: rank,
    value: 0,
    drafted: false,
  }
})
