// Preset expert rankings, organized by scoring format.
// Each scoring format can hold multiple analysts (more can be added over time).
// Players are NOT loaded by default — the user picks a preset to load it,
// and uploading their own CSV replaces whatever is loaded.

type RawPlayer = [number, string, string, string] // [rank, name, team, position]

function buildPlayers(idPrefix: string, raw: RawPlayer[]) {
  return raw.map(([rank, name, team, position]) => {
    const nameParts = name.split(" ")
    const firstName = nameParts.shift() || ""
    const lastName = nameParts.join(" ")
    return {
      id: `${idPrefix}-${rank}`,
      name,
      firstName,
      lastName,
      position,
      team: team || "FA",
      adp: rank,
      value: 0,
      drafted: false,
    }
  })
}

// ---------------------------------------------------------------------------
// HALF PPR — Justin Boone (Yahoo Sports), updated 6/3
// FantasyPros draft-rank accuracy: #1
// ---------------------------------------------------------------------------
const BOONE_RAW: RawPlayer[] = [
  [1, "Bijan Robinson", "ATL", "RB"],
  [2, "Jahmyr Gibbs", "DET", "RB"],
  [3, "Ja'Marr Chase", "CIN", "WR"],
  [4, "Jaxon Smith-Njigba", "SEA", "WR"],
  [5, "Puka Nacua", "LAR", "WR"],
  [6, "Jonathan Taylor", "IND", "RB"],
  [7, "Christian McCaffrey", "SF", "RB"],
  [8, "CeeDee Lamb", "DAL", "WR"],
  [9, "Amon-Ra St. Brown", "DET", "WR"],
  [10, "James Cook III", "BUF", "RB"],
  [11, "Ashton Jeanty", "LV", "RB"],
  [12, "Justin Jefferson", "MIN", "WR"],
  [13, "Chase Brown", "CIN", "RB"],
  [14, "De'Von Achane", "MIA", "RB"],
  [15, "Omarion Hampton", "LAC", "RB"],
  [16, "Saquon Barkley", "PHI", "RB"],
  [17, "Jeremiyah Love", "ARI", "RB"],
  [18, "Kenneth Walker III", "KC", "RB"],
  [19, "Drake London", "ATL", "WR"],
  [20, "Brock Bowers", "LV", "TE"],
  [21, "Nico Collins", "HOU", "WR"],
  [22, "George Pickens", "DAL", "WR"],
  [23, "Derrick Henry", "BAL", "RB"],
  [24, "DeVonta Smith", "PHI", "WR"],
  [25, "A.J. Brown", "NE", "WR"],
  [26, "Trey McBride", "ARI", "TE"],
  [27, "Josh Allen", "BUF", "QB"],
  [28, "Chris Olave", "NO", "WR"],
  [29, "Rashee Rice", "KC", "WR"],
  [30, "Kyren Williams", "LAR", "RB"],
  [31, "Cam Skattebo", "NYG", "RB"],
  [32, "Javonte Williams", "DAL", "RB"],
  [33, "Travis Etienne Jr.", "NO", "RB"],
  [34, "Tetairoa McMillan", "CAR", "WR"],
  [35, "Zay Flowers", "BAL", "WR"],
  [36, "Tee Higgins", "CIN", "WR"],
  [37, "Luther Burden III", "CHI", "WR"],
  [38, "Garrett Wilson", "NYJ", "WR"],
  [39, "Ladd McConkey", "LAC", "WR"],
  [40, "Breece Hall", "NYJ", "RB"],
  [41, "Terry McLaurin", "WAS", "WR"],
  [42, "Jaylen Waddle", "DEN", "WR"],
  [43, "D'Andre Swift", "CHI", "RB"],
  [44, "Colston Loveland", "CHI", "TE"],
  [45, "Josh Jacobs", "GB", "RB"],
  [46, "Lamar Jackson", "BAL", "QB"],
  [47, "Christian Watson", "GB", "WR"],
  [48, "David Montgomery", "HOU", "RB"],
  [49, "Quinshon Judkins", "CLE", "RB"],
  [50, "Malik Nabers", "NYG", "WR"],
  [51, "TreVeyon Henderson", "NE", "RB"],
  [52, "Carnell Tate", "TEN", "WR"],
  [53, "Bhayshul Tuten", "JAC", "RB"],
  [54, "Emeka Egbuka", "TB", "WR"],
  [55, "Davante Adams", "LAR", "WR"],
  [56, "Jameson Williams", "DET", "WR"],
  [57, "Chuba Hubbard", "CAR", "RB"],
  [58, "Jadarian Price", "SEA", "RB"],
  [59, "DJ Moore", "BUF", "WR"],
  [60, "Makai Lemon", "PHI", "WR"],
  [61, "Rome Odunze", "CHI", "WR"],
  [62, "Jayden Daniels", "WAS", "QB"],
  [63, "Drake Maye", "NE", "QB"],
  [64, "Tyler Warren", "IND", "TE"],
  [65, "Jordyn Tyson", "NO", "WR"],
  [66, "Parker Washington", "JAC", "WR"],
  [67, "Mike Evans", "SF", "WR"],
  [68, "Joe Burrow", "CIN", "QB"],
  [69, "Justin Herbert", "LAC", "QB"],
  [70, "Jalen Hurts", "PHI", "QB"],
  [71, "Tucker Kraft", "GB", "TE"],
  [72, "Bucky Irving", "TB", "RB"],
  [73, "Rhamondre Stevenson", "NE", "RB"],
  [74, "Marvin Harrison Jr.", "ARI", "WR"],
  [75, "Alec Pierce", "IND", "WR"],
  [76, "Caleb Williams", "CHI", "QB"],
  [77, "Chris Godwin Jr.", "TB", "WR"],
  [78, "Courtland Sutton", "DEN", "WR"],
  [79, "DK Metcalf", "PIT", "WR"],
  [80, "Jayden Reed", "GB", "WR"],
  [81, "Ricky Pearsall", "SF", "WR"],
  [82, "Brian Thomas Jr.", "JAC", "WR"],
  [83, "Jaylen Warren", "PIT", "RB"],
  [84, "Rico Dowdle", "PIT", "RB"],
  [85, "Tony Pollard", "TEN", "RB"],
  [86, "Kenneth Gainwell", "TB", "RB"],
  [87, "Jaxson Dart", "NYG", "QB"],
  [88, "Kyle Monangai", "CHI", "RB"],
  [89, "Blake Corum", "LAR", "RB"],
  [90, "Dak Prescott", "DAL", "QB"],
  [91, "Trevor Lawrence", "JAC", "QB"],
  [92, "RJ Harvey", "DEN", "RB"],
  [93, "Harold Fannin Jr.", "CLE", "TE"],
  [94, "Sam LaPorta", "DET", "TE"],
  [95, "Kyle Pitts Sr.", "ATL", "TE"],
  [96, "Bo Nix", "DEN", "QB"],
  [97, "George Kittle", "SF", "TE"],
  [98, "Jordan Addison", "MIN", "WR"],
  [99, "J.K. Dobbins", "DEN", "RB"],
  [100, "Jonathon Brooks", "CAR", "RB"],
  [101, "Jakobi Meyers", "JAC", "WR"],
  [102, "KC Concepcion", "CLE", "WR"],
  [103, "Jacory Croskey-Merritt", "WAS", "RB"],
  [104, "Rachaad White", "WAS", "RB"],
  [105, "Dalton Kincaid", "BUF", "TE"],
  [106, "Michael Wilson", "ARI", "WR"],
  [107, "Quentin Johnston", "LAC", "WR"],
  [108, "Wan'Dale Robinson", "TEN", "WR"],
  [109, "Josh Downs", "IND", "WR"],
  [110, "Brock Purdy", "SF", "QB"],
  [111, "Aaron Jones Sr.", "MIN", "RB"],
  [112, "Jordan Mason", "MIN", "RB"],
  [113, "Xavier Worthy", "KC", "WR"],
  [114, "Michael Pittman Jr.", "PIT", "WR"],
  [115, "Kyler Murray", "MIN", "QB"],
  [116, "Travis Kelce", "KC", "TE"],
  [117, "Isaiah Likely", "NYG", "TE"],
  [118, "Tyrone Tracy Jr.", "NYG", "RB"],
  [119, "Jalen Coker", "CAR", "WR"],
  [120, "Omar Cooper Jr.", "NYJ", "WR"],
  [121, "Jayden Higgins", "HOU", "WR"],
  [122, "Stefon Diggs", "FA", "WR"],
  [123, "Patrick Mahomes II", "KC", "QB"],
  [124, "Romeo Doubs", "NE", "WR"],
  [125, "Jonah Coleman", "DEN", "RB"],
  [126, "Chris Rodriguez Jr.", "JAC", "RB"],
  [127, "Mark Andrews", "BAL", "TE"],
  [128, "Keaton Mitchell", "LAC", "RB"],
  [129, "Isiah Pacheco", "DET", "RB"],
  [130, "Brian Robinson Jr.", "ATL", "RB"],
  [131, "Tyler Allgeier", "ARI", "RB"],
  [132, "Emmett Johnson", "KC", "RB"],
  [133, "Zach Charbonnet", "SEA", "RB"],
  [134, "Nicholas Singleton", "TEN", "RB"],
  [135, "Jalen McMillan", "TB", "WR"],
  [136, "Dallas Goedert", "PHI", "TE"],
  [137, "Chig Okonkwo", "WAS", "TE"],
  [138, "Antonio Williams", "WAS", "WR"],
  [139, "Kaytron Allen", "WAS", "RB"],
  [140, "Dylan Sampson", "CLE", "RB"],
  [141, "Woody Marks", "HOU", "RB"],
  [142, "Braelon Allen", "NYJ", "RB"],
  [143, "Tank Bigsby", "PHI", "RB"],
  [144, "Jake Ferguson", "DAL", "TE"],
  [145, "Travis Hunter", "JAC", "WR"],
  [146, "Denzel Boston", "CLE", "WR"],
  [147, "Khalil Shakir", "BUF", "WR"],
  [148, "Hunter Henry", "NE", "TE"],
  [149, "Matthew Stafford", "LAR", "QB"],
  [150, "Tyler Shough", "NO", "QB"],
  [151, "Ray Davis", "BUF", "RB"],
  [152, "Tyjae Spears", "TEN", "RB"],
  [153, "Matthew Golden", "GB", "WR"],
  [154, "Rashid Shaheed", "SEA", "WR"],
  [155, "Emanuel Wilson", "SEA", "RB"],
  [156, "Sean Tucker", "TB", "RB"],
  [157, "Jalen Nailor", "LV", "WR"],
  [158, "Tre Tucker", "LV", "WR"],
  [159, "Jauan Jennings", "MIN", "WR"],
  [160, "Deebo Samuel Sr.", "FA", "WR"],
  [161, "Jared Goff", "DET", "QB"],
  [162, "Malik Willis", "MIA", "QB"],
  [163, "Baker Mayfield", "TB", "QB"],
  [164, "Jordan Love", "GB", "QB"],
  [165, "Brenton Strange", "JAC", "TE"],
  [166, "Demond Claiborne", "MIN", "RB"],
  [167, "Oronde Gadsden II", "LAC", "TE"],
  [168, "Mike Washington Jr.", "LV", "RB"],
  [169, "Jordan James", "SF", "RB"],
  [170, "Alvin Kamara", "NO", "RB"],
  [171, "Chris Brooks", "GB", "RB"],
  [172, "James Conner", "ARI", "RB"],
  [173, "Jerry Jeudy", "CLE", "WR"],
  [174, "Houston Texans", "HOU", "DST"],
  [175, "Kaelon Black", "SF", "RB"],
  [176, "Isaac TeSlaa", "DET", "WR"],
  [177, "Malik Washington", "MIA", "WR"],
  [178, "Ryan Flournoy", "DAL", "WR"],
  [179, "Tre' Harris", "LAC", "WR"],
  [180, "Zachariah Branch", "ATL", "WR"],
  [181, "Darnell Mooney", "NYG", "WR"],
  [182, "Jaylen Wright", "MIA", "RB"],
  [183, "Justice Hill", "BAL", "RB"],
  [184, "Seattle Seahawks", "SEA", "DST"],
  [185, "Brandon Aubrey", "DAL", "K"],
  [186, "Najee Harris", "LAC", "RB"],
  [187, "Jaydon Blue", "DAL", "RB"],
  [188, "Sam Darnold", "SEA", "QB"],
  [189, "Los Angeles Rams", "LAR", "DST"],
  [190, "Adonai Mitchell", "NYJ", "WR"],
  [191, "Kenyon Sadiq", "NYJ", "TE"],
  [192, "Juwan Johnson", "NO", "TE"],
  [193, "Dalton Schultz", "HOU", "TE"],
  [194, "Adam Randall", "BAL", "RB"],
  [195, "Kimani Vidal", "LAC", "RB"],
  [196, "Kendre Miller", "NO", "RB"],
  [197, "Devin Neal", "NO", "RB"],
  [198, "MarShawn Lloyd", "GB", "RB"],
  [199, "Ollie Gordon II", "MIA", "RB"],
  [200, "DJ Giddens", "IND", "RB"],
  [201, "C.J. Stroud", "HOU", "QB"],
  [202, "Denver Broncos", "DEN", "DST"],
  [203, "Philadelphia Eagles", "PHI", "DST"],
  [204, "Ka'imi Fairbairn", "HOU", "K"],
  [205, "Cam Ward", "TEN", "QB"],
  [206, "Daniel Jones", "IND", "QB"],
  [207, "Bryce Young", "CAR", "QB"],
  [208, "AJ Barner", "SEA", "TE"],
  [209, "George Holani", "SEA", "RB"],
  [210, "Malik Davis", "DAL", "RB"],
  [211, "LeQuint Allen Jr.", "JAC", "RB"],
  [212, "Malachi Fields", "NYG", "WR"],
  [213, "Germie Bernard", "PIT", "WR"],
  [214, "Calvin Ridley", "TEN", "WR"],
  [215, "De'Zhaun Stribling", "SF", "WR"],
  [216, "Ted Hurst III", "TB", "WR"],
  [217, "Tank Dell", "HOU", "WR"],
  [218, "Chris Bell", "MIA", "WR"],
  [219, "Pat Bryant", "DEN", "WR"],
  [220, "Troy Franklin", "DEN", "WR"],
  [221, "Brandon Aiyuk", "SF", "WR"],
  [222, "Tyreek Hill", "FA", "WR"],
  [223, "Jaylin Noel", "HOU", "WR"],
  [224, "Tory Horton", "SEA", "WR"],
  [225, "Elijah Sarratt", "BAL", "WR"],
  [226, "Ja'Kobi Lane", "BAL", "WR"],
  [227, "Fernando Mendoza", "LV", "QB"],
  [228, "T.J. Hockenson", "MIN", "TE"],
  [229, "New England Patriots", "NE", "DST"],
  [230, "Cam Little", "JAC", "K"],
  [231, "Pittsburgh Steelers", "PIT", "DST"],
  [232, "Gunnar Helm", "TEN", "TE"],
  [233, "Geno Smith", "NYJ", "QB"],
  [234, "Aaron Rodgers", "PIT", "QB"],
  [235, "Greg Dulcich", "MIA", "TE"],
  [236, "Eli Stowers", "PHI", "TE"],
  [237, "Terrance Ferguson", "LAR", "TE"],
  [238, "Skyler Bell", "BUF", "WR"],
  [239, "Cameron Dicker", "LAC", "K"],
  [240, "Jason Myers", "SEA", "K"],
  [241, "Jacksonville Jaguars", "JAC", "DST"],
  [242, "Eddy Pineiro", "SF", "K"],
  [243, "Dontayvion Wicks", "PHI", "WR"],
  [244, "Jahan Dotson", "ATL", "WR"],
  [245, "Hollywood Brown", "PHI", "WR"],
  [246, "Tyquan Thornton", "KC", "WR"],
  [247, "Keon Coleman", "BUF", "WR"],
  [248, "Rashod Bateman", "BAL", "WR"],
  [249, "Marvin Mims Jr.", "DEN", "WR"],
  [250, "Jalen Tolbert", "MIA", "WR"],
  [251, "Christian Kirk", "SF", "WR"],
  [252, "Treylon Burks", "WAS", "WR"],
  [253, "Konata Mumpfield", "LAR", "WR"],
  [254, "Harrison Mevis", "LAR", "K"],
  [255, "Minnesota Vikings", "MIN", "DST"],
  [256, "Baltimore Ravens", "BAL", "DST"],
  [257, "Detroit Lions", "DET", "DST"],
  [258, "Cairo Santos", "CHI", "K"],
  [259, "Buffalo Bills", "BUF", "DST"],
  [260, "Will Reichard", "MIN", "K"],
  [261, "Tyler Loop", "BAL", "K"],
  [262, "Jack Bech", "LV", "WR"],
  [263, "Chris Brazzell II", "CAR", "WR"],
  [264, "Caleb Douglas", "MIA", "WR"],
  [265, "Cooper Kupp", "SEA", "WR"],
  [266, "Jake Bates", "DET", "K"],
  [267, "Pat Freiermuth", "PIT", "TE"],
  [268, "Cade Otton", "TB", "TE"],
  [269, "David Njoku", "LAC", "TE"],
  [270, "Mike Gesicki", "CIN", "TE"],
  [271, "Jake Tonges", "SF", "TE"],
  [272, "Jacoby Brissett", "ARI", "QB"],
  [273, "Michael Penix Jr.", "ATL", "QB"],
  [274, "Deshaun Watson", "CLE", "QB"],
  [275, "Tua Tagovailoa", "ATL", "QB"],
  [276, "Shedeur Sanders", "CLE", "QB"],
  [277, "Isaiah Davis", "NYJ", "RB"],
  [278, "Tahj Brooks", "CIN", "RB"],
  [279, "Trey Benson", "ARI", "RB"],
  [280, "Will Shipley", "PHI", "RB"],
  [281, "Devin Singletary", "NYG", "RB"],
  [282, "Emari Demercado", "KC", "RB"],
  [283, "Kaleb Johnson", "PIT", "RB"],
  [284, "Samaje Perine", "CIN", "RB"],
  [285, "Eli Heidenreich", "PIT", "RB"],
  [286, "Trevor Etienne", "CAR", "RB"],
  [287, "Seth McGowan", "IND", "RB"],
  [288, "Carson Beck", "ARI", "QB"],
  [289, "Darius Slayton", "NYG", "WR"],
  [290, "Nick Westbrook-Ikhine", "IND", "WR"],
  [291, "Dyami Brown", "WAS", "WR"],
  [292, "Kirk Cousins", "LV", "QB"],
  [293, "Kayshon Boutte", "NE", "WR"],
  [294, "Jalen Royals", "KC", "WR"],
  [295, "Brenen Thompson", "LAC", "WR"],
  [296, "Keenan Allen", "LAC", "WR"],
  [297, "Savion Williams", "GB", "WR"],
  [298, "KaVontae Turpin", "DAL", "WR"],
  [299, "Brashard Smith", "KC", "RB"],
  [300, "Ty Johnson", "BUF", "RB"],
  [301, "Phil Mafah", "DAL", "RB"],
]

// ---------------------------------------------------------------------------
// FULL PPR — Andrew Erickson (FantasyPros), updated 6/3
// FantasyPros draft-rank accuracy: #5
// ---------------------------------------------------------------------------
const ERICKSON_RAW: RawPlayer[] = [
  [1, "Ja'Marr Chase", "CIN", "WR"],
  [2, "Jahmyr Gibbs", "DET", "RB"],
  [3, "Puka Nacua", "LAR", "WR"],
  [4, "Jaxon Smith-Njigba", "SEA", "WR"],
  [5, "Bijan Robinson", "ATL", "RB"],
  [6, "Amon-Ra St. Brown", "DET", "WR"],
  [7, "James Cook III", "BUF", "RB"],
  [8, "Justin Jefferson", "MIN", "WR"],
  [9, "CeeDee Lamb", "DAL", "WR"],
  [10, "Jonathan Taylor", "IND", "RB"],
  [11, "Drake London", "ATL", "WR"],
  [12, "A.J. Brown", "NE", "WR"],
  [13, "Chase Brown", "CIN", "RB"],
  [14, "Rashee Rice", "KC", "WR"],
  [15, "Nico Collins", "HOU", "WR"],
  [16, "Trey McBride", "ARI", "TE"],
  [17, "Ashton Jeanty", "LV", "RB"],
  [18, "George Pickens", "DAL", "WR"],
  [19, "Zay Flowers", "BAL", "WR"],
  [20, "Malik Nabers", "NYG", "WR"],
  [21, "Omarion Hampton", "LAC", "RB"],
  [22, "Brock Bowers", "LV", "TE"],
  [23, "De'Von Achane", "MIA", "RB"],
  [24, "Christian McCaffrey", "SF", "RB"],
  [25, "Drake Maye", "NE", "QB"],
  [26, "Chris Olave", "NO", "WR"],
  [27, "Josh Allen", "BUF", "QB"],
  [28, "Tetairoa McMillan", "CAR", "WR"],
  [29, "DeVonta Smith", "PHI", "WR"],
  [30, "Lamar Jackson", "BAL", "QB"],
  [31, "Kenneth Walker III", "KC", "RB"],
  [32, "Colston Loveland", "CHI", "TE"],
  [33, "Saquon Barkley", "PHI", "RB"],
  [34, "Javonte Williams", "DAL", "RB"],
  [35, "Garrett Wilson", "NYJ", "WR"],
  [36, "Ladd McConkey", "LAC", "WR"],
  [37, "Jayden Daniels", "WAS", "QB"],
  [38, "Jaylen Waddle", "DEN", "WR"],
  [39, "Jeremiyah Love", "ARI", "RB"],
  [40, "Tee Higgins", "CIN", "WR"],
  [41, "Breece Hall", "NYJ", "RB"],
  [42, "Mike Evans", "SF", "WR"],
  [43, "Travis Etienne Jr.", "NO", "RB"],
  [44, "Terry McLaurin", "WAS", "WR"],
  [45, "DJ Moore", "BUF", "WR"],
  [46, "Derrick Henry", "BAL", "RB"],
  [47, "Cam Skattebo", "NYG", "RB"],
  [48, "Carnell Tate", "TEN", "WR"],
  [49, "Luther Burden III", "CHI", "WR"],
  [50, "Kyren Williams", "LAR", "RB"],
  [51, "Marvin Harrison Jr.", "ARI", "WR"],
  [52, "Emeka Egbuka", "TB", "WR"],
  [53, "Bucky Irving", "TB", "RB"],
  [54, "Joe Burrow", "CIN", "QB"],
  [55, "Christian Watson", "GB", "WR"],
  [56, "Josh Jacobs", "GB", "RB"],
  [57, "Tyler Warren", "IND", "TE"],
  [58, "Quinshon Judkins", "CLE", "RB"],
  [59, "Justin Herbert", "LAC", "QB"],
  [60, "Alec Pierce", "IND", "WR"],
  [61, "David Montgomery", "HOU", "RB"],
  [62, "Rome Odunze", "CHI", "WR"],
  [63, "Caleb Williams", "CHI", "QB"],
  [64, "Jameson Williams", "DET", "WR"],
  [65, "Rachaad White", "WAS", "RB"],
  [66, "Harold Fannin Jr.", "CLE", "TE"],
  [67, "RJ Harvey", "DEN", "RB"],
  [68, "Michael Pittman Jr.", "PIT", "WR"],
  [69, "Jordyn Tyson", "NO", "WR"],
  [70, "Jaxson Dart", "NYG", "QB"],
  [71, "Makai Lemon", "PHI", "WR"],
  [72, "TreVeyon Henderson", "NE", "RB"],
  [73, "Tucker Kraft", "GB", "TE"],
  [74, "Jalen Hurts", "PHI", "QB"],
  [75, "Jaylen Warren", "PIT", "RB"],
  [76, "Josh Downs", "IND", "WR"],
  [77, "Rico Dowdle", "PIT", "RB"],
  [78, "Jadarian Price", "SEA", "RB"],
  [79, "Brock Purdy", "SF", "QB"],
  [80, "Rhamondre Stevenson", "NE", "RB"],
  [81, "Davante Adams", "LAR", "WR"],
  [82, "Jakobi Meyers", "JAC", "WR"],
  [83, "DK Metcalf", "PIT", "WR"],
  [84, "D'Andre Swift", "CHI", "RB"],
  [85, "Kyle Pitts Sr.", "ATL", "TE"],
  [86, "Bhayshul Tuten", "JAC", "RB"],
  [87, "Chig Okonkwo", "WAS", "TE"],
  [88, "KC Concepcion", "CLE", "WR"],
  [89, "Chuba Hubbard", "CAR", "RB"],
  [90, "Courtland Sutton", "DEN", "WR"],
  [91, "Wan'Dale Robinson", "TEN", "WR"],
  [92, "Trevor Lawrence", "JAC", "QB"],
  [93, "Kenneth Gainwell", "TB", "RB"],
  [94, "Ricky Pearsall", "SF", "WR"],
  [95, "Sam LaPorta", "DET", "TE"],
  [96, "Parker Washington", "JAC", "WR"],
  [97, "Dalton Kincaid", "BUF", "TE"],
  [98, "Dak Prescott", "DAL", "QB"],
  [99, "Aaron Jones Sr.", "MIN", "RB"],
  [100, "Chris Godwin Jr.", "TB", "WR"],
  [101, "Patrick Mahomes II", "KC", "QB"],
  [102, "Tony Pollard", "TEN", "RB"],
  [103, "Kyle Monangai", "CHI", "RB"],
  [104, "Jordan Love", "GB", "QB"],
  [105, "Bo Nix", "DEN", "QB"],
  [106, "Isaiah Likely", "NYG", "TE"],
  [107, "Brian Thomas Jr.", "JAC", "WR"],
  [108, "Kyler Murray", "MIN", "QB"],
  [109, "Jayden Reed", "GB", "WR"],
  [110, "Michael Wilson", "ARI", "WR"],
  [111, "Travis Kelce", "KC", "TE"],
  [112, "George Kittle", "SF", "TE"],
  [113, "Baker Mayfield", "TB", "QB"],
  [114, "Malik Willis", "MIA", "QB"],
  [115, "Jayden Higgins", "HOU", "WR"],
  [116, "Jordan Addison", "MIN", "WR"],
  [117, "J.K. Dobbins", "DEN", "RB"],
  [118, "Jacory Croskey-Merritt", "WAS", "RB"],
  [119, "Matthew Stafford", "LAR", "QB"],
  [120, "Blake Corum", "LAR", "RB"],
  [121, "Romeo Doubs", "NE", "WR"],
  [122, "Jonathon Brooks", "CAR", "RB"],
  [123, "Xavier Worthy", "KC", "WR"],
  [124, "Greg Dulcich", "MIA", "TE"],
  [125, "Jared Goff", "DET", "QB"],
  [126, "Khalil Shakir", "BUF", "WR"],
  [127, "Tyler Allgeier", "ARI", "RB"],
  [128, "Omar Cooper Jr.", "NYJ", "WR"],
  [129, "Tyler Shough", "NO", "QB"],
  [130, "Dylan Sampson", "CLE", "RB"],
  [131, "Dallas Goedert", "PHI", "TE"],
  [132, "Emanuel Wilson", "SEA", "RB"],
  [133, "Jalen Coker", "CAR", "WR"],
  [134, "C.J. Stroud", "HOU", "QB"],
  [135, "Jordan Mason", "MIN", "RB"],
  [136, "Denzel Boston", "CLE", "WR"],
  [137, "Matthew Golden", "GB", "WR"],
  [138, "Kenyon Sadiq", "NYJ", "TE"],
  [139, "Cam Ward", "TEN", "QB"],
  [140, "Antonio Williams", "WAS", "WR"],
  [141, "Isiah Pacheco", "DET", "RB"],
  [142, "Quentin Johnston", "LAC", "WR"],
  [143, "Jonah Coleman", "DEN", "RB"],
  [144, "Brenton Strange", "JAC", "TE"],
  [145, "Nicholas Singleton", "TEN", "RB"],
  [146, "Tyrone Tracy Jr.", "NYG", "RB"],
  [147, "Bryce Young", "CAR", "QB"],
  [148, "Zach Charbonnet", "SEA", "RB"],
  [149, "Stefon Diggs", "FA", "WR"],
  [150, "Jaylin Noel", "HOU", "WR"],
  [151, "Houston Texans", "HOU", "DST"],
  [152, "Emmett Johnson", "KC", "RB"],
  [153, "Geno Smith", "NYJ", "QB"],
  [154, "Germie Bernard", "PIT", "WR"],
  [155, "Mark Andrews", "BAL", "TE"],
  [156, "Brian Robinson Jr.", "ATL", "RB"],
  [157, "Tank Bigsby", "PHI", "RB"],
  [158, "Jake Ferguson", "DAL", "TE"],
  [159, "Daniel Jones", "IND", "QB"],
  [160, "Keaton Mitchell", "LAC", "RB"],
  [161, "Seattle Seahawks", "SEA", "DST"],
  [162, "Tyjae Spears", "TEN", "RB"],
  [163, "Rashid Shaheed", "SEA", "WR"],
  [164, "Kaytron Allen", "WAS", "RB"],
  [165, "Jerry Jeudy", "CLE", "WR"],
  [166, "Travis Hunter", "JAC", "WR"],
  [167, "Los Angeles Rams", "LAR", "DST"],
  [168, "Jalen McMillan", "TB", "WR"],
  [169, "Alvin Kamara", "NO", "RB"],
  [170, "Chris Bell", "MIA", "WR"],
  [171, "Los Angeles Chargers", "LAC", "DST"],
  [172, "Philadelphia Eagles", "PHI", "DST"],
  [173, "AJ Barner", "SEA", "TE"],
  [174, "Darnell Mooney", "NYG", "WR"],
  [175, "Sean Tucker", "TB", "RB"],
  [176, "Ted Hurst III", "TB", "WR"],
  [177, "Chris Brooks", "GB", "RB"],
  [178, "Jauan Jennings", "MIN", "WR"],
  [179, "Sam Darnold", "SEA", "QB"],
  [180, "Elijah Sarratt", "BAL", "WR"],
  [181, "Hunter Henry", "NE", "TE"],
  [182, "Jordan James", "SF", "RB"],
  [183, "Denver Broncos", "DEN", "DST"],
  [184, "Isaac TeSlaa", "DET", "WR"],
  [185, "Detroit Lions", "DET", "DST"],
  [186, "Baltimore Ravens", "BAL", "DST"],
  [187, "Brandon Aubrey", "DAL", "K"],
  [188, "Minnesota Vikings", "MIN", "DST"],
  [189, "MarShawn Lloyd", "GB", "RB"],
  [190, "Kansas City Chiefs", "KC", "DST"],
  [191, "Jacksonville Jaguars", "JAC", "DST"],
  [192, "Ka'imi Fairbairn", "HOU", "K"],
  [193, "Cam Little", "JAC", "K"],
  [194, "Pittsburgh Steelers", "PIT", "DST"],
  [195, "Tre Tucker", "LV", "WR"],
  [196, "T.J. Hockenson", "MIN", "TE"],
  [197, "De'Zhaun Stribling", "SF", "WR"],
  [198, "Cameron Dicker", "LAC", "K"],
  [199, "Kayshon Boutte", "NE", "WR"],
  [200, "Evan McPherson", "CIN", "K"],
  [201, "Ray Davis", "BUF", "RB"],
  [202, "Brandon Aiyuk", "SF", "WR"],
  [203, "Juwan Johnson", "NO", "TE"],
  [204, "Jason Myers", "SEA", "K"],
  [205, "Calvin Ridley", "TEN", "WR"],
  [206, "New England Patriots", "NE", "DST"],
  [207, "Andy Borregales", "NE", "K"],
  [208, "Zachariah Branch", "ATL", "WR"],
  [209, "Dalton Schultz", "HOU", "TE"],
  [210, "Malik Washington", "MIA", "WR"],
  [211, "Tyler Loop", "BAL", "K"],
  [212, "Green Bay Packers", "GB", "DST"],
  [213, "Eddy Pineiro", "SF", "K"],
  [214, "Fernando Mendoza", "LV", "QB"],
  [215, "Chase McLaughlin", "TB", "K"],
  [216, "Cairo Santos", "CHI", "K"],
  [217, "Harrison Mevis", "LAR", "K"],
  [218, "Malachi Fields", "NYG", "WR"],
  [219, "Braelon Allen", "NYJ", "RB"],
  [220, "Buffalo Bills", "BUF", "DST"],
  [221, "Adonai Mitchell", "NYJ", "WR"],
  [222, "Mike Washington Jr.", "LV", "RB"],
  [223, "Pat Bryant", "DEN", "WR"],
  [224, "Chris Brazzell II", "CAR", "WR"],
  [225, "Jalen Nailor", "LV", "WR"],
  [226, "Gunnar Helm", "TEN", "TE"],
  [227, "Dontayvion Wicks", "PHI", "WR"],
  [228, "LeQuint Allen Jr.", "JAC", "RB"],
  [229, "Oronde Gadsden II", "LAC", "TE"],
  [230, "Chimere Dike", "TEN", "WR"],
  [231, "Bam Knight", "ARI", "RB"],
  [232, "Devaughn Vele", "NO", "WR"],
  [233, "Justice Hill", "BAL", "RB"],
  [234, "Woody Marks", "HOU", "RB"],
  [235, "Atlanta Falcons", "ATL", "DST"],
  [236, "Terrance Ferguson", "LAR", "TE"],
  [237, "DJ Giddens", "IND", "RB"],
  [238, "Demond Claiborne", "MIN", "RB"],
  [239, "Cyrus Allen", "KC", "WR"],
  [240, "Jake Bates", "DET", "K"],
  [241, "Tyreek Hill", "FA", "WR"],
  [242, "Tua Tagovailoa", "ATL", "QB"],
  [243, "Samaje Perine", "CIN", "RB"],
  [244, "Marvin Mims Jr.", "DEN", "WR"],
  [245, "Deebo Samuel Sr.", "FA", "WR"],
  [246, "David Njoku", "LAC", "TE"],
  [247, "Rashod Bateman", "BAL", "WR"],
  [248, "Kimani Vidal", "LAC", "RB"],
  [249, "Tennessee Titans", "TEN", "DST"],
  [250, "Charlie Smyth", "NO", "K"],
  [251, "Jaylen Wright", "MIA", "RB"],
  [252, "Chris Boswell", "PIT", "K"],
  [253, "Wil Lutz", "DEN", "K"],
  [254, "Jake Tonges", "SF", "TE"],
  [255, "Aaron Rodgers", "PIT", "QB"],
  [256, "Pat Freiermuth", "PIT", "TE"],
  [257, "Kaleb Johnson", "PIT", "RB"],
  [258, "Troy Franklin", "DEN", "WR"],
  [259, "Cade Otton", "TB", "TE"],
  [260, "Ollie Gordon II", "MIA", "RB"],
  [261, "Mike Gesicki", "CIN", "TE"],
  [262, "Tank Dell", "HOU", "WR"],
  [263, "Chris Rodriguez Jr.", "JAC", "RB"],
  [264, "Ryan Flournoy", "DAL", "WR"],
  [265, "Keenan Allen", "LAC", "WR"],
  [266, "Emari Demercado", "KC", "RB"],
  [267, "Tre' Harris", "LAC", "WR"],
  [268, "Darnell Washington", "PIT", "TE"],
  [269, "Cooper Kupp", "SEA", "WR"],
  [270, "DeMario Douglas", "NE", "WR"],
  [271, "Eli Heidenreich", "PIT", "RB"],
  [272, "Bryce Lance", "NO", "WR"],
  [273, "Keon Coleman", "BUF", "WR"],
  [274, "Eli Stowers", "PHI", "TE"],
  [275, "James Conner", "ARI", "RB"],
  [276, "Deshaun Watson", "CLE", "QB"],
  [277, "Andrei Iosivas", "CIN", "WR"],
  [278, "Jaydon Blue", "DAL", "RB"],
  [279, "San Francisco 49ers", "SF", "DST"],
  [280, "Las Vegas Raiders", "LV", "DST"],
  [281, "Theo Johnson", "NYG", "TE"],
  [282, "Harrison Butker", "KC", "K"],
  [283, "Najee Harris", "LAC", "RB"],
  [284, "Kaelon Black", "SF", "RB"],
  [285, "Michael Penix Jr.", "ATL", "QB"],
  [286, "Konata Mumpfield", "LAR", "WR"],
  [287, "Kyle Williams", "NE", "WR"],
  [288, "Brashard Smith", "KC", "RB"],
  [289, "Elic Ayomanor", "TEN", "WR"],
  [290, "Evan Engram", "DEN", "TE"],
  [291, "Mack Hollins", "NE", "WR"],
  [292, "George Holani", "SEA", "RB"],
  [293, "Christian Kirk", "SF", "WR"],
  [294, "Jaleel McLaughlin", "DEN", "RB"],
  [295, "Ja'Tavion Sanders", "CAR", "TE"],
  [296, "Kevin Coleman Jr.", "MIA", "WR"],
  [297, "Trey Benson", "ARI", "RB"],
  [298, "Skyler Bell", "BUF", "WR"],
  [299, "Tutu Atwell", "MIA", "WR"],
  [300, "Colby Parkinson", "LAR", "TE"],
  [301, "Seth McGowan", "IND", "RB"],
  [302, "Darius Slayton", "NYG", "WR"],
  [303, "Tyquan Thornton", "KC", "WR"],
  [304, "Adam Randall", "BAL", "RB"],
  [305, "CJ Daniels", "LAR", "WR"],
  [306, "Dawson Knox", "BUF", "TE"],
  [307, "Ja'Kobi Lane", "BAL", "WR"],
  [308, "Jacoby Brissett", "ARI", "QB"],
  [309, "Mason Taylor", "NYJ", "TE"],
  [310, "Kareem Hunt", "FA", "RB"],
  [311, "Isaiah Davis", "NYJ", "RB"],
  [312, "Jack Bech", "LV", "WR"],
  [313, "Tahj Brooks", "CIN", "RB"],
  [314, "Jerome Ford", "WAS", "RB"],
  [315, "Brenen Thompson", "LAC", "WR"],
  [316, "Savion Williams", "GB", "WR"],
  [317, "Trevor Etienne", "CAR", "RB"],
  [318, "Ty Johnson", "BUF", "RB"],
  [319, "Jalen Royals", "KC", "WR"],
  [320, "Eli Raridon", "NE", "TE"],
  [321, "Shedeur Sanders", "CLE", "QB"],
  [322, "Devin Neal", "NO", "RB"],
  [323, "Cedric Tillman", "CLE", "WR"],
  [324, "Kirk Cousins", "LV", "QB"],
  [325, "Oscar Delp", "NO", "TE"],
  [326, "Devin Singletary", "NYG", "RB"],
  [327, "Kendre Miller", "NO", "RB"],
  [328, "Hollywood Brown", "PHI", "WR"],
  [329, "Malik Davis", "DAL", "RB"],
  [330, "J'Mari Taylor", "JAC", "RB"],
  [331, "Jaylin Lane", "WAS", "WR"],
  [332, "Zane Gonzalez", "MIA", "K"],
  [333, "Tory Horton", "SEA", "WR"],
  [334, "J.J. McCarthy", "MIN", "QB"],
  [335, "Marlin Klein", "HOU", "TE"],
  [336, "Carson Beck", "ARI", "QB"],
  [337, "Luke McCaffrey", "WAS", "WR"],
  [338, "Tez Johnson", "TB", "WR"],
  [339, "Max Klare", "LAR", "TE"],
  [340, "Kendrick Bourne", "ARI", "WR"],
  [341, "Elijah Arroyo", "SEA", "TE"],
  [342, "Kalif Raymond", "CHI", "WR"],
  [343, "Isaiah Bond", "CLE", "WR"],
  [344, "Mac Jones", "SF", "QB"],
  [345, "Noah Fant", "NO", "TE"],
  [346, "Jalen Tolbert", "MIA", "WR"],
  [347, "Calvin Austin III", "NYG", "WR"],
  [348, "Michael Mayer", "LV", "TE"],
  [349, "Cole Kmet", "CHI", "TE"],
  [350, "Tommy Tremble", "CAR", "TE"],
  [351, "New Orleans Saints", "NO", "DST"],
  [352, "Justin Joly", "DEN", "TE"],
  [353, "Anthony Richardson Sr.", "IND", "QB"],
  [354, "Nate Boerkircher", "JAC", "TE"],
  [355, "Luke Musgrave", "GB", "TE"],
  [356, "Tyler Higbee", "LAR", "TE"],
  [357, "Justin Fields", "KC", "QB"],
  [358, "Jared Wiley", "KC", "TE"],
  [359, "Sam Roush", "CHI", "TE"],
  [360, "Darren Waller", "FA", "TE"],
  [361, "Noah Gray", "KC", "TE"],
  [362, "Cade Klubnik", "NYJ", "QB"],
  [363, "Ty Simpson", "LAR", "QB"],
  [364, "Ben Sinnott", "WAS", "TE"],
  [365, "Gardner Minshew II", "ARI", "QB"],
]

export type RankingPreset = {
  id: string
  analyst: string
  source: string
  updated: string
  accuracyRank: number
  accuracyNote: string
  players: ReturnType<typeof buildPlayers>
}

export type ScoringGroup = {
  id: string
  label: string
  description: string
  presets: RankingPreset[]
}

export const RANKING_PRESET_GROUPS: ScoringGroup[] = [
  {
    id: "half-ppr",
    label: "Half PPR",
    description: "0.5 points per reception",
    presets: [
      {
        id: "boone-half-ppr",
        analyst: "Justin Boone",
        source: "Yahoo Sports",
        updated: "6/3",
        accuracyRank: 1,
        accuracyNote: "#1 in FantasyPros draft accuracy",
        players: buildPlayers("boone", BOONE_RAW),
      },
    ],
  },
  {
    id: "full-ppr",
    label: "Full PPR",
    description: "1 point per reception",
    presets: [
      {
        id: "erickson-full-ppr",
        analyst: "Andrew Erickson",
        source: "FantasyPros",
        updated: "6/3",
        accuracyRank: 5,
        accuracyNote: "#5 in FantasyPros draft accuracy",
        players: buildPlayers("erickson", ERICKSON_RAW),
      },
    ],
  },
]

export function findPresetById(id: string): RankingPreset | undefined {
  for (const group of RANKING_PRESET_GROUPS) {
    const found = group.presets.find((p) => p.id === id)
    if (found) return found
  }
  return undefined
}
