// Preset expert rankings, organized by scoring format.
// Each scoring format can hold multiple analysts (more can be added over time).
// Players are NOT loaded by default — the user picks a preset to load it,
// and uploading their own CSV replaces whatever is loaded.

type RawPlayer = [number, string, string, string] // [rank, name, team, position]

const getCanonicalPlayerNameKey = (name: string) =>
  String(name || "")
    .replace(/\bKenny\s+Gainwell\b/i, "Kenneth Gainwell")
    .toLowerCase()
    .replace(/(\s|,)+(jr\.?|sr\.?|ii|iii|iv|v)\b/g, "")
    .replace(/[^a-z]/g, "")
    .trim()


function buildPlayers(idPrefix: string, raw: RawPlayer[]) {
  const seenNames = new Set<string>()

  return raw.filter(([, name]) => {
    const canonicalName = getCanonicalPlayerNameKey(name)
    if (seenNames.has(canonicalName)) return false
    seenNames.add(canonicalName)
    return true
  }).map(([rank, name, team, position]) => {
    const nameParts = name.split(" ")
    const firstName = nameParts.shift() || ""
    const lastName = nameParts.join(" ")
    return {
      id: `${idPrefix}-${rank}`,
      name,
      firstName,
      lastName,
      position,
      team: team || "FA",
      adp: rank,
      value: 0,
      drafted: false,
    }
  })
}

type UnderdogRawPlayer = [number, string, string, number] // [rank, name, position, ADP]

function buildUnderdogPlayers(idPrefix: string, raw: UnderdogRawPlayer[]) {
  const seenNames = new Set<string>()

  return raw.filter(([, name]) => {
    const canonicalName = getCanonicalPlayerNameKey(name)
    if (seenNames.has(canonicalName)) return false
    seenNames.add(canonicalName)
    return true
  }).map(([rank, name, position, adp]) => {
    const nameParts = name.split(" ")
    const firstName = nameParts.shift() || ""
    const lastName = nameParts.join(" ")
    return {
      id: `${idPrefix}-${rank}`,
      name,
      firstName,
      lastName,
      position,
      team: "FA",
      adp,
      rank,
      expertRank: rank,
      marketAdp: adp,
      value: 0,
      drafted: false,
    }
  })
}

function buildRawFromEntries(baseRaw: RawPlayer[], entries: readonly string[]): RawPlayer[] {
  const baseLookup = new Map(baseRaw.map(([, name, team, position]) => [getCanonicalPlayerNameKey(name), { team, position }] as const))
  const rankedNames = new Set<string>()
  const rankedEntries = entries.map((entry, index): RawPlayer => {
    const [name, explicitTeam, explicitPosition] = entry.split("|")
    const canonicalName = getCanonicalPlayerNameKey(name)
    rankedNames.add(canonicalName)
    const basePlayer = baseLookup.get(canonicalName)
    return [index + 1, name, explicitTeam || basePlayer?.team || "FA", explicitPosition || basePlayer?.position || "WR"]
  })

  const fallbackEntries = baseRaw
    .filter(([, name]) => !rankedNames.has(getCanonicalPlayerNameKey(name)))
    .map(([, name, team, position], index): RawPlayer => [rankedEntries.length + index + 1, name, team, position])

  return [...rankedEntries, ...fallbackEntries]
}

// ---------------------------------------------------------------------------
// HALF PPR — Justin Boone (Yahoo Sports), updated 6/3
// FantasyPros in-season accuracy: #1 in 2025
// ---------------------------------------------------------------------------

const UNDERDOG_BEST_BALL_JUNE_24_RAW: UnderdogRawPlayer[] = [
  [1, "Jahmyr Gibbs", "RB", 1.2],
  [2, "Bijan Robinson", "RB", 1.9],
  [3, "Ja'Marr Chase", "WR", 3.1],
  [4, "Puka Nacua", "WR", 4],
  [5, "Jaxon Smith-Njigba", "WR", 5.2],
  [6, "Jonathan Taylor", "RB", 6.8],
  [7, "Christian McCaffrey", "RB", 7.1],
  [8, "Amon-Ra St. Brown", "WR", 7.6],
  [9, "CeeDee Lamb", "WR", 9.5],
  [10, "Justin Jefferson", "WR", 9.8],
  [11, "Ashton Jeanty", "RB", 11.2],
  [12, "James Cook", "RB", 11.8],
  [13, "Saquon Barkley", "RB", 13.6],
  [14, "Omarion Hampton", "RB", 15],
  [15, "De'Von Achane", "RB", 16],
  [16, "Kenneth Walker III", "RB", 16.2],
  [17, "Chase Brown", "RB", 17.1],
  [18, "Derrick Henry", "RB", 17.6],
  [19, "Drake London", "WR", 18.7],
  [20, "A.J. Brown", "WR", 19.8],
  [21, "Brock Bowers", "TE", 20.4],
  [22, "Nico Collins", "WR", 22.2],
  [23, "George Pickens", "WR", 23.2],
  [24, "Jeremiyah Love", "RB", 24.2],
  [25, "Trey McBride", "TE", 26.8],
  [26, "Breece Hall", "RB", 27.1],
  [27, "DeVonta Smith", "WR", 27.6],
  [28, "Rashee Rice", "WR", 28],
  [29, "Chris Olave", "WR", 29.1],
  [30, "Travis Etienne Jr.", "RB", 29.9],
  [31, "Malik Nabers", "WR", 32],
  [32, "Kyren Williams", "RB", 32.1],
  [33, "Zay Flowers", "WR", 32.4],
  [34, "Josh Allen", "QB", 34.2],
  [35, "Tee Higgins", "WR", 34.5],
  [36, "Javonte Williams", "RB", 35.7],
  [37, "Ladd McConkey", "WR", 37],
  [38, "Tetairoa McMillan", "WR", 38.3],
  [39, "Garrett Wilson", "WR", 38.7],
  [40, "Emeka Egbuka", "WR", 39],
  [41, "Josh Jacobs", "RB", 40.6],
  [42, "Luther Burden", "WR", 42.3],
  [43, "Cam Skattebo", "RB", 43.6],
  [44, "Mike Evans", "WR", 44.2],
  [45, "Terry McLaurin", "WR", 44.9],
  [46, "Colston Loveland", "TE", 46],
  [47, "Jaylen Waddle", "WR", 47.2],
  [48, "Jameson Williams", "WR", 48.7],
  [49, "David Montgomery", "RB", 49.3],
  [50, "Davante Adams", "WR", 50.3],
  [51, "TreVeyon Henderson", "RB", 51.3],
  [52, "D'Andre Swift", "RB", 51.6],
  [53, "Bucky Irving", "RB", 53.8],
  [54, "Quinshon Judkins", "RB", 54.4],
  [55, "D.J. Moore", "WR", 55.8],
  [56, "Bhayshul Tuten", "RB", 55.9],
  [57, "Lamar Jackson", "QB", 56.3],
  [58, "Christian Watson", "WR", 57.1],
  [59, "Rome Odunze", "WR", 58.7],
  [60, "Carnell Tate", "WR", 59.5],
  [61, "Jadarian Price", "RB", 61.1],
  [62, "Brian Thomas", "WR", 61.5],
  [63, "Jordyn Tyson", "WR", 63.6],
  [64, "Tyler Warren", "TE", 64.8],
  [65, "Joe Burrow", "QB", 65.7],
  [66, "Jayden Daniels", "QB", 67.1],
  [67, "Marvin Harrison", "WR", 67.8],
  [68, "Drake Maye", "QB", 68.2],
  [69, "Parker Washington", "WR", 68.8],
  [70, "Caleb Williams", "QB", 70.5],
  [71, "Jalen Hurts", "QB", 72.1],
  [72, "Makai Lemon", "WR", 72.5],
  [73, "Chuba Hubbard", "RB", 72.9],
  [74, "Rhamondre Stevenson", "RB", 74.9],
  [75, "Jaylen Warren", "RB", 75.3],
  [76, "DK Metcalf", "WR", 76.1],
  [77, "Tony Pollard", "RB", 76.5],
  [78, "Alec Pierce", "WR", 78.1],
  [79, "Dak Prescott", "QB", 79.9],
  [80, "Quentin Johnston", "WR", 80],
  [81, "Courtland Sutton", "WR", 81.5],
  [82, "Justin Herbert", "QB", 81.9],
  [83, "Tucker Kraft", "TE", 82.7],
  [84, "Jayden Reed", "WR", 83.8],
  [85, "Trevor Lawrence", "QB", 85.4],
  [86, "RJ Harvey", "RB", 86.8],
  [87, "Jordan Addison", "WR", 87.3],
  [88, "Rico Dowdle", "RB", 87.8],
  [89, "Chris Godwin", "WR", 88.7],
  [90, "Patrick Mahomes", "QB", 90.1],
  [91, "Josh Downs", "WR", 92],
  [92, "Kyle Monangai", "RB", 92.2],
  [93, "Blake Corum", "RB", 93.7],
  [94, "Michael Wilson", "WR", 94.7],
  [95, "Brock Purdy", "QB", 96.8],
  [96, "Xavier Worthy", "WR", 96.8],
  [97, "Jaxson Dart", "QB", 96.9],
  [98, "Sam LaPorta", "TE", 97.6],
  [99, "J.K. Dobbins", "RB", 100.4],
  [100, "Jakobi Meyers", "WR", 101.8],
  [101, "Ricky Pearsall", "WR", 101.9],
  [102, "Harold Fannin", "TE", 102.2],
  [103, "Michael Pittman Jr.", "WR", 103.5],
  [104, "Matthew Stafford", "QB", 103.9],
  [105, "Kenneth Gainwell", "RB", 105.1],
  [106, "Jonathon Brooks", "RB", 105.5],
  [107, "Bo Nix", "QB", 106.5],
  [108, "Kyle Pitts", "TE", 107.3],
  [109, "Jared Goff", "QB", 108.3],
  [110, "Matthew Golden", "WR", 109.4],
  [111, "Kyler Murray", "QB", 110],
  [112, "Jordan Love", "QB", 111.1],
  [113, "Rachaad White", "RB", 111.1],
  [114, "George Kittle", "TE", 114.3],
  [115, "Wan'Dale Robinson", "WR", 115.6],
  [116, "Romeo Doubs", "WR", 116.2],
  [117, "Aaron Jones", "RB", 117],
  [118, "KC Concepcion", "WR", 117.7],
  [119, "Baker Mayfield", "QB", 118.9],
  [120, "Travis Kelce", "TE", 119.4],
  [121, "Tyler Shough", "QB", 120.8],
  [122, "Jacory Croskey-Merritt", "RB", 121.9],
  [123, "Jayden Higgins", "WR", 123.3],
  [124, "Jordan Mason", "RB", 124.1],
  [125, "Mark Andrews", "TE", 125.5],
  [126, "Chris Rodriguez", "RB", 127.3],
  [127, "Jake Ferguson", "TE", 127.4],
  [128, "Khalil Shakir", "WR", 128],
  [129, "Dalton Kincaid", "TE", 129.3],
  [130, "Isaiah Likely", "TE", 130.9],
  [131, "Jalen Coker", "WR", 130.9],
  [132, "Malik Willis", "QB", 131],
  [133, "Tyrone Tracy", "RB", 132.5],
  [134, "Stefon Diggs", "WR", 132.9],
  [135, "Keaton Mitchell", "RB", 135.4],
  [136, "Dallas Goedert", "TE", 135.9],
  [137, "Travis Hunter", "WR", 137.7],
  [138, "Cam Ward", "QB", 138.9],
  [139, "Rashid Shaheed", "WR", 139],
  [140, "Omar Cooper Jr.", "WR", 141.4],
  [141, "Sam Darnold", "QB", 142.1],
  [142, "C.J. Stroud", "QB", 142.4],
  [143, "Woody Marks", "RB", 143.8],
  [144, "Oronde Gadsden", "TE", 144.9],
  [145, "Jalen McMillan", "WR", 145.4],
  [146, "Daniel Jones", "QB", 145.5],
  [147, "Chig Okonkwo", "TE", 146.3],
  [148, "Jauan Jennings", "WR", 148.9],
  [149, "Isiah Pacheco", "RB", 149.5],
  [150, "Hunter Henry", "TE", 150.1],
  [151, "Jalen Nailor", "WR", 151.7],
  [152, "Jonah Coleman", "RB", 152.3],
  [153, "Brenton Strange", "TE", 153.1],
  [154, "Tre Tucker", "WR", 153.8],
  [155, "Bryce Young", "QB", 156.3],
  [156, "Juwan Johnson", "TE", 156.7],
  [157, "Kenyon Sadiq", "TE", 157.3],
  [158, "Denzel Boston", "WR", 157.7],
  [159, "Zach Charbonnet", "RB", 158.9],
  [160, "Tyler Allgeier", "RB", 159.2],
  [161, "Tyjae Spears", "RB", 161.7],
  [162, "Ryan Flournoy", "WR", 162.3],
  [163, "Deebo Samuel", "WR", 163.4],
  [164, "T.J. Hockenson", "TE", 165.5],
  [165, "Antonio Williams", "WR", 166.6],
  [166, "Tre' Harris", "WR", 167.2],
  [167, "Brian Robinson", "RB", 168.1],
  [168, "Tank Bigsby", "RB", 168.9],
  [169, "De'Zhaun Stribling", "WR", 169.9],
  [170, "Dalton Schultz", "TE", 170.6],
  [171, "Isaac TeSlaa", "WR", 171.1],
  [172, "Fernando Mendoza", "QB", 172.2],
  [173, "Dylan Sampson", "RB", 173.3],
  [174, "AJ Barner", "TE", 175.3],
  [175, "Sean Tucker", "RB", 176.2],
  [176, "Aaron Rodgers", "QB", 176.4],
  [177, "Zachariah Branch", "WR", 177.7],
  [178, "Gunnar Helm", "TE", 179.1],
  [179, "Jerry Jeudy", "WR", 179.3],
  [180, "Adonai Mitchell", "WR", 179.9],
  [181, "Geno Smith", "QB", 182.2],
  [182, "Alvin Kamara", "RB", 182.6],
  [183, "Germie Bernard", "WR", 183.9],
  [184, "Greg Dulcich", "TE", 183.9],
  [185, "Calvin Ridley", "WR", 185.2],
  [186, "Brandon Aiyuk", "WR", 185.9],
  [187, "Cade Otton", "TE", 186.8],
  [188, "Tank Dell", "WR", 189.5],
  [189, "Malik Washington", "WR", 190.5],
  [190, "Nicholas Singleton", "RB", 191.4],
  [191, "Emmett Johnson", "RB", 192.3],
  [192, "Pat Freiermuth", "TE", 193.7],
  [193, "Ted Hurst", "WR", 194.8],
  [194, "Dontayvion Wicks", "WR", 195],
  [195, "Mike Washington Jr.", "RB", 198.8],
  [196, "Ray Davis", "RB", 198.9],
  [197, "Eli Stowers", "TE", 199.3],
  [198, "Kaytron Allen", "RB", 199.5],
  [199, "Jacoby Brissett", "QB", 200],
  [200, "Terrance Ferguson", "TE", 200.6],
  [201, "Braelon Allen", "RB", 202.4],
  [202, "Darnell Mooney", "WR", 204],
  [203, "Cooper Kupp", "WR", 205.1],
  [204, "Elijah Sarratt", "WR", 205.9],
  [205, "Tua Tagovailoa", "QB", 207.1],
  [206, "David Njoku", "TE", 207.6],
  [207, "MarShawn Lloyd", "RB", 207.6],
  [208, "Mike Gesicki", "TE", 207.9],
  [209, "Jaydon Blue", "RB", 208.5],
  [210, "Troy Franklin", "WR", 208.7],
  [211, "Pat Bryant", "WR", 209.6],
  [212, "Jaylin Noel", "WR", 210.1],
  [213, "Jordan James", "RB", 210.9],
  [214, "George Holani", "RB", 211.2],
  [215, "Tyreek Hill", "WR", 211.5],
  [216, "Kayshon Boutte", "WR", 211.6],
  [217, "Chris Brazzell II", "WR", 212.4],
  [218, "Demond Claiborne", "RB", 212.6],
  [219, "Tory Horton", "WR", 213.1],
  [220, "Chris Bell", "WR", 213.3],
  [221, "Malachi Fields", "WR", 213.3],
  [222, "Keon Coleman", "WR", 213.5],
  [223, "Rashod Bateman", "WR", 213.5],
  [224, "Christian Kirk", "WR", 213.7],
  [225, "Colby Parkinson", "TE", 213.7],
  [226, "Deshaun Watson", "QB", 214],
  [227, "Darnell Washington", "TE", 214.2],
  [228, "Justice Hill", "RB", 214.2],
  [229, "Evan Engram", "TE", 214.3],
  [230, "Kimani Vidal", "RB", 214.4],
  [231, "Tyquan Thornton", "WR", 214.4],
  [232, "Kaelon Black", "RB", 214.5],
  [233, "Michael Penix", "QB", 214.5],
  [234, "Devaughn Vele", "WR", 214.7],
  [235, "Shedeur Sanders", "QB", 214.7],
  [236, "Ja'Kobi Lane", "WR", 214.8],
  [237, "Emanuel Wilson", "RB", 215.1],
  [238, "Jake Tonges", "TE", 215.2],
  [239, "James Conner", "RB", 215.2],
  [240, "Samaje Perine", "RB", 215.2],
]

// ---------------------------------------------------------------------------
// HALF PPR — Justin Boone (Yahoo Sports), updated 6/3
// FantasyPros in-season accuracy: #1 in 2025
// ---------------------------------------------------------------------------
const BOONE_RAW: RawPlayer[] = [
  [1, "Bijan Robinson", "ATL", "RB"],
  [2, "Jahmyr Gibbs", "DET", "RB"],
  [3, "Ja'Marr Chase", "CIN", "WR"],
  [4, "Jaxon Smith-Njigba", "SEA", "WR"],
  [5, "Puka Nacua", "LAR", "WR"],
  [6, "Jonathan Taylor", "IND", "RB"],
  [7, "Christian McCaffrey", "SF", "RB"],
  [8, "CeeDee Lamb", "DAL", "WR"],
  [9, "Amon-Ra St. Brown", "DET", "WR"],
  [10, "James Cook III", "BUF", "RB"],
  [11, "Ashton Jeanty", "LV", "RB"],
  [12, "Justin Jefferson", "MIN", "WR"],
  [13, "Chase Brown", "CIN", "RB"],
  [14, "De'Von Achane", "MIA", "RB"],
  [15, "Omarion Hampton", "LAC", "RB"],
  [16, "Saquon Barkley", "PHI", "RB"],
  [17, "Jeremiyah Love", "ARI", "RB"],
  [18, "Kenneth Walker III", "KC", "RB"],
  [19, "Drake London", "ATL", "WR"],
  [20, "Brock Bowers", "LV", "TE"],
  [21, "Nico Collins", "HOU", "WR"],
  [22, "George Pickens", "DAL", "WR"],
  [23, "Derrick Henry", "BAL", "RB"],
  [24, "DeVonta Smith", "PHI", "WR"],
  [25, "A.J. Brown", "NE", "WR"],
  [26, "Trey McBride", "ARI", "TE"],
  [27, "Josh Allen", "BUF", "QB"],
  [28, "Chris Olave", "NO", "WR"],
  [29, "Rashee Rice", "KC", "WR"],
  [30, "Kyren Williams", "LAR", "RB"],
  [31, "Cam Skattebo", "NYG", "RB"],
  [32, "Javonte Williams", "DAL", "RB"],
  [33, "Travis Etienne Jr.", "NO", "RB"],
  [34, "Tetairoa McMillan", "CAR", "WR"],
  [35, "Zay Flowers", "BAL", "WR"],
  [36, "Tee Higgins", "CIN", "WR"],
  [37, "Luther Burden III", "CHI", "WR"],
  [38, "Garrett Wilson", "NYJ", "WR"],
  [39, "Ladd McConkey", "LAC", "WR"],
  [40, "Breece Hall", "NYJ", "RB"],
  [41, "Terry McLaurin", "WAS", "WR"],
  [42, "Jaylen Waddle", "DEN", "WR"],
  [43, "D'Andre Swift", "CHI", "RB"],
  [44, "Colston Loveland", "CHI", "TE"],
  [45, "Josh Jacobs", "GB", "RB"],
  [46, "Lamar Jackson", "BAL", "QB"],
  [47, "Christian Watson", "GB", "WR"],
  [48, "David Montgomery", "HOU", "RB"],
  [49, "Quinshon Judkins", "CLE", "RB"],
  [50, "Malik Nabers", "NYG", "WR"],
  [51, "TreVeyon Henderson", "NE", "RB"],
  [52, "Carnell Tate", "TEN", "WR"],
  [53, "Bhayshul Tuten", "JAC", "RB"],
  [54, "Emeka Egbuka", "TB", "WR"],
  [55, "Davante Adams", "LAR", "WR"],
  [56, "Jameson Williams", "DET", "WR"],
  [57, "Chuba Hubbard", "CAR", "RB"],
  [58, "Jadarian Price", "SEA", "RB"],
  [59, "DJ Moore", "BUF", "WR"],
  [60, "Makai Lemon", "PHI", "WR"],
  [61, "Rome Odunze", "CHI", "WR"],
  [62, "Jayden Daniels", "WAS", "QB"],
  [63, "Drake Maye", "NE", "QB"],
  [64, "Tyler Warren", "IND", "TE"],
  [65, "Jordyn Tyson", "NO", "WR"],
  [66, "Parker Washington", "JAC", "WR"],
  [67, "Mike Evans", "SF", "WR"],
  [68, "Joe Burrow", "CIN", "QB"],
  [69, "Justin Herbert", "LAC", "QB"],
  [70, "Jalen Hurts", "PHI", "QB"],
  [71, "Tucker Kraft", "GB", "TE"],
  [72, "Bucky Irving", "TB", "RB"],
  [73, "Rhamondre Stevenson", "NE", "RB"],
  [74, "Marvin Harrison Jr.", "ARI", "WR"],
  [75, "Alec Pierce", "IND", "WR"],
  [76, "Caleb Williams", "CHI", "QB"],
  [77, "Chris Godwin Jr.", "TB", "WR"],
  [78, "Courtland Sutton", "DEN", "WR"],
  [79, "DK Metcalf", "PIT", "WR"],
  [80, "Jayden Reed", "GB", "WR"],
  [81, "Ricky Pearsall", "SF", "WR"],
  [82, "Brian Thomas Jr.", "JAC", "WR"],
  [83, "Jaylen Warren", "PIT", "RB"],
  [84, "Rico Dowdle", "PIT", "RB"],
  [85, "Tony Pollard", "TEN", "RB"],
  [86, "Kenneth Gainwell", "TB", "RB"],
  [87, "Jaxson Dart", "NYG", "QB"],
  [88, "Kyle Monangai", "CHI", "RB"],
  [89, "Blake Corum", "LAR", "RB"],
  [90, "Dak Prescott", "DAL", "QB"],
  [91, "Trevor Lawrence", "JAC", "QB"],
  [92, "RJ Harvey", "DEN", "RB"],
  [93, "Harold Fannin Jr.", "CLE", "TE"],
  [94, "Sam LaPorta", "DET", "TE"],
  [95, "Kyle Pitts Sr.", "ATL", "TE"],
  [96, "Bo Nix", "DEN", "QB"],
  [97, "George Kittle", "SF", "TE"],
  [98, "Jordan Addison", "MIN", "WR"],
  [99, "J.K. Dobbins", "DEN", "RB"],
  [100, "Jonathon Brooks", "CAR", "RB"],
  [101, "Jakobi Meyers", "JAC", "WR"],
  [102, "KC Concepcion", "CLE", "WR"],
  [103, "Jacory Croskey-Merritt", "WAS", "RB"],
  [104, "Rachaad White", "WAS", "RB"],
  [105, "Dalton Kincaid", "BUF", "TE"],
  [106, "Michael Wilson", "ARI", "WR"],
  [107, "Quentin Johnston", "LAC", "WR"],
  [108, "Wan'Dale Robinson", "TEN", "WR"],
  [109, "Josh Downs", "IND", "WR"],
  [110, "Brock Purdy", "SF", "QB"],
  [111, "Aaron Jones Sr.", "MIN", "RB"],
  [112, "Jordan Mason", "MIN", "RB"],
  [113, "Xavier Worthy", "KC", "WR"],
  [114, "Michael Pittman Jr.", "PIT", "WR"],
  [115, "Kyler Murray", "MIN", "QB"],
  [116, "Travis Kelce", "KC", "TE"],
  [117, "Isaiah Likely", "NYG", "TE"],
  [118, "Tyrone Tracy Jr.", "NYG", "RB"],
  [119, "Jalen Coker", "CAR", "WR"],
  [120, "Omar Cooper Jr.", "NYJ", "WR"],
  [121, "Jayden Higgins", "HOU", "WR"],
  [122, "Stefon Diggs", "FA", "WR"],
  [123, "Patrick Mahomes II", "KC", "QB"],
  [124, "Romeo Doubs", "NE", "WR"],
  [125, "Jonah Coleman", "DEN", "RB"],
  [126, "Chris Rodriguez Jr.", "JAC", "RB"],
  [127, "Mark Andrews", "BAL", "TE"],
  [128, "Keaton Mitchell", "LAC", "RB"],
  [129, "Isiah Pacheco", "DET", "RB"],
  [130, "Brian Robinson Jr.", "ATL", "RB"],
  [131, "Tyler Allgeier", "ARI", "RB"],
  [132, "Emmett Johnson", "KC", "RB"],
  [133, "Zach Charbonnet", "SEA", "RB"],
  [134, "Nicholas Singleton", "TEN", "RB"],
  [135, "Jalen McMillan", "TB", "WR"],
  [136, "Dallas Goedert", "PHI", "TE"],
  [137, "Chig Okonkwo", "WAS", "TE"],
  [138, "Antonio Williams", "WAS", "WR"],
  [139, "Kaytron Allen", "WAS", "RB"],
  [140, "Dylan Sampson", "CLE", "RB"],
  [141, "Woody Marks", "HOU", "RB"],
  [142, "Braelon Allen", "NYJ", "RB"],
  [143, "Tank Bigsby", "PHI", "RB"],
  [144, "Jake Ferguson", "DAL", "TE"],
  [145, "Travis Hunter", "JAC", "WR"],
  [146, "Denzel Boston", "CLE", "WR"],
  [147, "Khalil Shakir", "BUF", "WR"],
  [148, "Hunter Henry", "NE", "TE"],
  [149, "Matthew Stafford", "LAR", "QB"],
  [150, "Tyler Shough", "NO", "QB"],
  [151, "Ray Davis", "BUF", "RB"],
  [152, "Tyjae Spears", "TEN", "RB"],
  [153, "Matthew Golden", "GB", "WR"],
  [154, "Rashid Shaheed", "SEA", "WR"],
  [155, "Emanuel Wilson", "SEA", "RB"],
  [156, "Sean Tucker", "TB", "RB"],
  [157, "Jalen Nailor", "LV", "WR"],
  [158, "Tre Tucker", "LV", "WR"],
  [159, "Jauan Jennings", "MIN", "WR"],
  [160, "Deebo Samuel Sr.", "FA", "WR"],
  [161, "Jared Goff", "DET", "QB"],
  [162, "Malik Willis", "MIA", "QB"],
  [163, "Baker Mayfield", "TB", "QB"],
  [164, "Jordan Love", "GB", "QB"],
  [165, "Brenton Strange", "JAC", "TE"],
  [166, "Demond Claiborne", "MIN", "RB"],
  [167, "Oronde Gadsden II", "LAC", "TE"],
  [168, "Mike Washington Jr.", "LV", "RB"],
  [169, "Jordan James", "SF", "RB"],
  [170, "Alvin Kamara", "NO", "RB"],
  [171, "Chris Brooks", "GB", "RB"],
  [172, "James Conner", "ARI", "RB"],
  [173, "Jerry Jeudy", "CLE", "WR"],
  [174, "Houston Texans", "HOU", "DST"],
  [175, "Kaelon Black", "SF", "RB"],
  [176, "Isaac TeSlaa", "DET", "WR"],
  [177, "Malik Washington", "MIA", "WR"],
  [178, "Ryan Flournoy", "DAL", "WR"],
  [179, "Tre' Harris", "LAC", "WR"],
  [180, "Zachariah Branch", "ATL", "WR"],
  [181, "Darnell Mooney", "NYG", "WR"],
  [182, "Jaylen Wright", "MIA", "RB"],
  [183, "Justice Hill", "BAL", "RB"],
  [184, "Seattle Seahawks", "SEA", "DST"],
  [185, "Brandon Aubrey", "DAL", "K"],
  [186, "Najee Harris", "LAC", "RB"],
  [187, "Jaydon Blue", "DAL", "RB"],
  [188, "Sam Darnold", "SEA", "QB"],
  [189, "Los Angeles Rams", "LAR", "DST"],
  [190, "Adonai Mitchell", "NYJ", "WR"],
  [191, "Kenyon Sadiq", "NYJ", "TE"],
  [192, "Juwan Johnson", "NO", "TE"],
  [193, "Dalton Schultz", "HOU", "TE"],
  [194, "Adam Randall", "BAL", "RB"],
  [195, "Kimani Vidal", "LAC", "RB"],
  [196, "Kendre Miller", "NO", "RB"],
  [197, "Devin Neal", "NO", "RB"],
  [198, "MarShawn Lloyd", "GB", "RB"],
  [199, "Ollie Gordon II", "MIA", "RB"],
  [200, "DJ Giddens", "IND", "RB"],
  [201, "C.J. Stroud", "HOU", "QB"],
  [202, "Denver Broncos", "DEN", "DST"],
  [203, "Philadelphia Eagles", "PHI", "DST"],
  [204, "Ka'imi Fairbairn", "HOU", "K"],
  [205, "Cam Ward", "TEN", "QB"],
  [206, "Daniel Jones", "IND", "QB"],
  [207, "Bryce Young", "CAR", "QB"],
  [208, "AJ Barner", "SEA", "TE"],
  [209, "George Holani", "SEA", "RB"],
  [210, "Malik Davis", "DAL", "RB"],
  [211, "LeQuint Allen Jr.", "JAC", "RB"],
  [212, "Malachi Fields", "NYG", "WR"],
  [213, "Germie Bernard", "PIT", "WR"],
  [214, "Calvin Ridley", "TEN", "WR"],
  [215, "De'Zhaun Stribling", "SF", "WR"],
  [216, "Ted Hurst III", "TB", "WR"],
  [217, "Tank Dell", "HOU", "WR"],
  [218, "Chris Bell", "MIA", "WR"],
  [219, "Pat Bryant", "DEN", "WR"],
  [220, "Troy Franklin", "DEN", "WR"],
  [221, "Brandon Aiyuk", "SF", "WR"],
  [222, "Tyreek Hill", "FA", "WR"],
  [223, "Jaylin Noel", "HOU", "WR"],
  [224, "Tory Horton", "SEA", "WR"],
  [225, "Elijah Sarratt", "BAL", "WR"],
  [226, "Ja'Kobi Lane", "BAL", "WR"],
  [227, "Fernando Mendoza", "LV", "QB"],
  [228, "T.J. Hockenson", "MIN", "TE"],
  [229, "New England Patriots", "NE", "DST"],
  [230, "Cam Little", "JAC", "K"],
  [231, "Pittsburgh Steelers", "PIT", "DST"],
  [232, "Gunnar Helm", "TEN", "TE"],
  [233, "Geno Smith", "NYJ", "QB"],
  [234, "Aaron Rodgers", "PIT", "QB"],
  [235, "Greg Dulcich", "MIA", "TE"],
  [236, "Eli Stowers", "PHI", "TE"],
  [237, "Terrance Ferguson", "LAR", "TE"],
  [238, "Skyler Bell", "BUF", "WR"],
  [239, "Cameron Dicker", "LAC", "K"],
  [240, "Jason Myers", "SEA", "K"],
  [241, "Jacksonville Jaguars", "JAC", "DST"],
  [242, "Eddy Pineiro", "SF", "K"],
  [243, "Dontayvion Wicks", "PHI", "WR"],
  [244, "Jahan Dotson", "ATL", "WR"],
  [245, "Hollywood Brown", "PHI", "WR"],
  [246, "Tyquan Thornton", "KC", "WR"],
  [247, "Keon Coleman", "BUF", "WR"],
  [248, "Rashod Bateman", "BAL", "WR"],
  [249, "Marvin Mims Jr.", "DEN", "WR"],
  [250, "Jalen Tolbert", "MIA", "WR"],
  [251, "Christian Kirk", "SF", "WR"],
  [252, "Treylon Burks", "WAS", "WR"],
  [253, "Konata Mumpfield", "LAR", "WR"],
  [254, "Harrison Mevis", "LAR", "K"],
  [255, "Minnesota Vikings", "MIN", "DST"],
  [256, "Baltimore Ravens", "BAL", "DST"],
  [257, "Detroit Lions", "DET", "DST"],
  [258, "Cairo Santos", "CHI", "K"],
  [259, "Buffalo Bills", "BUF", "DST"],
  [260, "Will Reichard", "MIN", "K"],
  [261, "Tyler Loop", "BAL", "K"],
  [262, "Jack Bech", "LV", "WR"],
  [263, "Chris Brazzell II", "CAR", "WR"],
  [264, "Caleb Douglas", "MIA", "WR"],
  [265, "Cooper Kupp", "SEA", "WR"],
  [266, "Jake Bates", "DET", "K"],
  [267, "Pat Freiermuth", "PIT", "TE"],
  [268, "Cade Otton", "TB", "TE"],
  [269, "David Njoku", "LAC", "TE"],
  [270, "Mike Gesicki", "CIN", "TE"],
  [271, "Jake Tonges", "SF", "TE"],
  [272, "Jacoby Brissett", "ARI", "QB"],
  [273, "Michael Penix Jr.", "ATL", "QB"],
  [274, "Deshaun Watson", "CLE", "QB"],
  [275, "Tua Tagovailoa", "ATL", "QB"],
  [276, "Shedeur Sanders", "CLE", "QB"],
  [277, "Isaiah Davis", "NYJ", "RB"],
  [278, "Tahj Brooks", "CIN", "RB"],
  [279, "Trey Benson", "ARI", "RB"],
  [280, "Will Shipley", "PHI", "RB"],
  [281, "Devin Singletary", "NYG", "RB"],
  [282, "Emari Demercado", "KC", "RB"],
  [283, "Kaleb Johnson", "PIT", "RB"],
  [284, "Samaje Perine", "CIN", "RB"],
  [285, "Eli Heidenreich", "PIT", "RB"],
  [286, "Trevor Etienne", "CAR", "RB"],
  [287, "Seth McGowan", "IND", "RB"],
  [288, "Carson Beck", "ARI", "QB"],
  [289, "Darius Slayton", "NYG", "WR"],
  [290, "Nick Westbrook-Ikhine", "IND", "WR"],
  [291, "Dyami Brown", "WAS", "WR"],
  [292, "Kirk Cousins", "LV", "QB"],
  [293, "Kayshon Boutte", "NE", "WR"],
  [294, "Jalen Royals", "KC", "WR"],
  [295, "Brenen Thompson", "LAC", "WR"],
  [296, "Keenan Allen", "LAC", "WR"],
  [297, "Savion Williams", "GB", "WR"],
  [298, "KaVontae Turpin", "DAL", "WR"],
  [299, "Brashard Smith", "KC", "RB"],
  [300, "Ty Johnson", "BUF", "RB"],
  [301, "Phil Mafah", "DAL", "RB"],
]


// ---------------------------------------------------------------------------
// HALF PPR — Dalton Del Don (The Deep Shot), updated 6/22
// FantasyPros in-season accuracy: #6 in 2025
// ---------------------------------------------------------------------------
const DEL_DON_HALF_PPR_UPDATED_ENTRIES = [
  'Jahmyr Gibbs|DET|RB',
  'Bijan Robinson|ATL|RB',
  "Ja'Marr Chase|CIN|WR",
  'Puka Nacua|LAR|WR',
  'Jaxon Smith-Njigba|SEA|WR',
  'Christian McCaffrey|SF|RB',
  'Jonathan Taylor|IND|RB',
  'Ashton Jeanty|LV|RB',
  'James Cook III|BUF|RB',
  'Amon-Ra St. Brown|DET|WR',
  'CeeDee Lamb|DAL|WR',
  'Chase Brown|CIN|RB',
  'Kenneth Walker III|KC|RB',
  'Drake London|ATL|WR',
  'Justin Jefferson|MIN|WR',
  'Omarion Hampton|LAC|RB',
  'Saquon Barkley|PHI|RB',
  'Brock Bowers|LV|TE',
  "De'Von Achane|MIA|RB",
  'Derrick Henry|BAL|RB',
  'A.J. Brown|NE|WR',
  'Nico Collins|HOU|WR',
  'Jeremiyah Love|ARI|RB',
  'Rashee Rice|KC|WR',
  'Trey McBride|ARI|TE',
  'George Pickens|DAL|WR',
  'DeVonta Smith|PHI|WR',
  'Zay Flowers|BAL|WR',
  'Kyren Williams|LAR|RB',
  'Travis Etienne Jr.|NO|RB',
  'Colston Loveland|CHI|TE',
  'Luther Burden III|CHI|WR',
  'Garrett Wilson|NYJ|WR',
  'Chris Olave|NO|WR',
  'Breece Hall|NYJ|RB',
  'Lamar Jackson|BAL|QB',
  'Josh Allen|BUF|QB',
  'Tee Higgins|CIN|WR',
  'Malik Nabers|NYG|WR',
  'Emeka Egbuka|TB|WR',
  'Terry McLaurin|WAS|WR',
  'Tetairoa McMillan|CAR|WR',
  'Ladd McConkey|LAC|WR',
  'Christian Watson|GB|WR',
  'Mike Evans|SF|WR',
  'Rome Odunze|CHI|WR',
  'Jaylen Waddle|DEN|WR',
  'Davante Adams|LAR|WR',
  'Javonte Williams|DAL|RB',
  'Josh Jacobs|GB|RB',
  'David Montgomery|HOU|RB',
  'Cam Skattebo|NYG|RB',
  'Bhayshul Tuten|JAC|RB',
  'TreVeyon Henderson|NE|RB',
  "D'Andre Swift|CHI|RB",
  'Quinshon Judkins|CLE|RB',
  'Bucky Irving|TB|RB',
  'Jayden Daniels|WAS|QB',
  'Drake Maye|NE|QB',
  'Joe Burrow|CIN|QB',
  'Jordyn Tyson|NO|WR',
  'Jameson Williams|DET|WR',
  'Brian Thomas Jr.|JAC|WR',
  'Tyler Warren|IND|TE',
  'DJ Moore|BUF|WR',
  'Marvin Harrison Jr.|ARI|WR',
  'Tucker Kraft|GB|TE',
  'Harold Fannin Jr.|CLE|TE',
  'Jaylen Warren|PIT|RB',
  'Rhamondre Stevenson|NE|RB',
  'Caleb Williams|CHI|QB',
  'Jalen Hurts|PHI|QB',
  'Parker Washington|JAC|WR',
  'Carnell Tate|TEN|WR',
  'Chris Godwin Jr.|TB|WR',
  'Quentin Johnston|LAC|WR',
  'Makai Lemon|PHI|WR',
  'Alec Pierce|IND|WR',
  'DK Metcalf|PIT|WR',
  'Trevor Lawrence|JAC|QB',
  'Tony Pollard|TEN|RB',
  'Jonathon Brooks|CAR|RB',
  'Blake Corum|LAR|RB',
  'Jadarian Price|SEA|RB',
  'Sam LaPorta|DET|TE',
  'George Kittle|SF|TE',
  'Justin Herbert|LAC|QB',
  'Brock Purdy|SF|QB',
  'Jaxson Dart|NYG|QB',
  'RJ Harvey|DEN|RB',
  'Chuba Hubbard|CAR|RB',
  'Jayden Reed|GB|WR',
  'Courtland Sutton|DEN|WR',
  'Dak Prescott|DAL|QB',
  'Kyler Murray|MIN|QB',
  'Michael Wilson|ARI|WR',
  'Josh Downs|IND|WR',
  'Ricky Pearsall|SF|WR',
  'Xavier Worthy|KC|WR',
  'Dalton Kincaid|BUF|TE',
  'Matthew Golden|GB|WR',
  'Jalen Coker|CAR|WR',
  'Patrick Mahomes II|KC|QB',
  'Kyle Pitts Sr.|ATL|TE',
  'Kyle Monangai|CHI|RB',
  'J.K. Dobbins|DEN|RB',
  'Rico Dowdle|PIT|RB',
  'Kenny Gainwell|TB|RB'
] as const

const DEL_DON_HALF_PPR_RAW: RawPlayer[] = buildRawFromEntries(BOONE_RAW, DEL_DON_HALF_PPR_UPDATED_ENTRIES)

// ---------------------------------------------------------------------------
// FULL PPR — Andrew Erickson (FantasyPros), updated 6/18
// FantasyPros draft accuracy: #5 in 2024
// ---------------------------------------------------------------------------
const ERICKSON_BASE_RAW: RawPlayer[] = [
  [1, "Ja'Marr Chase", "CIN", "WR"],
  [2, "Jahmyr Gibbs", "DET", "RB"],
  [3, "Puka Nacua", "LAR", "WR"],
  [4, "Jaxon Smith-Njigba", "SEA", "WR"],
  [5, "Bijan Robinson", "ATL", "RB"],
  [6, "Amon-Ra St. Brown", "DET", "WR"],
  [7, "James Cook III", "BUF", "RB"],
  [8, "A.J. Brown", "NE", "WR"],
  [9, "Justin Jefferson", "MIN", "WR"],
  [10, "Jonathan Taylor", "IND", "RB"],
  [11, "CeeDee Lamb", "DAL", "WR"],
  [12, "Rashee Rice", "KC", "WR"],
  [13, "Chase Brown", "CIN", "RB"],
  [14, "Drake London", "ATL", "WR"],
  [15, "Nico Collins", "HOU", "WR"],
  [16, "Trey McBride", "ARI", "TE"],
  [17, "Ashton Jeanty", "LV", "RB"],
  [18, "George Pickens", "DAL", "WR"],
  [19, "Zay Flowers", "BAL", "WR"],
  [20, "Tetairoa McMillan", "CAR", "WR"],
  [21, "Omarion Hampton", "LAC", "RB"],
  [22, "Brock Bowers", "LV", "TE"],
  [23, "De'Von Achane", "MIA", "RB"],
  [24, "Kenneth Walker III", "KC", "RB"],
  [25, "Drake Maye", "NE", "QB"],
  [26, "Chris Olave", "NO", "WR"],
  [27, "Josh Allen", "BUF", "QB"],
  [28, "Garrett Wilson", "NYJ", "WR"],
  [29, "DeVonta Smith", "PHI", "WR"],
  [30, "Lamar Jackson", "BAL", "QB"],
  [31, "Christian McCaffrey", "SF", "RB"],
  [32, "Colston Loveland", "CHI", "TE"],
  [33, "Saquon Barkley", "PHI", "RB"],
  [34, "Javonte Williams", "DAL", "RB"],
  [35, "Ladd McConkey", "LAC", "WR"],
  [36, "Malik Nabers", "NYG", "WR"],
  [37, "Jayden Daniels", "WAS", "QB"],
  [38, "Jaylen Waddle", "DEN", "WR"],
  [39, "Jeremiyah Love", "ARI", "RB"],
  [40, "Tee Higgins", "CIN", "WR"],
  [41, "Breece Hall", "NYJ", "RB"],
  [42, "Terry McLaurin", "WAS", "WR"],
  [43, "Travis Etienne Jr.", "NO", "RB"],
  [44, "Emeka Egbuka", "TB", "WR"],
  [45, "Carnell Tate", "TEN", "WR"],
  [46, "Derrick Henry", "BAL", "RB"],
  [47, "Cam Skattebo", "NYG", "RB"],
  [48, "Luther Burden III", "CHI", "WR"],
  [49, "DJ Moore", "BUF", "WR"],
  [50, "Kyren Williams", "LAR", "RB"],
  [51, "Mike Evans", "SF", "WR"],
  [52, "Marvin Harrison Jr.", "ARI", "WR"],
  [53, "Bucky Irving", "TB", "RB"],
  [54, "Joe Burrow", "CIN", "QB"],
  [55, "Christian Watson", "GB", "WR"],
  [56, "Josh Jacobs", "GB", "RB"],
  [57, "Tyler Warren", "IND", "TE"],
  [58, "Quinshon Judkins", "CLE", "RB"],
  [59, "Justin Herbert", "LAC", "QB"],
  [60, "Alec Pierce", "IND", "WR"],
  [61, "David Montgomery", "HOU", "RB"],
  [62, "Rome Odunze", "CHI", "WR"],
  [63, "Caleb Williams", "CHI", "QB"],
  [64, "Jameson Williams", "DET", "WR"],
  [65, "TreVeyon Henderson", "NE", "RB"],
  [66, "Tucker Kraft", "GB", "TE"],
  [67, "RJ Harvey", "DEN", "RB"],
  [68, "Michael Pittman Jr.", "PIT", "WR"],
  [69, "Jordyn Tyson", "NO", "WR"],
  [70, "Jaxson Dart", "NYG", "QB"],
  [71, "Makai Lemon", "PHI", "WR"],
  [72, "Rachaad White", "WAS", "RB"],
  [73, "Harold Fannin Jr.", "CLE", "TE"],
  [74, "Jalen Hurts", "PHI", "QB"],
  [75, "Jaylen Warren", "PIT", "RB"],
  [76, "Josh Downs", "IND", "WR"],
  [77, "Bhayshul Tuten", "JAC", "RB"],
  [78, "Rico Dowdle", "PIT", "RB"],
  [79, "Brock Purdy", "SF", "QB"],
  [80, "Jadarian Price", "SEA", "RB"],
  [81, "Davante Adams", "LAR", "WR"],
  [82, "Jakobi Meyers", "JAC", "WR"],
  [83, "DK Metcalf", "PIT", "WR"],
  [84, "D'Andre Swift", "CHI", "RB"],
  [85, "Kyle Pitts Sr.", "ATL", "TE"],
  [86, "Rhamondre Stevenson", "NE", "RB"],
  [87, "Sam LaPorta", "DET", "TE"],
  [88, "KC Concepcion", "CLE", "WR"],
  [89, "Chuba Hubbard", "CAR", "RB"],
  [90, "Courtland Sutton", "DEN", "WR"],
  [91, "Wan'Dale Robinson", "TEN", "WR"],
  [92, "Trevor Lawrence", "JAC", "QB"],
  [93, "Kenneth Gainwell", "TB", "RB"],
  [94, "Ricky Pearsall", "SF", "WR"],
  [95, "Isaiah Likely", "NYG", "TE"],
  [96, "Chris Godwin Jr.", "TB", "WR"],
  [97, "Dalton Kincaid", "BUF", "TE"],
  [98, "Dak Prescott", "DAL", "QB"],
  [99, "Aaron Jones Sr.", "MIN", "RB"],
  [100, "Parker Washington", "JAC", "WR"],
  [101, "Bo Nix", "DEN", "QB"],
  [102, "Tony Pollard", "TEN", "RB"],
  [103, "Kyle Monangai", "CHI", "RB"],
  [104, "Patrick Mahomes II", "KC", "QB"],
  [105, "Jordan Love", "GB", "QB"],
  [106, "George Kittle", "SF", "TE"],
  [107, "Jayden Reed", "GB", "WR"],
  [108, "Kyler Murray", "MIN", "QB"],
  [109, "Brian Thomas Jr.", "JAC", "WR"],
  [110, "Michael Wilson", "ARI", "WR"],
  [111, "Chig Okonkwo", "WAS", "TE"],
  [112, "Travis Kelce", "KC", "TE"],
  [113, "Malik Willis", "MIA", "QB"],
  [114, "Baker Mayfield", "TB", "QB"],
  [115, "Xavier Worthy", "KC", "WR"],
  [116, "Jayden Higgins", "HOU", "WR"],
  [117, "J.K. Dobbins", "DEN", "RB"],
  [118, "Jonathon Brooks", "CAR", "RB"],
  [119, "Jared Goff", "DET", "QB"],
  [120, "Blake Corum", "LAR", "RB"],
  [121, "Jordan Addison", "MIN", "WR"],
  [122, "Jacory Croskey-Merritt", "WAS", "RB"],
  [123, "Romeo Doubs", "NE", "WR"],
  [124, "Greg Dulcich", "MIA", "TE"],
  [125, "Omar Cooper Jr.", "NYJ", "WR"],
  [126, "Khalil Shakir", "BUF", "WR"],
  [127, "Tyler Shough", "NO", "QB"],
  [128, "Emanuel Wilson", "SEA", "RB"],
  [129, "Dallas Goedert", "PHI", "TE"],
  [130, "Tyler Allgeier", "ARI", "RB"],
  [131, "Jalen Coker", "CAR", "WR"],
  [132, "C.J. Stroud", "HOU", "QB"],
  [133, "Jordan Mason", "MIN", "RB"],
  [134, "Denzel Boston", "CLE", "WR"],
  [135, "Matthew Golden", "GB", "WR"],
  [136, "Kenyon Sadiq", "NYJ", "TE"],
  [137, "Cam Ward", "TEN", "QB"],
  [138, "Antonio Williams", "WAS", "WR"],
  [139, "Isiah Pacheco", "DET", "RB"],
  [140, "Quentin Johnston", "LAC", "WR"],
  [141, "Tyrone Tracy Jr.", "NYG", "RB"],
  [142, "Brenton Strange", "JAC", "TE"],
  [143, "Nicholas Singleton", "TEN", "RB"],
  [144, "Jonah Coleman", "DEN", "RB"],
  [145, "Bryce Young", "CAR", "QB"],
  [146, "Zach Charbonnet", "SEA", "RB"],
  [147, "Stefon Diggs", "FA", "WR"],
  [148, "Jaylin Noel", "HOU", "WR"],
  [149, "Houston Texans", "HOU", "DST"],
  [150, "Brian Robinson Jr.", "ATL", "RB"],
  [151, "Geno Smith", "NYJ", "QB"],
  [152, "Germie Bernard", "PIT", "WR"],
  [153, "Mark Andrews", "BAL", "TE"],
  [154, "Tyjae Spears", "TEN", "RB"],
  [155, "Alvin Kamara", "NO", "RB"],
  [156, "Jake Ferguson", "DAL", "TE"],
  [157, "Daniel Jones", "IND", "QB"],
  [158, "Emmett Johnson", "KC", "RB"],
  [159, "Seattle Seahawks", "SEA", "DST"],
  [160, "Keaton Mitchell", "LAC", "RB"],
  [161, "Rashid Shaheed", "SEA", "WR"],
  [162, "MarShawn Lloyd", "GB", "RB"],
  [163, "Jerry Jeudy", "CLE", "WR"],
  [164, "Travis Hunter", "JAC", "WR"],
  [165, "Los Angeles Rams", "LAR", "DST"],
  [166, "Jalen McMillan", "TB", "WR"],
  [167, "Kaytron Allen", "WAS", "RB"],
  [168, "Chris Bell", "MIA", "WR"],
  [169, "Los Angeles Chargers", "LAC", "DST"],
  [170, "Philadelphia Eagles", "PHI", "DST"],
  [171, "AJ Barner", "SEA", "TE"],
  [172, "Darnell Mooney", "NYG", "WR"],
  [173, "Tank Bigsby", "PHI", "RB"],
  [174, "Elijah Sarratt", "BAL", "WR"],
  [175, "Chris Brooks", "GB", "RB"],
  [176, "Ted Hurst III", "TB", "WR"],
  [177, "Sam Darnold", "SEA", "QB"],
  [178, "Jauan Jennings", "MIN", "WR"],
  [179, "Hunter Henry", "NE", "TE"],
  [180, "Sean Tucker", "TB", "RB"],
  [181, "Denver Broncos", "DEN", "DST"],
  [182, "Tre Tucker", "LV", "WR"],
  [183, "Detroit Lions", "DET", "DST"],
  [184, "Baltimore Ravens", "BAL", "DST"],
  [185, "Brandon Aubrey", "DAL", "K"],
  [186, "Minnesota Vikings", "MIN", "DST"],
  [187, "Jordan James", "SF", "RB"],
  [188, "Kansas City Chiefs", "KC", "DST"],
  [189, "Jacksonville Jaguars", "JAC", "DST"],
  [190, "Ka'imi Fairbairn", "HOU", "K"],
  [191, "Cam Little", "JAC", "K"],
  [192, "Pittsburgh Steelers", "PIT", "DST"],
  [193, "Isaac TeSlaa", "DET", "WR"],
  [194, "T.J. Hockenson", "MIN", "TE"],
  [195, "Tre' Harris", "LAC", "WR"],
  [196, "Cameron Dicker", "LAC", "K"],
  [197, "De'Zhaun Stribling", "SF", "WR"],
  [198, "Evan McPherson", "CIN", "K"],
  [199, "Braelon Allen", "NYJ", "RB"],
  [200, "Brandon Aiyuk", "SF", "WR"],
  [201, "Dalton Schultz", "HOU", "TE"],
  [202, "Jason Myers", "SEA", "K"],
  [203, "Malachi Fields", "NYG", "WR"],
  [204, "New England Patriots", "NE", "DST"],
  [205, "Andy Borregales", "NE", "K"],
  [206, "Kayshon Boutte", "NE", "WR"],
  [207, "Juwan Johnson", "NO", "TE"],
  [208, "Calvin Ridley", "TEN", "WR"],
  [209, "Tyler Loop", "BAL", "K"],
  [210, "Green Bay Packers", "GB", "DST"],
  [211, "Eddy Pineiro", "SF", "K"],
  [212, "Fernando Mendoza", "LV", "QB"],
  [213, "Chase McLaughlin", "TB", "K"],
  [214, "Cairo Santos", "CHI", "K"],
  [215, "Harrison Mevis", "LAR", "K"],
  [216, "Zachariah Branch", "ATL", "WR"],
  [217, "Ray Davis", "BUF", "RB"],
  [218, "Buffalo Bills", "BUF", "DST"],
  [219, "Malik Washington", "MIA", "WR"],
  [220, "LeQuint Allen Jr.", "JAC", "RB"],
  [221, "Pat Bryant", "DEN", "WR"],
  [222, "Adonai Mitchell", "NYJ", "WR"],
  [223, "Chris Brazzell II", "CAR", "WR"],
  [224, "Gunnar Helm", "TEN", "TE"],
  [225, "Dontayvion Wicks", "PHI", "WR"],
  [226, "Woody Marks", "HOU", "RB"],
  [227, "Oronde Gadsden II", "LAC", "TE"],
  [228, "Jalen Nailor", "LV", "WR"],
  [229, "Mike Washington Jr.", "LV", "RB"],
  [230, "Chimere Dike", "TEN", "WR"],
  [231, "DJ Giddens", "IND", "RB"],
  [232, "Samaje Perine", "CIN", "RB"],
  [233, "Atlanta Falcons", "ATL", "DST"],
  [234, "Terrance Ferguson", "LAR", "TE"],
  [235, "Chris Rodriguez Jr.", "JAC", "RB"],
  [236, "Demond Claiborne", "MIN", "RB"],
  [237, "Devaughn Vele", "NO", "WR"],
  [238, "Jake Bates", "DET", "K"],
  [239, "Cyrus Allen", "KC", "WR"],
  [240, "Aaron Rodgers", "PIT", "QB"],
  [241, "Kimani Vidal", "LAC", "RB"],
  [242, "Tyreek Hill", "FA", "WR"],
  [243, "Deebo Samuel Sr.", "FA", "WR"],
  [244, "David Njoku", "LAC", "TE"],
  [245, "Marvin Mims Jr.", "DEN", "WR"],
  [246, "Ollie Gordon II", "MIA", "RB"],
  [247, "Tennessee Titans", "TEN", "DST"],
  [248, "Charlie Smyth", "NO", "K"],
  [249, "Justice Hill", "BAL", "RB"],
  [250, "Chris Boswell", "PIT", "K"],
  [251, "Wil Lutz", "DEN", "K"],
  [252, "Jake Tonges", "SF", "TE"],
  [253, "Tua Tagovailoa", "ATL", "QB"],
  [254, "Pat Freiermuth", "PIT", "TE"],
  [255, "Kaleb Johnson", "PIT", "RB"],
  [256, "Rashod Bateman", "BAL", "WR"],
  [257, "Cade Otton", "TB", "TE"],
  [258, "Trey Benson", "ARI", "RB"],
  [259, "Mike Gesicki", "CIN", "TE"],
  [260, "Troy Franklin", "DEN", "WR"],
  [261, "Jaylen Wright", "MIA", "RB"],
  [262, "Tank Dell", "HOU", "WR"],
  [263, "Ryan Flournoy", "DAL", "WR"],
  [264, "James Conner", "ARI", "RB"],
  [265, "Keenan Allen", "LAC", "WR"],
  [266, "Darnell Washington", "PIT", "TE"],
  [267, "DeMario Douglas", "NE", "WR"],
  [268, "Keon Coleman", "BUF", "WR"],
  [269, "Najee Harris", "LAC", "RB"],
  [270, "Andrei Iosivas", "CIN", "WR"],
  [271, "Konata Mumpfield", "LAR", "WR"],
  [272, "Eli Stowers", "PHI", "TE"],
  [273, "Jaydon Blue", "DAL", "RB"],
  [274, "Deshaun Watson", "CLE", "QB"],
  [275, "Cooper Kupp", "SEA", "WR"],
  [276, "Kaelon Black", "SF", "RB"],
  [277, "San Francisco 49ers", "SF", "DST"],
  [278, "Las Vegas Raiders", "LV", "DST"],
  [279, "Theo Johnson", "NYG", "TE"],
  [280, "Harrison Butker", "KC", "K"],
  [281, "Eli Heidenreich", "PIT", "RB"],
  [282, "Emari Demercado", "KC", "RB"],
  [283, "Michael Penix Jr.", "ATL", "QB"],
  [284, "Kyle Williams", "NE", "WR"],
  [285, "Bryce Lance", "NO", "WR"],
  [286, "Jaleel McLaughlin", "DEN", "RB"],
  [287, "Mack Hollins", "NE", "WR"],
  [288, "Evan Engram", "DEN", "TE"],
  [289, "Christian Kirk", "SF", "WR"],
  [290, "George Holani", "SEA", "RB"],
  [291, "Elic Ayomanor", "TEN", "WR"],
  [292, "Brashard Smith", "KC", "RB"],
  [293, "Ja'Tavion Sanders", "CAR", "TE"],
  [294, "Kevin Coleman Jr.", "MIA", "WR"],
  [295, "Seth McGowan", "IND", "RB"],
  [296, "Skyler Bell", "BUF", "WR"],
  [297, "Tutu Atwell", "MIA", "WR"],
  [298, "Colby Parkinson", "LAR", "TE"],
  [299, "Bam Knight", "ARI", "RB"],
  [300, "Darius Slayton", "NYG", "WR"],
  [301, "Tyquan Thornton", "KC", "WR"],
  [302, "Adam Randall", "BAL", "RB"],
  [303, "CJ Daniels", "LAR", "WR"],
  [304, "Dawson Knox", "BUF", "TE"],
  [305, "Ja'Kobi Lane", "BAL", "WR"],
  [306, "Jacoby Brissett", "ARI", "QB"],
  [307, "Mason Taylor", "NYJ", "TE"],
  [308, "Jerome Ford", "WAS", "RB"],
  [309, "Isaiah Davis", "NYJ", "RB"],
  [310, "Jack Bech", "LV", "WR"],
  [311, "J'Mari Taylor", "JAC", "RB"],
  [312, "Kareem Hunt", "FA", "RB"],
  [313, "Brenen Thompson", "LAC", "WR"],
  [314, "Jalen Royals", "KC", "WR"],
  [315, "Ty Johnson", "BUF", "RB"],
  [316, "Devin Neal", "NO", "RB"],
  [317, "Savion Williams", "GB", "WR"],
  [318, "Eli Raridon", "NE", "TE"],
  [319, "Shedeur Sanders", "CLE", "QB"],
  [320, "Trevor Etienne", "CAR", "RB"],
  [321, "Cedric Tillman", "CLE", "WR"],
  [322, "Kirk Cousins", "LV", "QB"],
  [323, "Oscar Delp", "NO", "TE"],
  [324, "Kendre Miller", "NO", "RB"],
  [325, "Devin Singletary", "NYG", "RB"],
  [326, "Hollywood Brown", "PHI", "WR"],
  [327, "Malik Davis", "DAL", "RB"],
  [328, "Tahj Brooks", "CIN", "RB"],
  [329, "Tory Horton", "SEA", "WR"],
  [330, "Zane Gonzalez", "MIA", "K"],
  [331, "Jaylin Lane", "WAS", "WR"],
  [332, "J.J. McCarthy", "MIN", "QB"],
  [333, "Marlin Klein", "HOU", "TE"],
  [334, "Carson Beck", "ARI", "QB"],
  [335, "Kendrick Bourne", "ARI", "WR"],
  [336, "Kalif Raymond", "CHI", "WR"],
  [337, "Elijah Arroyo", "SEA", "TE"],
  [338, "Tez Johnson", "TB", "WR"],
  [339, "Max Klare", "LAR", "TE"],
  [340, "Luke McCaffrey", "WAS", "WR"],
  [341, "Jalen Tolbert", "MIA", "WR"],
  [342, "Anthony Richardson Sr.", "IND", "QB"],
  [343, "Noah Fant", "NO", "TE"],
  [344, "Calvin Austin III", "NYG", "WR"],
  [345, "Isaiah Bond", "CLE", "WR"],
  [346, "Michael Mayer", "LV", "TE"],
  [347, "Tommy Tremble", "CAR", "TE"],
  [348, "Cole Kmet", "CHI", "TE"],
  [349, "New Orleans Saints", "NO", "DST"],
  [350, "Justin Joly", "DEN", "TE"],
  [351, "Mac Jones", "SF", "QB"],
  [352, "Nate Boerkircher", "JAC", "TE"],
  [353, "Luke Musgrave", "GB", "TE"],
  [354, "Tyler Higbee", "LAR", "TE"],
  [355, "Cade Klubnik", "NYJ", "QB"],
  [356, "Darren Waller", "FA", "TE"],
  [357, "Noah Gray", "KC", "TE"],
  [358, "Jared Wiley", "KC", "TE"],
  [359, "Sam Roush", "CHI", "TE"],
  [360, "Justin Fields", "KC", "QB"],
  [361, "Ty Simpson", "LAR", "QB"],
  [362, "Ben Sinnott", "WAS", "TE"],
  [363, "Gardner Minshew II", "ARI", "QB"],
]



const ERICKSON_6_18_PPR_ENTRIES = [
  "Ja'Marr Chase|CIN|WR",
  'Jahmyr Gibbs|DET|RB',
  'Puka Nacua|LAR|WR',
  'Jaxon Smith-Njigba|SEA|WR',
  'Bijan Robinson|ATL|RB',
  'Amon-Ra St. Brown|DET|WR',
  'James Cook III|BUF|RB',
  'A.J. Brown|NE|WR',
  'Justin Jefferson|MIN|WR',
  'Jonathan Taylor|IND|RB',
  'CeeDee Lamb|DAL|WR',
  'Rashee Rice|KC|WR',
  'Chase Brown|CIN|RB',
  'Drake London|ATL|WR',
  'Nico Collins|HOU|WR',
  'Trey McBride|ARI|TE',
  'Ashton Jeanty|LV|RB',
  'George Pickens|DAL|WR',
  'Zay Flowers|BAL|WR',
  'Tetairoa McMillan|CAR|WR',
  'Omarion Hampton|LAC|RB',
  'Brock Bowers|LV|TE',
  "De'Von Achane|MIA|RB",
  'Kenneth Walker III|KC|RB',
  'Drake Maye|NE|QB',
  'Chris Olave|NO|WR',
  'Josh Allen|BUF|QB',
  'DeVonta Smith|PHI|WR',
  'Garrett Wilson|NYJ|WR',
  'Lamar Jackson|BAL|QB',
  'Christian McCaffrey|SF|RB',
  'Colston Loveland|CHI|TE',
  'Saquon Barkley|PHI|RB',
  'Javonte Williams|DAL|RB',
  'Ladd McConkey|LAC|WR',
  'Malik Nabers|NYG|WR',
  'Jayden Daniels|WAS|QB',
  'Jaylen Waddle|DEN|WR',
  'Jeremiyah Love|ARI|RB',
  'Tee Higgins|CIN|WR',
  'Breece Hall|NYJ|RB',
  'Terry McLaurin|WAS|WR',
  'Travis Etienne Jr.|NO|RB',
  'Carnell Tate|TEN|WR',
  'Emeka Egbuka|TB|WR',
  'Derrick Henry|BAL|RB',
  'Cam Skattebo|NYG|RB',
  'Luther Burden III|CHI|WR',
  'Mike Evans|SF|WR',
  'Kyren Williams|LAR|RB',
  'DJ Moore|BUF|WR',
  'Christian Watson|GB|WR',
  'Bucky Irving|TB|RB',
  'Joe Burrow|CIN|QB',
  'Marvin Harrison Jr.|ARI|WR',
  'Josh Jacobs|GB|RB',
  'Tyler Warren|IND|TE',
  'David Montgomery|HOU|RB',
  'Justin Herbert|LAC|QB',
  'Rome Odunze|CHI|WR',
  'Quinshon Judkins|CLE|RB',
  'Alec Pierce|IND|WR',
  'Caleb Williams|CHI|QB',
  'Jameson Williams|DET|WR',
  'TreVeyon Henderson|NE|RB',
  'Tucker Kraft|GB|TE',
  'RJ Harvey|DEN|RB',
  'Michael Pittman Jr.|PIT|WR',
  'Jordyn Tyson|NO|WR',
  'Jaxson Dart|NYG|QB',
  'Makai Lemon|PHI|WR',
  'Rachaad White|WAS|RB',
  'Harold Fannin Jr.|CLE|TE',
  'Jalen Hurts|PHI|QB',
  'Jaylen Warren|PIT|RB',
  'Josh Downs|IND|WR',
  'Bhayshul Tuten|JAC|RB',
  'Rico Dowdle|PIT|RB',
  'Trevor Lawrence|JAC|QB',
  'Jadarian Price|SEA|RB',
  'Davante Adams|LAR|WR',
  'Jakobi Meyers|JAC|WR',
  'DK Metcalf|PIT|WR',
  "D'Andre Swift|CHI|RB",
  'Kyle Pitts Sr.|ATL|TE',
  'Rhamondre Stevenson|NE|RB',
  'Sam LaPorta|DET|TE',
  'KC Concepcion|CLE|WR',
  'Tony Pollard|TEN|RB',
  'Courtland Sutton|DEN|WR',
  "Wan'Dale Robinson|TEN|WR",
  'Brock Purdy|SF|QB',
  'Chuba Hubbard|CAR|RB',
  'Ricky Pearsall|SF|WR',
  'Isaiah Likely|NYG|TE',
  'Chris Godwin Jr.|TB|WR',
  'Dalton Kincaid|BUF|TE',
  'Dak Prescott|DAL|QB',
  'Jonathon Brooks|CAR|RB',
  'Parker Washington|JAC|WR',
  'Bo Nix|DEN|QB',
  'Kenny Gainwell|TB|RB'
] as const

const ERICKSON_RAW: RawPlayer[] = buildRawFromEntries(ERICKSON_BASE_RAW, ERICKSON_6_18_PPR_ENTRIES)

// ---------------------------------------------------------------------------
// FULL PPR — Dalton Del Don (The Deep Shot), updated 6/22
// FantasyPros in-season accuracy: #6 in 2025
// ---------------------------------------------------------------------------
const DEL_DON_6_22_PPR_ENTRIES = [
  "Ja'Marr Chase|CIN|WR",
  'Jahmyr Gibbs|DET|RB',
  'Puka Nacua|LAR|WR',
  'Jaxon Smith-Njigba|SEA|WR',
  'Bijan Robinson|ATL|RB',
  'Amon-Ra St. Brown|DET|WR',
  'Christian McCaffrey|SF|RB',
  'CeeDee Lamb|DAL|WR',
  'Drake London|ATL|WR',
  'Jonathan Taylor|IND|RB',
  'Justin Jefferson|MIN|WR',
  'A.J. Brown|NE|WR',
  'Ashton Jeanty|LV|RB',
  'Nico Collins|HOU|WR',
  'Rashee Rice|KC|WR',
  'Trey McBride|ARI|TE',
  'Chase Brown|CIN|RB',
  'George Pickens|DAL|WR',
  'DeVonta Smith|PHI|WR',
  'Zay Flowers|BAL|WR',
  'James Cook III|BUF|RB',
  'Brock Bowers|LV|TE',
  'Kenneth Walker III|KC|RB',
  'Omarion Hampton|LAC|RB',
  'Lamar Jackson|BAL|QB',
  'Garrett Wilson|NYJ|WR',
  'Josh Allen|BUF|QB',
  'Luther Burden III|CHI|WR',
  'Chris Olave|NO|WR',
  'Jayden Daniels|WAS|QB',
  "De'Von Achane|MIA|RB",
  'Colston Loveland|CHI|TE',
  'Saquon Barkley|PHI|RB',
  'Jeremiyah Love|ARI|RB',
  'Tee Higgins|CIN|WR',
  'Malik Nabers|NYG|WR',
  'Drake Maye|NE|QB',
  'Terry McLaurin|WAS|WR',
  'Travis Etienne Jr.|NO|RB',
  'Tetairoa McMillan|CAR|WR',
  'Derrick Henry|BAL|RB',
  'Ladd McConkey|LAC|WR',
  'Breece Hall|NYJ|RB',
  'Emeka Egbuka|TB|WR',
  'Jaylen Waddle|DEN|WR',
  'Kyren Williams|LAR|RB',
  'Javonte Williams|DAL|RB',
  'Jordyn Tyson|NO|WR',
  'Mike Evans|SF|WR',
  'Cam Skattebo|NYG|RB',
  'Christian Watson|GB|WR',
  'Rome Odunze|CHI|WR',
  'David Montgomery|HOU|RB',
  'Joe Burrow|CIN|QB',
  'Davante Adams|LAR|WR',
  'Josh Jacobs|GB|RB',
  'Tyler Warren|IND|TE',
  'Bhayshul Tuten|JAC|RB',
  'Caleb Williams|CHI|QB',
  'Jameson Williams|DET|WR',
  'TreVeyon Henderson|NE|RB',
  'DJ Moore|BUF|WR',
  'Jalen Hurts|PHI|QB',
  'Brian Thomas Jr.|JAC|WR',
  'Jaylen Warren|PIT|RB',
  'Harold Fannin Jr.|CLE|TE',
  'Bucky Irving|TB|RB',
  'Marvin Harrison Jr.|ARI|WR',
  'Carnell Tate|TEN|WR',
  'Trevor Lawrence|JAC|QB',
  'Chris Godwin Jr.|TB|WR',
  "D'Andre Swift|CHI|RB",
  'Tucker Kraft|GB|TE',
  'Justin Herbert|LAC|QB',
  'Quinshon Judkins|CLE|RB',
  'Parker Washington|JAC|WR',
  'Rhamondre Stevenson|NE|RB',
  'Jonathon Brooks|CAR|RB',
  'Brock Purdy|SF|QB',
  'Tony Pollard|TEN|RB',
  'Josh Downs|IND|WR',
  'Makai Lemon|PHI|WR',
  'Quentin Johnston|LAC|WR',
  'RJ Harvey|DEN|RB',
  'Sam LaPorta|DET|TE',
  'Jadarian Price|SEA|RB',
  'George Kittle|SF|TE',
  'Michael Wilson|ARI|WR',
  'Blake Corum|LAR|RB',
  'Jayden Reed|GB|WR',
  'Courtland Sutton|DEN|WR',
  'Jaxson Dart|NYG|QB',
  'Kenny Gainwell|TB|RB',
  'Alec Pierce|IND|WR',
  'Kyle Pitts Sr.|ATL|TE',
  'DK Metcalf|PIT|WR',
  'Dalton Kincaid|BUF|TE',
  'Dak Prescott|DAL|QB',
  'Chuba Hubbard|CAR|RB',
  'Ricky Pearsall|SF|WR'
] as const

const DEL_DON_RAW: RawPlayer[] = buildRawFromEntries(ERICKSON_RAW, DEL_DON_6_22_PPR_ENTRIES)


// ---------------------------------------------------------------------------
// HYBRID FULL PPR — accuracy-weighted by position
// Non-TE ranks start from Dalton Del Don; TE ranks use James Emrick-Wilson
// because his 2025 in-season TE accuracy rank was #5.
// James is intentionally not exposed as a standalone preset.
// ---------------------------------------------------------------------------
const EMRICK_WILSON_TE_RAW: RawPlayer[] = [
  [16, "Trey McBride", "ARI", "TE"],
  [22, "Brock Bowers", "LV", "TE"],
  [32, "Colston Loveland", "CHI", "TE"],
  [57, "Harold Fannin Jr.", "CLE", "TE"],
  [66, "Tucker Kraft", "GB", "TE"],
  [73, "Tyler Warren", "IND", "TE"],
  [85, "Sam LaPorta", "DET", "TE"],
  [87, "Kyle Pitts Sr.", "ATL", "TE"],
  [95, "Jake Ferguson", "DAL", "TE"],
  [97, "Oronde Gadsden II", "LAC", "TE"],
  [106, "Brenton Strange", "JAC", "TE"],
  [111, "Travis Kelce", "KC", "TE"],
  [112, "Isaiah Likely", "NYG", "TE"],
  [124, "Juwan Johnson", "NO", "TE"],
  [131, "Mark Andrews", "BAL", "TE"],
  [138, "Dalton Schultz", "HOU", "TE"],
  [144, "Dallas Goedert", "PHI", "TE"],
  [155, "Dalton Kincaid", "BUF", "TE"],
  [158, "Hunter Henry", "NE", "TE"],
  [173, "AJ Barner", "SEA", "TE"],
  [181, "T.J. Hockenson", "MIN", "TE"],
  [196, "Kenyon Sadiq", "NYJ", "TE"],
  [203, "Mason Taylor", "NYJ", "TE"],
  [209, "George Kittle", "SF", "TE"],
  [226, "Terrance Ferguson", "LAR", "TE"],
  [229, "Theo Johnson", "NYG", "TE"],
  [236, "Gunnar Helm", "TEN", "TE"],
  [246, "David Njoku", "LAC", "TE"],
  [254, "Chig Okonkwo", "WAS", "TE"],
  [256, "Evan Engram", "DEN", "TE"],
  [259, "Colby Parkinson", "LAR", "TE"],
  [261, "Cade Otton", "TB", "TE"],
  [268, "Pat Freiermuth", "PIT", "TE"],
  [274, "Mike Gesicki", "CIN", "TE"],
  [281, "Jake Tonges", "SF", "TE"],
]


const EMRICK_WILSON_HALF_PPR_RAW: RawPlayer[] = [
  [1, "Bijan Robinson", "ATL", "RB"],
  [2, "Ja'Marr Chase", "CIN", "WR"],
  [3, "Jahmyr Gibbs", "DET", "RB"],
  [4, "Puka Nacua", "LAR", "WR"],
  [5, "Jaxon Smith-Njigba", "SEA", "WR"],
  [6, "Christian McCaffrey", "SF", "RB"],
  [7, "Amon-Ra St. Brown", "DET", "WR"],
  [8, "Justin Jefferson", "MIN", "WR"],
  [9, "CeeDee Lamb", "DAL", "WR"],
  [10, "Jonathan Taylor", "IND", "RB"],
  [11, "Ashton Jeanty", "LV", "RB"],
  [12, "Omarion Hampton", "LAC", "RB"],
  [13, "Rashee Rice", "KC", "WR"],
  [14, "James Cook III", "BUF", "RB"],
  [15, "Trey McBride", "ARI", "TE"],
  [16, "Saquon Barkley", "PHI", "RB"],
  [17, "Drake London", "ATL", "WR"],
  [18, "Nico Collins", "HOU", "WR"],
  [19, "De'Von Achane", "MIA", "RB"],
  [20, "Chase Brown", "CIN", "RB"],
  [21, "Malik Nabers", "NYG", "WR"],
  [22, "Chris Olave", "NO", "WR"],
  [23, "George Pickens", "DAL", "WR"],
  [24, "Brock Bowers", "LV", "TE"],
  [25, "Kenneth Walker III", "KC", "RB"],
  [26, "Josh Allen", "BUF", "QB"],
  [27, "Lamar Jackson", "BAL", "QB"],
  [28, "A.J. Brown", "NE", "WR"],
  [29, "Drake Maye", "NE", "QB"],
  [30, "Breece Hall", "NYJ", "RB"],
  [31, "Tee Higgins", "CIN", "WR"],
  [32, "Tetairoa McMillan", "CAR", "WR"],
  [33, "Jeremiyah Love", "ARI", "RB"],
  [34, "Travis Etienne Jr.", "NO", "RB"],
  [35, "Colston Loveland", "CHI", "TE"],
  [36, "Luther Burden III", "CHI", "WR"],
  [37, "Joe Burrow", "CIN", "QB"],
  [38, "Josh Jacobs", "GB", "RB"],
  [39, "Michael Wilson", "ARI", "WR"],
  [40, "Garrett Wilson", "NYJ", "WR"],
  [41, "Davante Adams", "LAR", "WR"],
  [42, "Derrick Henry", "BAL", "RB"],
  [43, "Jameson Williams", "DET", "WR"],
  [44, "Christian Watson", "GB", "WR"],
  [45, "Ladd McConkey", "LAC", "WR"],
  [46, "Javonte Williams", "DAL", "RB"],
  [47, "Kyren Williams", "LAR", "RB"],
  [48, "David Montgomery", "HOU", "RB"],
  [49, "Jaylen Waddle", "DEN", "WR"],
  [50, "Makai Lemon", "PHI", "WR"],
  [51, "Zay Flowers", "BAL", "WR"],
  [52, "Terry McLaurin", "WAS", "WR"],
  [53, "Bhayshul Tuten", "JAC", "RB"],
  [54, "Bucky Irving", "TB", "RB"],
  [55, "Jayden Daniels", "WAS", "QB"],
  [56, "Quinshon Judkins", "CLE", "RB"],
  [57, "Tucker Kraft", "GB", "TE"],
  [58, "Cam Skattebo", "NYG", "RB"],
  [59, "DeVonta Smith", "PHI", "WR"],
  [60, "Jalen Hurts", "PHI", "QB"],
  [61, "Mike Evans", "SF", "WR"],
  [62, "TreVeyon Henderson", "NE", "RB"],
  [63, "Jaxson Dart", "NYG", "QB"],
  [64, "Emeka Egbuka", "TB", "WR"],
  [65, "Tony Pollard", "TEN", "RB"],
  [66, "D'Andre Swift", "CHI", "RB"],
  [67, "Harold Fannin Jr.", "CLE", "TE"],
  [68, "J.K. Dobbins", "DEN", "RB"],
  [69, "DJ Moore", "BUF", "WR"],
  [70, "Justin Herbert", "LAC", "QB"],
  [71, "Parker Washington", "JAC", "WR"],
  [72, "Rico Dowdle", "PIT", "RB"],
  [73, "Chuba Hubbard", "CAR", "RB"],
  [74, "Trevor Lawrence", "JAC", "QB"],
  [75, "Courtland Sutton", "DEN", "WR"],
  [76, "Alec Pierce", "IND", "WR"],
  [77, "Tyler Warren", "IND", "TE"],
  [78, "Tyler Allgeier", "ARI", "RB"],
  [79, "Caleb Williams", "CHI", "QB"],
  [80, "RJ Harvey", "DEN", "RB"],
  [81, "Rome Odunze", "CHI", "WR"],
  [82, "DK Metcalf", "PIT", "WR"],
  [83, "Carnell Tate", "TEN", "WR"],
  [84, "Sam LaPorta", "DET", "TE"],
  [85, "Jaylen Warren", "PIT", "RB"],
  [86, "Kyle Pitts Sr.", "ATL", "TE"],
  [87, "Marvin Harrison Jr.", "ARI", "WR"],
  [88, "Kyle Monangai", "CHI", "RB"],
  [89, "Jakobi Meyers", "JAC", "WR"],
  [90, "Brock Purdy", "SF", "QB"],
  [91, "Chris Godwin Jr.", "TB", "WR"],
  [92, "Jadarian Price", "SEA", "RB"],
  [93, "Jordan Addison", "MIN", "WR"],
  [94, "Oronde Gadsden II", "LAC", "TE"],
  [95, "Brian Thomas Jr.", "JAC", "WR"],
  [96, "Jake Ferguson", "DAL", "TE"],
  [97, "Bo Nix", "DEN", "QB"],
  [98, "Rhamondre Stevenson", "NE", "RB"],
  [99, "Kenneth Gainwell", "TB", "RB"],
  [100, "Dak Prescott", "DAL", "QB"],
]

function extendRawWithFallback(primaryRaw: RawPlayer[], fallbackRaw: RawPlayer[]): RawPlayer[] {
  const primaryNames = new Set(primaryRaw.map(([, name]) => name))
  return [
    ...primaryRaw,
    ...fallbackRaw
      .filter(([, name]) => !primaryNames.has(name))
      .map(([, name, team, position], index): RawPlayer => [primaryRaw.length + index + 1, name, team, position]),
  ]
}

function buildHybridRaw(baseRaw: RawPlayer[], teRaw: RawPlayer[]): RawPlayer[] {
  const teByName = new Map(teRaw.map(([rank, name, team, position]) => [getCanonicalPlayerNameKey(name), { rank, team, position }]))
  const baseNames = new Set(baseRaw.map(([, name]) => getCanonicalPlayerNameKey(name)))
  const hybridEntries: RawPlayer[] = [
    ...baseRaw.map(([rank, name, team, position]): RawPlayer => {
      const teOverride = teByName.get(getCanonicalPlayerNameKey(name))
      return teOverride ? [teOverride.rank, name, teOverride.team || team, teOverride.position] : [rank, name, team, position]
    }),
    ...teRaw.filter(([, name]) => !baseNames.has(getCanonicalPlayerNameKey(name))),
  ]

  return hybridEntries
    .sort(([rankA, nameA], [rankB, nameB]) => rankA - rankB || nameA.localeCompare(nameB))
    .map(([, name, team, position], index): RawPlayer => [index + 1, name, team, position])
}

const HYBRID_HALF_PPR_RAW: RawPlayer[] = buildHybridRaw(BOONE_RAW, EMRICK_WILSON_TE_RAW)
const HYBRID_FULL_PPR_RAW: RawPlayer[] = buildHybridRaw(DEL_DON_RAW, EMRICK_WILSON_TE_RAW)

export type AccuracyRanks = Partial<Record<"QB" | "RB" | "WR" | "TE" | "K" | "DST" | "IDP", number | "-">>

export type RankingPreset = {
  id: string
  analyst: string
  source: string
  updated: string
  accuracyRank: number
  accuracyType: "In-season" | "Draft" | "Hybrid"
  accuracyRanks?: AccuracyRanks
  accuracyNote: string
  methodology?: string
  sourceByPosition?: Partial<Record<"QB" | "RB" | "WR" | "TE" | "K" | "DST", string>>
  players: ReturnType<typeof buildPlayers>
}

export type ScoringGroup = {
  id: string
  label: string
  description: string
  presets: RankingPreset[]
}

export const RANKING_PRESET_GROUPS: ScoringGroup[] = [
  {
    id: "half-ppr",
    label: "Half PPR",
    description: "0.5 points per reception",
    presets: [
      {
        id: "hybrid-half-ppr",
        analyst: "Sage Rankings",
        source: "Best analyst by position",
        updated: "6/22",
        accuracyRank: 1,
        accuracyType: "Hybrid",
        accuracyRanks: { QB: 6, RB: 5, WR: 1, TE: 5, K: 11, DST: 28, IDP: "-" },
        accuracyNote: "Position-aware board: Boone baseline with James Emrick-Wilson's #5 TE accuracy input.",
        methodology:
          "Uses the strongest available position specialists: Justin Boone for QB/RB/WR and James Emrick-Wilson for TE, then re-sorts into one actionable draft board.",
        sourceByPosition: { QB: "Justin Boone", RB: "Justin Boone", WR: "Justin Boone", TE: "James Emrick-Wilson", K: "Justin Boone", DST: "Justin Boone" },
        players: buildPlayers("hybrid-half", HYBRID_HALF_PPR_RAW),
      },
      {
        id: "boone-half-ppr",
        analyst: "Justin Boone",
        source: "Yahoo Sports",
        updated: "6/3",
        accuracyRank: 1,
        accuracyType: "In-season",
        accuracyRanks: { QB: 6, RB: 5, WR: 1, TE: 18, K: 11, DST: 28, IDP: "-" },
        accuracyNote: "#1 in FantasyPros 2025 in-season accuracy",
        players: buildPlayers("boone", BOONE_RAW),
      },
      {
        id: "del-don-half-ppr",
        analyst: "Dalton Del Don",
        source: "The Deep Shot",
        updated: "6/22",
        accuracyRank: 6,
        accuracyType: "In-season",
        accuracyRanks: { QB: 9, RB: 12, WR: 13, TE: 10, K: 31, DST: 30, IDP: "-" },
        accuracyNote: "#6 in FantasyPros 2025 in-season accuracy",
        players: buildPlayers("del-don-half", DEL_DON_HALF_PPR_RAW),
      },
    ],
  },
  {
    id: "best-ball",
    label: "Best Ball",
    description: "Built for Best Ball tournaments · Auto-lineup · Half PPR · No weekly management",
    presets: [
      {
        id: "underdog-best-ball-june-24",
        analyst: "Underdog ADP",
        source: "Underdog Fantasy",
        updated: "6/24",
        accuracyRank: 1,
        accuracyType: "Draft",
        accuracyNote: "Underdog Best Ball tournament ADP from June 24; auto-lineup half-PPR market pricing.",
        methodology: "Uses Underdog ADP as the room map for best-ball drafts where weekly lineup management is not required.",
        players: buildUnderdogPlayers("underdog-0624", UNDERDOG_BEST_BALL_JUNE_24_RAW),
      },
    ],
  },
  {
    id: "full-ppr",
    label: "Full PPR",
    description: "1 point per reception",
    presets: [
      {
        id: "hybrid-full-ppr",
        analyst: "Sage Rankings",
        source: "Hybrid: Dalton Del Don + James Emrick-Wilson TE",
        updated: "6/22",
        accuracyRank: 1,
        accuracyType: "Hybrid",
        accuracyRanks: { QB: 9, RB: 12, WR: 13, TE: 5, K: 31, DST: 30, IDP: "-" },
        accuracyNote: "Hybrid board: Dalton Del Don in-season baseline with James Emrick-Wilson's #5 TE accuracy input.",
        methodology:
          "Uses Dalton Del Don's in-season board for QB/RB/WR and James Emrick-Wilson's TE ordering, then re-sorts the board into one Sage draft list.",
        sourceByPosition: { QB: "Dalton Del Don", RB: "Dalton Del Don", WR: "Dalton Del Don", TE: "James Emrick-Wilson", K: "Dalton Del Don", DST: "Dalton Del Don" },
        players: buildPlayers("hybrid-full", HYBRID_FULL_PPR_RAW),
      },
      {
        id: "erickson-full-ppr",
        analyst: "Andrew Erickson",
        source: "FantasyPros",
        updated: "6/18",
        accuracyRank: 5,
        accuracyType: "Draft",
        accuracyNote: "#5 in FantasyPros 2024 draft accuracy",
        players: buildPlayers("erickson", ERICKSON_RAW),
      },
      {
        id: "del-don-full-ppr",
        analyst: "Dalton Del Don",
        source: "The Deep Shot",
        updated: "6/22",
        accuracyRank: 6,
        accuracyType: "In-season",
        accuracyRanks: { QB: 9, RB: 12, WR: 13, TE: 10, K: 31, DST: 30, IDP: "-" },
        accuracyNote: "#6 in FantasyPros 2025 in-season accuracy",
        players: buildPlayers("del-don", DEL_DON_RAW),
      },
    ],
  },
]

export function findPresetById(id: string): RankingPreset | undefined {
  for (const group of RANKING_PRESET_GROUPS) {
    const found = group.presets.find((p) => p.id === id)
    if (found) return found
  }
  return undefined
}
