// Preset expert rankings, organized by scoring format.
// Each scoring format can hold multiple analysts (more can be added over time).
// Players are NOT loaded by default — the user picks a preset to load it,
// and uploading their own CSV replaces whatever is loaded.

type RawPlayer = [number, string, string, string] // [rank, name, team, position]

function buildPlayers(idPrefix: string, raw: RawPlayer[]) {
  return raw.map(([rank, name, team, position]) => {
    const nameParts = name.split(" ")
    const firstName = nameParts.shift() || ""
    const lastName = nameParts.join(" ")
    return {
      id: `${idPrefix}-${rank}`,
      name,
      firstName,
      lastName,
      position,
      team: team || "FA",
      adp: rank,
      value: 0,
      drafted: false,
    }
  })
}

// ---------------------------------------------------------------------------
// HALF PPR — Justin Boone (Yahoo Sports), updated 6/3
// FantasyPros in-season accuracy: #1 in 2025
// ---------------------------------------------------------------------------
const BOONE_RAW: RawPlayer[] = [
  [1, "Bijan Robinson", "ATL", "RB"],
  [2, "Jahmyr Gibbs", "DET", "RB"],
  [3, "Ja'Marr Chase", "CIN", "WR"],
  [4, "Jaxon Smith-Njigba", "SEA", "WR"],
  [5, "Puka Nacua", "LAR", "WR"],
  [6, "Jonathan Taylor", "IND", "RB"],
  [7, "Christian McCaffrey", "SF", "RB"],
  [8, "CeeDee Lamb", "DAL", "WR"],
  [9, "Amon-Ra St. Brown", "DET", "WR"],
  [10, "James Cook III", "BUF", "RB"],
  [11, "Ashton Jeanty", "LV", "RB"],
  [12, "Justin Jefferson", "MIN", "WR"],
  [13, "Chase Brown", "CIN", "RB"],
  [14, "De'Von Achane", "MIA", "RB"],
  [15, "Omarion Hampton", "LAC", "RB"],
  [16, "Saquon Barkley", "PHI", "RB"],
  [17, "Jeremiyah Love", "ARI", "RB"],
  [18, "Kenneth Walker III", "KC", "RB"],
  [19, "Drake London", "ATL", "WR"],
  [20, "Brock Bowers", "LV", "TE"],
  [21, "Nico Collins", "HOU", "WR"],
  [22, "George Pickens", "DAL", "WR"],
  [23, "Derrick Henry", "BAL", "RB"],
  [24, "DeVonta Smith", "PHI", "WR"],
  [25, "A.J. Brown", "NE", "WR"],
  [26, "Trey McBride", "ARI", "TE"],
  [27, "Josh Allen", "BUF", "QB"],
  [28, "Chris Olave", "NO", "WR"],
  [29, "Rashee Rice", "KC", "WR"],
  [30, "Kyren Williams", "LAR", "RB"],
  [31, "Cam Skattebo", "NYG", "RB"],
  [32, "Javonte Williams", "DAL", "RB"],
  [33, "Travis Etienne Jr.", "NO", "RB"],
  [34, "Tetairoa McMillan", "CAR", "WR"],
  [35, "Zay Flowers", "BAL", "WR"],
  [36, "Tee Higgins", "CIN", "WR"],
  [37, "Luther Burden III", "CHI", "WR"],
  [38, "Garrett Wilson", "NYJ", "WR"],
  [39, "Ladd McConkey", "LAC", "WR"],
  [40, "Breece Hall", "NYJ", "RB"],
  [41, "Terry McLaurin", "WAS", "WR"],
  [42, "Jaylen Waddle", "DEN", "WR"],
  [43, "D'Andre Swift", "CHI", "RB"],
  [44, "Colston Loveland", "CHI", "TE"],
  [45, "Josh Jacobs", "GB", "RB"],
  [46, "Lamar Jackson", "BAL", "QB"],
  [47, "Christian Watson", "GB", "WR"],
  [48, "David Montgomery", "HOU", "RB"],
  [49, "Quinshon Judkins", "CLE", "RB"],
  [50, "Malik Nabers", "NYG", "WR"],
  [51, "TreVeyon Henderson", "NE", "RB"],
  [52, "Carnell Tate", "TEN", "WR"],
  [53, "Bhayshul Tuten", "JAC", "RB"],
  [54, "Emeka Egbuka", "TB", "WR"],
  [55, "Davante Adams", "LAR", "WR"],
  [56, "Jameson Williams", "DET", "WR"],
  [57, "Chuba Hubbard", "CAR", "RB"],
  [58, "Jadarian Price", "SEA", "RB"],
  [59, "DJ Moore", "BUF", "WR"],
  [60, "Makai Lemon", "PHI", "WR"],
  [61, "Rome Odunze", "CHI", "WR"],
  [62, "Jayden Daniels", "WAS", "QB"],
  [63, "Drake Maye", "NE", "QB"],
  [64, "Tyler Warren", "IND", "TE"],
  [65, "Jordyn Tyson", "NO", "WR"],
  [66, "Parker Washington", "JAC", "WR"],
  [67, "Mike Evans", "SF", "WR"],
  [68, "Joe Burrow", "CIN", "QB"],
  [69, "Justin Herbert", "LAC", "QB"],
  [70, "Jalen Hurts", "PHI", "QB"],
  [71, "Tucker Kraft", "GB", "TE"],
  [72, "Bucky Irving", "TB", "RB"],
  [73, "Rhamondre Stevenson", "NE", "RB"],
  [74, "Marvin Harrison Jr.", "ARI", "WR"],
  [75, "Alec Pierce", "IND", "WR"],
  [76, "Caleb Williams", "CHI", "QB"],
  [77, "Chris Godwin Jr.", "TB", "WR"],
  [78, "Courtland Sutton", "DEN", "WR"],
  [79, "DK Metcalf", "PIT", "WR"],
  [80, "Jayden Reed", "GB", "WR"],
  [81, "Ricky Pearsall", "SF", "WR"],
  [82, "Brian Thomas Jr.", "JAC", "WR"],
  [83, "Jaylen Warren", "PIT", "RB"],
  [84, "Rico Dowdle", "PIT", "RB"],
  [85, "Tony Pollard", "TEN", "RB"],
  [86, "Kenneth Gainwell", "TB", "RB"],
  [87, "Jaxson Dart", "NYG", "QB"],
  [88, "Kyle Monangai", "CHI", "RB"],
  [89, "Blake Corum", "LAR", "RB"],
  [90, "Dak Prescott", "DAL", "QB"],
  [91, "Trevor Lawrence", "JAC", "QB"],
  [92, "RJ Harvey", "DEN", "RB"],
  [93, "Harold Fannin Jr.", "CLE", "TE"],
  [94, "Sam LaPorta", "DET", "TE"],
  [95, "Kyle Pitts Sr.", "ATL", "TE"],
  [96, "Bo Nix", "DEN", "QB"],
  [97, "George Kittle", "SF", "TE"],
  [98, "Jordan Addison", "MIN", "WR"],
  [99, "J.K. Dobbins", "DEN", "RB"],
  [100, "Jonathon Brooks", "CAR", "RB"],
  [101, "Jakobi Meyers", "JAC", "WR"],
  [102, "KC Concepcion", "CLE", "WR"],
  [103, "Jacory Croskey-Merritt", "WAS", "RB"],
  [104, "Rachaad White", "WAS", "RB"],
  [105, "Dalton Kincaid", "BUF", "TE"],
  [106, "Michael Wilson", "ARI", "WR"],
  [107, "Quentin Johnston", "LAC", "WR"],
  [108, "Wan'Dale Robinson", "TEN", "WR"],
  [109, "Josh Downs", "IND", "WR"],
  [110, "Brock Purdy", "SF", "QB"],
  [111, "Aaron Jones Sr.", "MIN", "RB"],
  [112, "Jordan Mason", "MIN", "RB"],
  [113, "Xavier Worthy", "KC", "WR"],
  [114, "Michael Pittman Jr.", "PIT", "WR"],
  [115, "Kyler Murray", "MIN", "QB"],
  [116, "Travis Kelce", "KC", "TE"],
  [117, "Isaiah Likely", "NYG", "TE"],
  [118, "Tyrone Tracy Jr.", "NYG", "RB"],
  [119, "Jalen Coker", "CAR", "WR"],
  [120, "Omar Cooper Jr.", "NYJ", "WR"],
  [121, "Jayden Higgins", "HOU", "WR"],
  [122, "Stefon Diggs", "FA", "WR"],
  [123, "Patrick Mahomes II", "KC", "QB"],
  [124, "Romeo Doubs", "NE", "WR"],
  [125, "Jonah Coleman", "DEN", "RB"],
  [126, "Chris Rodriguez Jr.", "JAC", "RB"],
  [127, "Mark Andrews", "BAL", "TE"],
  [128, "Keaton Mitchell", "LAC", "RB"],
  [129, "Isiah Pacheco", "DET", "RB"],
  [130, "Brian Robinson Jr.", "ATL", "RB"],
  [131, "Tyler Allgeier", "ARI", "RB"],
  [132, "Emmett Johnson", "KC", "RB"],
  [133, "Zach Charbonnet", "SEA", "RB"],
  [134, "Nicholas Singleton", "TEN", "RB"],
  [135, "Jalen McMillan", "TB", "WR"],
  [136, "Dallas Goedert", "PHI", "TE"],
  [137, "Chig Okonkwo", "WAS", "TE"],
  [138, "Antonio Williams", "WAS", "WR"],
  [139, "Kaytron Allen", "WAS", "RB"],
  [140, "Dylan Sampson", "CLE", "RB"],
  [141, "Woody Marks", "HOU", "RB"],
  [142, "Braelon Allen", "NYJ", "RB"],
  [143, "Tank Bigsby", "PHI", "RB"],
  [144, "Jake Ferguson", "DAL", "TE"],
  [145, "Travis Hunter", "JAC", "WR"],
  [146, "Denzel Boston", "CLE", "WR"],
  [147, "Khalil Shakir", "BUF", "WR"],
  [148, "Hunter Henry", "NE", "TE"],
  [149, "Matthew Stafford", "LAR", "QB"],
  [150, "Tyler Shough", "NO", "QB"],
  [151, "Ray Davis", "BUF", "RB"],
  [152, "Tyjae Spears", "TEN", "RB"],
  [153, "Matthew Golden", "GB", "WR"],
  [154, "Rashid Shaheed", "SEA", "WR"],
  [155, "Emanuel Wilson", "SEA", "RB"],
  [156, "Sean Tucker", "TB", "RB"],
  [157, "Jalen Nailor", "LV", "WR"],
  [158, "Tre Tucker", "LV", "WR"],
  [159, "Jauan Jennings", "MIN", "WR"],
  [160, "Deebo Samuel Sr.", "FA", "WR"],
  [161, "Jared Goff", "DET", "QB"],
  [162, "Malik Willis", "MIA", "QB"],
  [163, "Baker Mayfield", "TB", "QB"],
  [164, "Jordan Love", "GB", "QB"],
  [165, "Brenton Strange", "JAC", "TE"],
  [166, "Demond Claiborne", "MIN", "RB"],
  [167, "Oronde Gadsden II", "LAC", "TE"],
  [168, "Mike Washington Jr.", "LV", "RB"],
  [169, "Jordan James", "SF", "RB"],
  [170, "Alvin Kamara", "NO", "RB"],
  [171, "Chris Brooks", "GB", "RB"],
  [172, "James Conner", "ARI", "RB"],
  [173, "Jerry Jeudy", "CLE", "WR"],
  [174, "Houston Texans", "HOU", "DST"],
  [175, "Kaelon Black", "SF", "RB"],
  [176, "Isaac TeSlaa", "DET", "WR"],
  [177, "Malik Washington", "MIA", "WR"],
  [178, "Ryan Flournoy", "DAL", "WR"],
  [179, "Tre' Harris", "LAC", "WR"],
  [180, "Zachariah Branch", "ATL", "WR"],
  [181, "Darnell Mooney", "NYG", "WR"],
  [182, "Jaylen Wright", "MIA", "RB"],
  [183, "Justice Hill", "BAL", "RB"],
  [184, "Seattle Seahawks", "SEA", "DST"],
  [185, "Brandon Aubrey", "DAL", "K"],
  [186, "Najee Harris", "LAC", "RB"],
  [187, "Jaydon Blue", "DAL", "RB"],
  [188, "Sam Darnold", "SEA", "QB"],
  [189, "Los Angeles Rams", "LAR", "DST"],
  [190, "Adonai Mitchell", "NYJ", "WR"],
  [191, "Kenyon Sadiq", "NYJ", "TE"],
  [192, "Juwan Johnson", "NO", "TE"],
  [193, "Dalton Schultz", "HOU", "TE"],
  [194, "Adam Randall", "BAL", "RB"],
  [195, "Kimani Vidal", "LAC", "RB"],
  [196, "Kendre Miller", "NO", "RB"],
  [197, "Devin Neal", "NO", "RB"],
  [198, "MarShawn Lloyd", "GB", "RB"],
  [199, "Ollie Gordon II", "MIA", "RB"],
  [200, "DJ Giddens", "IND", "RB"],
  [201, "C.J. Stroud", "HOU", "QB"],
  [202, "Denver Broncos", "DEN", "DST"],
  [203, "Philadelphia Eagles", "PHI", "DST"],
  [204, "Ka'imi Fairbairn", "HOU", "K"],
  [205, "Cam Ward", "TEN", "QB"],
  [206, "Daniel Jones", "IND", "QB"],
  [207, "Bryce Young", "CAR", "QB"],
  [208, "AJ Barner", "SEA", "TE"],
  [209, "George Holani", "SEA", "RB"],
  [210, "Malik Davis", "DAL", "RB"],
  [211, "LeQuint Allen Jr.", "JAC", "RB"],
  [212, "Malachi Fields", "NYG", "WR"],
  [213, "Germie Bernard", "PIT", "WR"],
  [214, "Calvin Ridley", "TEN", "WR"],
  [215, "De'Zhaun Stribling", "SF", "WR"],
  [216, "Ted Hurst III", "TB", "WR"],
  [217, "Tank Dell", "HOU", "WR"],
  [218, "Chris Bell", "MIA", "WR"],
  [219, "Pat Bryant", "DEN", "WR"],
  [220, "Troy Franklin", "DEN", "WR"],
  [221, "Brandon Aiyuk", "SF", "WR"],
  [222, "Tyreek Hill", "FA", "WR"],
  [223, "Jaylin Noel", "HOU", "WR"],
  [224, "Tory Horton", "SEA", "WR"],
  [225, "Elijah Sarratt", "BAL", "WR"],
  [226, "Ja'Kobi Lane", "BAL", "WR"],
  [227, "Fernando Mendoza", "LV", "QB"],
  [228, "T.J. Hockenson", "MIN", "TE"],
  [229, "New England Patriots", "NE", "DST"],
  [230, "Cam Little", "JAC", "K"],
  [231, "Pittsburgh Steelers", "PIT", "DST"],
  [232, "Gunnar Helm", "TEN", "TE"],
  [233, "Geno Smith", "NYJ", "QB"],
  [234, "Aaron Rodgers", "PIT", "QB"],
  [235, "Greg Dulcich", "MIA", "TE"],
  [236, "Eli Stowers", "PHI", "TE"],
  [237, "Terrance Ferguson", "LAR", "TE"],
  [238, "Skyler Bell", "BUF", "WR"],
  [239, "Cameron Dicker", "LAC", "K"],
  [240, "Jason Myers", "SEA", "K"],
  [241, "Jacksonville Jaguars", "JAC", "DST"],
  [242, "Eddy Pineiro", "SF", "K"],
  [243, "Dontayvion Wicks", "PHI", "WR"],
  [244, "Jahan Dotson", "ATL", "WR"],
  [245, "Hollywood Brown", "PHI", "WR"],
  [246, "Tyquan Thornton", "KC", "WR"],
  [247, "Keon Coleman", "BUF", "WR"],
  [248, "Rashod Bateman", "BAL", "WR"],
  [249, "Marvin Mims Jr.", "DEN", "WR"],
  [250, "Jalen Tolbert", "MIA", "WR"],
  [251, "Christian Kirk", "SF", "WR"],
  [252, "Treylon Burks", "WAS", "WR"],
  [253, "Konata Mumpfield", "LAR", "WR"],
  [254, "Harrison Mevis", "LAR", "K"],
  [255, "Minnesota Vikings", "MIN", "DST"],
  [256, "Baltimore Ravens", "BAL", "DST"],
  [257, "Detroit Lions", "DET", "DST"],
  [258, "Cairo Santos", "CHI", "K"],
  [259, "Buffalo Bills", "BUF", "DST"],
  [260, "Will Reichard", "MIN", "K"],
  [261, "Tyler Loop", "BAL", "K"],
  [262, "Jack Bech", "LV", "WR"],
  [263, "Chris Brazzell II", "CAR", "WR"],
  [264, "Caleb Douglas", "MIA", "WR"],
  [265, "Cooper Kupp", "SEA", "WR"],
  [266, "Jake Bates", "DET", "K"],
  [267, "Pat Freiermuth", "PIT", "TE"],
  [268, "Cade Otton", "TB", "TE"],
  [269, "David Njoku", "LAC", "TE"],
  [270, "Mike Gesicki", "CIN", "TE"],
  [271, "Jake Tonges", "SF", "TE"],
  [272, "Jacoby Brissett", "ARI", "QB"],
  [273, "Michael Penix Jr.", "ATL", "QB"],
  [274, "Deshaun Watson", "CLE", "QB"],
  [275, "Tua Tagovailoa", "ATL", "QB"],
  [276, "Shedeur Sanders", "CLE", "QB"],
  [277, "Isaiah Davis", "NYJ", "RB"],
  [278, "Tahj Brooks", "CIN", "RB"],
  [279, "Trey Benson", "ARI", "RB"],
  [280, "Will Shipley", "PHI", "RB"],
  [281, "Devin Singletary", "NYG", "RB"],
  [282, "Emari Demercado", "KC", "RB"],
  [283, "Kaleb Johnson", "PIT", "RB"],
  [284, "Samaje Perine", "CIN", "RB"],
  [285, "Eli Heidenreich", "PIT", "RB"],
  [286, "Trevor Etienne", "CAR", "RB"],
  [287, "Seth McGowan", "IND", "RB"],
  [288, "Carson Beck", "ARI", "QB"],
  [289, "Darius Slayton", "NYG", "WR"],
  [290, "Nick Westbrook-Ikhine", "IND", "WR"],
  [291, "Dyami Brown", "WAS", "WR"],
  [292, "Kirk Cousins", "LV", "QB"],
  [293, "Kayshon Boutte", "NE", "WR"],
  [294, "Jalen Royals", "KC", "WR"],
  [295, "Brenen Thompson", "LAC", "WR"],
  [296, "Keenan Allen", "LAC", "WR"],
  [297, "Savion Williams", "GB", "WR"],
  [298, "KaVontae Turpin", "DAL", "WR"],
  [299, "Brashard Smith", "KC", "RB"],
  [300, "Ty Johnson", "BUF", "RB"],
  [301, "Phil Mafah", "DAL", "RB"],
]


// ---------------------------------------------------------------------------
// HALF PPR — Dalton Del Don (The Deep Shot), updated 6/15
// FantasyPros in-season accuracy: #6 in 2025
// ---------------------------------------------------------------------------
const DEL_DON_HALF_PPR_TOP_100 = [
  "Jahmyr Gibbs", "Bijan Robinson", "Ja'Marr Chase", "Puka Nacua", "Jaxon Smith-Njigba",
  "Jonathan Taylor", "Christian McCaffrey", "Ashton Jeanty", "James Cook III", "Amon-Ra St. Brown",
  "CeeDee Lamb", "Chase Brown", "Kenneth Walker III", "Drake London", "Justin Jefferson",
  "Brock Bowers", "A.J. Brown", "Omarion Hampton", "Saquon Barkley", "De'Von Achane",
  "Derrick Henry", "Jeremiyah Love", "Trey McBride", "Nico Collins", "Rashee Rice",
  "Garrett Wilson", "George Pickens", "DeVonta Smith", "Kyren Williams", "Travis Etienne Jr.",
  "Zay Flowers", "Chris Olave", "Lamar Jackson", "Josh Allen", "Breece Hall",
  "Colston Loveland", "Tee Higgins", "Javonte Williams", "Josh Jacobs", "David Montgomery",
  "Cam Skattebo", "Luther Burden III", "Malik Nabers", "Terry McLaurin", "Emeka Egbuka",
  "Tetairoa McMillan", "Ladd McConkey", "Christian Watson", "Mike Evans", "Jaylen Waddle",
  "Rome Odunze", "Bhayshul Tuten", "TreVeyon Henderson", "D'Andre Swift", "Quinshon Judkins",
  "Bucky Irving", "Jayden Daniels", "Drake Maye", "Joe Burrow", "Jordyn Tyson",
  "Davante Adams", "Jameson Williams", "DJ Moore", "Tyler Warren", "Marvin Harrison Jr.",
  "Parker Washington", "Tucker Kraft", "George Kittle", "Jaylen Warren", "Rhamondre Stevenson",
  "Caleb Williams", "Jalen Hurts", "Brian Thomas Jr.", "Carnell Tate", "Quentin Johnston",
  "Chris Godwin Jr.", "Makai Lemon", "Alec Pierce", "DK Metcalf", "Trevor Lawrence",
  "Tony Pollard", "Jonathon Brooks", "Blake Corum", "Jadarian Price", "Harold Fannin Jr.",
  "Sam LaPorta", "Jaxson Dart", "Brock Purdy", "Justin Herbert", "RJ Harvey",
  "Chuba Hubbard", "Dalton Kincaid", "Jayden Reed", "Courtland Sutton", "Dak Prescott",
  "Kyler Murray", "Michael Wilson", "Josh Downs", "Ricky Pearsall", "Xavier Worthy",
] as const

const delDonHalfPlayerLookup = new Map(BOONE_RAW.map(([, name, team, position]) => [name, { team, position }] as const))
const DEL_DON_HALF_PPR_RAW: RawPlayer[] = [
  ...DEL_DON_HALF_PPR_TOP_100.map((name, index): RawPlayer => {
    const player = delDonHalfPlayerLookup.get(name)
    return [index + 1, name, player?.team || "FA", player?.position || "WR"]
  }),
  ...BOONE_RAW.filter(([, name]) => !DEL_DON_HALF_PPR_TOP_100.includes(name as (typeof DEL_DON_HALF_PPR_TOP_100)[number])).map(
    ([, name, team, position], index): RawPlayer => [DEL_DON_HALF_PPR_TOP_100.length + index + 1, name, team, position],
  ),
]

// ---------------------------------------------------------------------------
// FULL PPR — Andrew Erickson (FantasyPros), updated 6/12
// FantasyPros draft accuracy: #5 in 2024
// ---------------------------------------------------------------------------
const ERICKSON_RAW: RawPlayer[] = [
  [1, "Ja'Marr Chase", "CIN", "WR"],
  [2, "Jahmyr Gibbs", "DET", "RB"],
  [3, "Puka Nacua", "LAR", "WR"],
  [4, "Jaxon Smith-Njigba", "SEA", "WR"],
  [5, "Bijan Robinson", "ATL", "RB"],
  [6, "Amon-Ra St. Brown", "DET", "WR"],
  [7, "James Cook III", "BUF", "RB"],
  [8, "A.J. Brown", "NE", "WR"],
  [9, "Justin Jefferson", "MIN", "WR"],
  [10, "Jonathan Taylor", "IND", "RB"],
  [11, "CeeDee Lamb", "DAL", "WR"],
  [12, "Rashee Rice", "KC", "WR"],
  [13, "Chase Brown", "CIN", "RB"],
  [14, "Drake London", "ATL", "WR"],
  [15, "Nico Collins", "HOU", "WR"],
  [16, "Trey McBride", "ARI", "TE"],
  [17, "Ashton Jeanty", "LV", "RB"],
  [18, "George Pickens", "DAL", "WR"],
  [19, "Zay Flowers", "BAL", "WR"],
  [20, "Tetairoa McMillan", "CAR", "WR"],
  [21, "Omarion Hampton", "LAC", "RB"],
  [22, "Brock Bowers", "LV", "TE"],
  [23, "De'Von Achane", "MIA", "RB"],
  [24, "Kenneth Walker III", "KC", "RB"],
  [25, "Drake Maye", "NE", "QB"],
  [26, "Chris Olave", "NO", "WR"],
  [27, "Josh Allen", "BUF", "QB"],
  [28, "Garrett Wilson", "NYJ", "WR"],
  [29, "DeVonta Smith", "PHI", "WR"],
  [30, "Lamar Jackson", "BAL", "QB"],
  [31, "Christian McCaffrey", "SF", "RB"],
  [32, "Colston Loveland", "CHI", "TE"],
  [33, "Saquon Barkley", "PHI", "RB"],
  [34, "Javonte Williams", "DAL", "RB"],
  [35, "Ladd McConkey", "LAC", "WR"],
  [36, "Malik Nabers", "NYG", "WR"],
  [37, "Jayden Daniels", "WAS", "QB"],
  [38, "Jaylen Waddle", "DEN", "WR"],
  [39, "Jeremiyah Love", "ARI", "RB"],
  [40, "Tee Higgins", "CIN", "WR"],
  [41, "Breece Hall", "NYJ", "RB"],
  [42, "Terry McLaurin", "WAS", "WR"],
  [43, "Travis Etienne Jr.", "NO", "RB"],
  [44, "Emeka Egbuka", "TB", "WR"],
  [45, "Carnell Tate", "TEN", "WR"],
  [46, "Derrick Henry", "BAL", "RB"],
  [47, "Cam Skattebo", "NYG", "RB"],
  [48, "Luther Burden III", "CHI", "WR"],
  [49, "DJ Moore", "BUF", "WR"],
  [50, "Kyren Williams", "LAR", "RB"],
  [51, "Mike Evans", "SF", "WR"],
  [52, "Marvin Harrison Jr.", "ARI", "WR"],
  [53, "Bucky Irving", "TB", "RB"],
  [54, "Joe Burrow", "CIN", "QB"],
  [55, "Christian Watson", "GB", "WR"],
  [56, "Josh Jacobs", "GB", "RB"],
  [57, "Tyler Warren", "IND", "TE"],
  [58, "Quinshon Judkins", "CLE", "RB"],
  [59, "Justin Herbert", "LAC", "QB"],
  [60, "Alec Pierce", "IND", "WR"],
  [61, "David Montgomery", "HOU", "RB"],
  [62, "Rome Odunze", "CHI", "WR"],
  [63, "Caleb Williams", "CHI", "QB"],
  [64, "Jameson Williams", "DET", "WR"],
  [65, "TreVeyon Henderson", "NE", "RB"],
  [66, "Tucker Kraft", "GB", "TE"],
  [67, "RJ Harvey", "DEN", "RB"],
  [68, "Michael Pittman Jr.", "PIT", "WR"],
  [69, "Jordyn Tyson", "NO", "WR"],
  [70, "Jaxson Dart", "NYG", "QB"],
  [71, "Makai Lemon", "PHI", "WR"],
  [72, "Rachaad White", "WAS", "RB"],
  [73, "Harold Fannin Jr.", "CLE", "TE"],
  [74, "Jalen Hurts", "PHI", "QB"],
  [75, "Jaylen Warren", "PIT", "RB"],
  [76, "Josh Downs", "IND", "WR"],
  [77, "Bhayshul Tuten", "JAC", "RB"],
  [78, "Rico Dowdle", "PIT", "RB"],
  [79, "Brock Purdy", "SF", "QB"],
  [80, "Jadarian Price", "SEA", "RB"],
  [81, "Davante Adams", "LAR", "WR"],
  [82, "Jakobi Meyers", "JAC", "WR"],
  [83, "DK Metcalf", "PIT", "WR"],
  [84, "D'Andre Swift", "CHI", "RB"],
  [85, "Kyle Pitts Sr.", "ATL", "TE"],
  [86, "Rhamondre Stevenson", "NE", "RB"],
  [87, "Sam LaPorta", "DET", "TE"],
  [88, "KC Concepcion", "CLE", "WR"],
  [89, "Chuba Hubbard", "CAR", "RB"],
  [90, "Courtland Sutton", "DEN", "WR"],
  [91, "Wan'Dale Robinson", "TEN", "WR"],
  [92, "Trevor Lawrence", "JAC", "QB"],
  [93, "Kenneth Gainwell", "TB", "RB"],
  [94, "Ricky Pearsall", "SF", "WR"],
  [95, "Isaiah Likely", "NYG", "TE"],
  [96, "Chris Godwin Jr.", "TB", "WR"],
  [97, "Dalton Kincaid", "BUF", "TE"],
  [98, "Dak Prescott", "DAL", "QB"],
  [99, "Aaron Jones Sr.", "MIN", "RB"],
  [100, "Parker Washington", "JAC", "WR"],
  [101, "Bo Nix", "DEN", "QB"],
  [102, "Tony Pollard", "TEN", "RB"],
  [103, "Kyle Monangai", "CHI", "RB"],
  [104, "Patrick Mahomes II", "KC", "QB"],
  [105, "Jordan Love", "GB", "QB"],
  [106, "George Kittle", "SF", "TE"],
  [107, "Jayden Reed", "GB", "WR"],
  [108, "Kyler Murray", "MIN", "QB"],
  [109, "Brian Thomas Jr.", "JAC", "WR"],
  [110, "Michael Wilson", "ARI", "WR"],
  [111, "Chig Okonkwo", "WAS", "TE"],
  [112, "Travis Kelce", "KC", "TE"],
  [113, "Malik Willis", "MIA", "QB"],
  [114, "Baker Mayfield", "TB", "QB"],
  [115, "Xavier Worthy", "KC", "WR"],
  [116, "Jayden Higgins", "HOU", "WR"],
  [117, "J.K. Dobbins", "DEN", "RB"],
  [118, "Jonathon Brooks", "CAR", "RB"],
  [119, "Jared Goff", "DET", "QB"],
  [120, "Blake Corum", "LAR", "RB"],
  [121, "Jordan Addison", "MIN", "WR"],
  [122, "Jacory Croskey-Merritt", "WAS", "RB"],
  [123, "Romeo Doubs", "NE", "WR"],
  [124, "Greg Dulcich", "MIA", "TE"],
  [125, "Omar Cooper Jr.", "NYJ", "WR"],
  [126, "Khalil Shakir", "BUF", "WR"],
  [127, "Tyler Shough", "NO", "QB"],
  [128, "Emanuel Wilson", "SEA", "RB"],
  [129, "Dallas Goedert", "PHI", "TE"],
  [130, "Tyler Allgeier", "ARI", "RB"],
  [131, "Jalen Coker", "CAR", "WR"],
  [132, "C.J. Stroud", "HOU", "QB"],
  [133, "Jordan Mason", "MIN", "RB"],
  [134, "Denzel Boston", "CLE", "WR"],
  [135, "Matthew Golden", "GB", "WR"],
  [136, "Kenyon Sadiq", "NYJ", "TE"],
  [137, "Cam Ward", "TEN", "QB"],
  [138, "Antonio Williams", "WAS", "WR"],
  [139, "Isiah Pacheco", "DET", "RB"],
  [140, "Quentin Johnston", "LAC", "WR"],
  [141, "Tyrone Tracy Jr.", "NYG", "RB"],
  [142, "Brenton Strange", "JAC", "TE"],
  [143, "Nicholas Singleton", "TEN", "RB"],
  [144, "Jonah Coleman", "DEN", "RB"],
  [145, "Bryce Young", "CAR", "QB"],
  [146, "Zach Charbonnet", "SEA", "RB"],
  [147, "Stefon Diggs", "FA", "WR"],
  [148, "Jaylin Noel", "HOU", "WR"],
  [149, "Houston Texans", "HOU", "DST"],
  [150, "Brian Robinson Jr.", "ATL", "RB"],
  [151, "Geno Smith", "NYJ", "QB"],
  [152, "Germie Bernard", "PIT", "WR"],
  [153, "Mark Andrews", "BAL", "TE"],
  [154, "Tyjae Spears", "TEN", "RB"],
  [155, "Alvin Kamara", "NO", "RB"],
  [156, "Jake Ferguson", "DAL", "TE"],
  [157, "Daniel Jones", "IND", "QB"],
  [158, "Emmett Johnson", "KC", "RB"],
  [159, "Seattle Seahawks", "SEA", "DST"],
  [160, "Keaton Mitchell", "LAC", "RB"],
  [161, "Rashid Shaheed", "SEA", "WR"],
  [162, "MarShawn Lloyd", "GB", "RB"],
  [163, "Jerry Jeudy", "CLE", "WR"],
  [164, "Travis Hunter", "JAC", "WR"],
  [165, "Los Angeles Rams", "LAR", "DST"],
  [166, "Jalen McMillan", "TB", "WR"],
  [167, "Kaytron Allen", "WAS", "RB"],
  [168, "Chris Bell", "MIA", "WR"],
  [169, "Los Angeles Chargers", "LAC", "DST"],
  [170, "Philadelphia Eagles", "PHI", "DST"],
  [171, "AJ Barner", "SEA", "TE"],
  [172, "Darnell Mooney", "NYG", "WR"],
  [173, "Tank Bigsby", "PHI", "RB"],
  [174, "Elijah Sarratt", "BAL", "WR"],
  [175, "Chris Brooks", "GB", "RB"],
  [176, "Ted Hurst III", "TB", "WR"],
  [177, "Sam Darnold", "SEA", "QB"],
  [178, "Jauan Jennings", "MIN", "WR"],
  [179, "Hunter Henry", "NE", "TE"],
  [180, "Sean Tucker", "TB", "RB"],
  [181, "Denver Broncos", "DEN", "DST"],
  [182, "Tre Tucker", "LV", "WR"],
  [183, "Detroit Lions", "DET", "DST"],
  [184, "Baltimore Ravens", "BAL", "DST"],
  [185, "Brandon Aubrey", "DAL", "K"],
  [186, "Minnesota Vikings", "MIN", "DST"],
  [187, "Jordan James", "SF", "RB"],
  [188, "Kansas City Chiefs", "KC", "DST"],
  [189, "Jacksonville Jaguars", "JAC", "DST"],
  [190, "Ka'imi Fairbairn", "HOU", "K"],
  [191, "Cam Little", "JAC", "K"],
  [192, "Pittsburgh Steelers", "PIT", "DST"],
  [193, "Isaac TeSlaa", "DET", "WR"],
  [194, "T.J. Hockenson", "MIN", "TE"],
  [195, "Tre' Harris", "LAC", "WR"],
  [196, "Cameron Dicker", "LAC", "K"],
  [197, "De'Zhaun Stribling", "SF", "WR"],
  [198, "Evan McPherson", "CIN", "K"],
  [199, "Braelon Allen", "NYJ", "RB"],
  [200, "Brandon Aiyuk", "SF", "WR"],
  [201, "Dalton Schultz", "HOU", "TE"],
  [202, "Jason Myers", "SEA", "K"],
  [203, "Malachi Fields", "NYG", "WR"],
  [204, "New England Patriots", "NE", "DST"],
  [205, "Andy Borregales", "NE", "K"],
  [206, "Kayshon Boutte", "NE", "WR"],
  [207, "Juwan Johnson", "NO", "TE"],
  [208, "Calvin Ridley", "TEN", "WR"],
  [209, "Tyler Loop", "BAL", "K"],
  [210, "Green Bay Packers", "GB", "DST"],
  [211, "Eddy Pineiro", "SF", "K"],
  [212, "Fernando Mendoza", "LV", "QB"],
  [213, "Chase McLaughlin", "TB", "K"],
  [214, "Cairo Santos", "CHI", "K"],
  [215, "Harrison Mevis", "LAR", "K"],
  [216, "Zachariah Branch", "ATL", "WR"],
  [217, "Ray Davis", "BUF", "RB"],
  [218, "Buffalo Bills", "BUF", "DST"],
  [219, "Malik Washington", "MIA", "WR"],
  [220, "LeQuint Allen Jr.", "JAC", "RB"],
  [221, "Pat Bryant", "DEN", "WR"],
  [222, "Adonai Mitchell", "NYJ", "WR"],
  [223, "Chris Brazzell II", "CAR", "WR"],
  [224, "Gunnar Helm", "TEN", "TE"],
  [225, "Dontayvion Wicks", "PHI", "WR"],
  [226, "Woody Marks", "HOU", "RB"],
  [227, "Oronde Gadsden II", "LAC", "TE"],
  [228, "Jalen Nailor", "LV", "WR"],
  [229, "Mike Washington Jr.", "LV", "RB"],
  [230, "Chimere Dike", "TEN", "WR"],
  [231, "DJ Giddens", "IND", "RB"],
  [232, "Samaje Perine", "CIN", "RB"],
  [233, "Atlanta Falcons", "ATL", "DST"],
  [234, "Terrance Ferguson", "LAR", "TE"],
  [235, "Chris Rodriguez Jr.", "JAC", "RB"],
  [236, "Demond Claiborne", "MIN", "RB"],
  [237, "Devaughn Vele", "NO", "WR"],
  [238, "Jake Bates", "DET", "K"],
  [239, "Cyrus Allen", "KC", "WR"],
  [240, "Aaron Rodgers", "PIT", "QB"],
  [241, "Kimani Vidal", "LAC", "RB"],
  [242, "Tyreek Hill", "FA", "WR"],
  [243, "Deebo Samuel Sr.", "FA", "WR"],
  [244, "David Njoku", "LAC", "TE"],
  [245, "Marvin Mims Jr.", "DEN", "WR"],
  [246, "Ollie Gordon II", "MIA", "RB"],
  [247, "Tennessee Titans", "TEN", "DST"],
  [248, "Charlie Smyth", "NO", "K"],
  [249, "Justice Hill", "BAL", "RB"],
  [250, "Chris Boswell", "PIT", "K"],
  [251, "Wil Lutz", "DEN", "K"],
  [252, "Jake Tonges", "SF", "TE"],
  [253, "Tua Tagovailoa", "ATL", "QB"],
  [254, "Pat Freiermuth", "PIT", "TE"],
  [255, "Kaleb Johnson", "PIT", "RB"],
  [256, "Rashod Bateman", "BAL", "WR"],
  [257, "Cade Otton", "TB", "TE"],
  [258, "Trey Benson", "ARI", "RB"],
  [259, "Mike Gesicki", "CIN", "TE"],
  [260, "Troy Franklin", "DEN", "WR"],
  [261, "Jaylen Wright", "MIA", "RB"],
  [262, "Tank Dell", "HOU", "WR"],
  [263, "Ryan Flournoy", "DAL", "WR"],
  [264, "James Conner", "ARI", "RB"],
  [265, "Keenan Allen", "LAC", "WR"],
  [266, "Darnell Washington", "PIT", "TE"],
  [267, "DeMario Douglas", "NE", "WR"],
  [268, "Keon Coleman", "BUF", "WR"],
  [269, "Najee Harris", "LAC", "RB"],
  [270, "Andrei Iosivas", "CIN", "WR"],
  [271, "Konata Mumpfield", "LAR", "WR"],
  [272, "Eli Stowers", "PHI", "TE"],
  [273, "Jaydon Blue", "DAL", "RB"],
  [274, "Deshaun Watson", "CLE", "QB"],
  [275, "Cooper Kupp", "SEA", "WR"],
  [276, "Kaelon Black", "SF", "RB"],
  [277, "San Francisco 49ers", "SF", "DST"],
  [278, "Las Vegas Raiders", "LV", "DST"],
  [279, "Theo Johnson", "NYG", "TE"],
  [280, "Harrison Butker", "KC", "K"],
  [281, "Eli Heidenreich", "PIT", "RB"],
  [282, "Emari Demercado", "KC", "RB"],
  [283, "Michael Penix Jr.", "ATL", "QB"],
  [284, "Kyle Williams", "NE", "WR"],
  [285, "Bryce Lance", "NO", "WR"],
  [286, "Jaleel McLaughlin", "DEN", "RB"],
  [287, "Mack Hollins", "NE", "WR"],
  [288, "Evan Engram", "DEN", "TE"],
  [289, "Christian Kirk", "SF", "WR"],
  [290, "George Holani", "SEA", "RB"],
  [291, "Elic Ayomanor", "TEN", "WR"],
  [292, "Brashard Smith", "KC", "RB"],
  [293, "Ja'Tavion Sanders", "CAR", "TE"],
  [294, "Kevin Coleman Jr.", "MIA", "WR"],
  [295, "Seth McGowan", "IND", "RB"],
  [296, "Skyler Bell", "BUF", "WR"],
  [297, "Tutu Atwell", "MIA", "WR"],
  [298, "Colby Parkinson", "LAR", "TE"],
  [299, "Bam Knight", "ARI", "RB"],
  [300, "Darius Slayton", "NYG", "WR"],
  [301, "Tyquan Thornton", "KC", "WR"],
  [302, "Adam Randall", "BAL", "RB"],
  [303, "CJ Daniels", "LAR", "WR"],
  [304, "Dawson Knox", "BUF", "TE"],
  [305, "Ja'Kobi Lane", "BAL", "WR"],
  [306, "Jacoby Brissett", "ARI", "QB"],
  [307, "Mason Taylor", "NYJ", "TE"],
  [308, "Jerome Ford", "WAS", "RB"],
  [309, "Isaiah Davis", "NYJ", "RB"],
  [310, "Jack Bech", "LV", "WR"],
  [311, "J'Mari Taylor", "JAC", "RB"],
  [312, "Kareem Hunt", "FA", "RB"],
  [313, "Brenen Thompson", "LAC", "WR"],
  [314, "Jalen Royals", "KC", "WR"],
  [315, "Ty Johnson", "BUF", "RB"],
  [316, "Devin Neal", "NO", "RB"],
  [317, "Savion Williams", "GB", "WR"],
  [318, "Eli Raridon", "NE", "TE"],
  [319, "Shedeur Sanders", "CLE", "QB"],
  [320, "Trevor Etienne", "CAR", "RB"],
  [321, "Cedric Tillman", "CLE", "WR"],
  [322, "Kirk Cousins", "LV", "QB"],
  [323, "Oscar Delp", "NO", "TE"],
  [324, "Kendre Miller", "NO", "RB"],
  [325, "Devin Singletary", "NYG", "RB"],
  [326, "Hollywood Brown", "PHI", "WR"],
  [327, "Malik Davis", "DAL", "RB"],
  [328, "Tahj Brooks", "CIN", "RB"],
  [329, "Tory Horton", "SEA", "WR"],
  [330, "Zane Gonzalez", "MIA", "K"],
  [331, "Jaylin Lane", "WAS", "WR"],
  [332, "J.J. McCarthy", "MIN", "QB"],
  [333, "Marlin Klein", "HOU", "TE"],
  [334, "Carson Beck", "ARI", "QB"],
  [335, "Kendrick Bourne", "ARI", "WR"],
  [336, "Kalif Raymond", "CHI", "WR"],
  [337, "Elijah Arroyo", "SEA", "TE"],
  [338, "Tez Johnson", "TB", "WR"],
  [339, "Max Klare", "LAR", "TE"],
  [340, "Luke McCaffrey", "WAS", "WR"],
  [341, "Jalen Tolbert", "MIA", "WR"],
  [342, "Anthony Richardson Sr.", "IND", "QB"],
  [343, "Noah Fant", "NO", "TE"],
  [344, "Calvin Austin III", "NYG", "WR"],
  [345, "Isaiah Bond", "CLE", "WR"],
  [346, "Michael Mayer", "LV", "TE"],
  [347, "Tommy Tremble", "CAR", "TE"],
  [348, "Cole Kmet", "CHI", "TE"],
  [349, "New Orleans Saints", "NO", "DST"],
  [350, "Justin Joly", "DEN", "TE"],
  [351, "Mac Jones", "SF", "QB"],
  [352, "Nate Boerkircher", "JAC", "TE"],
  [353, "Luke Musgrave", "GB", "TE"],
  [354, "Tyler Higbee", "LAR", "TE"],
  [355, "Cade Klubnik", "NYJ", "QB"],
  [356, "Darren Waller", "FA", "TE"],
  [357, "Noah Gray", "KC", "TE"],
  [358, "Jared Wiley", "KC", "TE"],
  [359, "Sam Roush", "CHI", "TE"],
  [360, "Justin Fields", "KC", "QB"],
  [361, "Ty Simpson", "LAR", "QB"],
  [362, "Ben Sinnott", "WAS", "TE"],
  [363, "Gardner Minshew II", "ARI", "QB"],
]


// ---------------------------------------------------------------------------
// FULL PPR — Dalton Del Don (The Deep Shot), updated 6/15
// FantasyPros in-season accuracy: #6 in 2025
// ---------------------------------------------------------------------------
const DEL_DON_TOP_100 = [
  "Ja'Marr Chase", "Jahmyr Gibbs", "Puka Nacua", "Jaxon Smith-Njigba", "Bijan Robinson",
  "Amon-Ra St. Brown", "Christian McCaffrey", "CeeDee Lamb", "Drake London", "Jonathan Taylor",
  "Justin Jefferson", "A.J. Brown", "Ashton Jeanty", "Nico Collins", "Garrett Wilson", "Trey McBride",
  "Chase Brown", "Rashee Rice", "George Pickens", "DeVonta Smith", "James Cook III", "Brock Bowers",
  "Kenneth Walker III", "Omarion Hampton", "Lamar Jackson", "Zay Flowers", "Josh Allen", "Chris Olave",
  "Luther Burden III", "Jayden Daniels", "De'Von Achane", "Colston Loveland", "Saquon Barkley",
  "Jeremiyah Love", "Tee Higgins", "Malik Nabers", "Drake Maye", "Terry McLaurin", "Travis Etienne Jr.",
  "Tetairoa McMillan", "Derrick Henry", "Ladd McConkey", "Breece Hall", "Emeka Egbuka", "Jaylen Waddle",
  "Kyren Williams", "Javonte Williams", "Jordyn Tyson", "Mike Evans", "Cam Skattebo", "Christian Watson",
  "Rome Odunze", "David Montgomery", "Joe Burrow", "Davante Adams", "Josh Jacobs", "Tyler Warren",
  "Bhayshul Tuten", "Caleb Williams", "Jameson Williams", "TreVeyon Henderson", "Marvin Harrison Jr.",
  "Jalen Hurts", "DJ Moore", "Jaylen Warren", "Tucker Kraft", "Bucky Irving", "Carnell Tate",
  "Parker Washington", "Trevor Lawrence", "Brian Thomas Jr.", "D'Andre Swift", "Harold Fannin Jr.",
  "Jaxson Dart", "Rhamondre Stevenson", "Chris Godwin Jr.", "Quinshon Judkins", "Jonathon Brooks",
  "Brock Purdy", "Tony Pollard", "Quentin Johnston", "Josh Downs", "Makai Lemon", "RJ Harvey",
  "George Kittle", "Jadarian Price", "Kyle Pitts Sr.", "Michael Wilson", "Blake Corum", "Jayden Reed",
  "Courtland Sutton", "Justin Herbert", "Chuba Hubbard", "Alec Pierce", "Sam LaPorta", "DK Metcalf",
  "Dalton Kincaid", "Dak Prescott", "Kyle Monangai", "Ricky Pearsall",
] as const

const playerLookup = new Map(ERICKSON_RAW.map(([, name, team, position]) => [name, { team, position }]))
const DEL_DON_RAW: RawPlayer[] = [
  ...DEL_DON_TOP_100.map((name, index): RawPlayer => {
    const player = playerLookup.get(name)
    return [index + 1, name, player?.team || "FA", player?.position || "WR"]
  }),
  ...ERICKSON_RAW.filter(([, name]) => !DEL_DON_TOP_100.includes(name as (typeof DEL_DON_TOP_100)[number])).map(
    ([, name, team, position], index): RawPlayer => [DEL_DON_TOP_100.length + index + 1, name, team, position],
  ),
]


// ---------------------------------------------------------------------------
// HYBRID FULL PPR — accuracy-weighted by position
// Non-TE ranks start from Dalton Del Don; TE ranks use James Emrick-Wilson
// because his 2025 in-season TE accuracy rank was #5.
// James is intentionally not exposed as a standalone preset.
// ---------------------------------------------------------------------------
const EMRICK_WILSON_TE_RAW: RawPlayer[] = [
  [16, "Trey McBride", "ARI", "TE"],
  [22, "Brock Bowers", "LV", "TE"],
  [32, "Colston Loveland", "CHI", "TE"],
  [57, "Harold Fannin Jr.", "CLE", "TE"],
  [66, "Tucker Kraft", "GB", "TE"],
  [73, "Tyler Warren", "IND", "TE"],
  [85, "Sam LaPorta", "DET", "TE"],
  [87, "Kyle Pitts Sr.", "ATL", "TE"],
  [95, "Jake Ferguson", "DAL", "TE"],
  [97, "Oronde Gadsden II", "LAC", "TE"],
  [106, "Brenton Strange", "JAC", "TE"],
  [111, "Travis Kelce", "KC", "TE"],
  [112, "Isaiah Likely", "NYG", "TE"],
  [124, "Juwan Johnson", "NO", "TE"],
  [131, "Mark Andrews", "BAL", "TE"],
  [138, "Dalton Schultz", "HOU", "TE"],
  [144, "Dallas Goedert", "PHI", "TE"],
  [155, "Dalton Kincaid", "BUF", "TE"],
  [158, "Hunter Henry", "NE", "TE"],
  [173, "AJ Barner", "SEA", "TE"],
  [181, "T.J. Hockenson", "MIN", "TE"],
  [196, "Kenyon Sadiq", "NYJ", "TE"],
  [203, "Mason Taylor", "NYJ", "TE"],
  [209, "George Kittle", "SF", "TE"],
  [226, "Terrance Ferguson", "LAR", "TE"],
  [229, "Theo Johnson", "NYG", "TE"],
  [236, "Gunnar Helm", "TEN", "TE"],
  [246, "David Njoku", "LAC", "TE"],
  [254, "Chig Okonkwo", "WAS", "TE"],
  [256, "Evan Engram", "DEN", "TE"],
  [259, "Colby Parkinson", "LAR", "TE"],
  [261, "Cade Otton", "TB", "TE"],
  [268, "Pat Freiermuth", "PIT", "TE"],
  [274, "Mike Gesicki", "CIN", "TE"],
  [281, "Jake Tonges", "SF", "TE"],
]


const EMRICK_WILSON_HALF_PPR_RAW: RawPlayer[] = [
  [1, "Bijan Robinson", "ATL", "RB"],
  [2, "Ja'Marr Chase", "CIN", "WR"],
  [3, "Jahmyr Gibbs", "DET", "RB"],
  [4, "Puka Nacua", "LAR", "WR"],
  [5, "Jaxon Smith-Njigba", "SEA", "WR"],
  [6, "Christian McCaffrey", "SF", "RB"],
  [7, "Amon-Ra St. Brown", "DET", "WR"],
  [8, "Justin Jefferson", "MIN", "WR"],
  [9, "CeeDee Lamb", "DAL", "WR"],
  [10, "Jonathan Taylor", "IND", "RB"],
  [11, "Ashton Jeanty", "LV", "RB"],
  [12, "Omarion Hampton", "LAC", "RB"],
  [13, "Rashee Rice", "KC", "WR"],
  [14, "James Cook III", "BUF", "RB"],
  [15, "Trey McBride", "ARI", "TE"],
  [16, "Saquon Barkley", "PHI", "RB"],
  [17, "Drake London", "ATL", "WR"],
  [18, "Nico Collins", "HOU", "WR"],
  [19, "De'Von Achane", "MIA", "RB"],
  [20, "Chase Brown", "CIN", "RB"],
  [21, "Malik Nabers", "NYG", "WR"],
  [22, "Chris Olave", "NO", "WR"],
  [23, "George Pickens", "DAL", "WR"],
  [24, "Brock Bowers", "LV", "TE"],
  [25, "Kenneth Walker III", "KC", "RB"],
  [26, "Josh Allen", "BUF", "QB"],
  [27, "Lamar Jackson", "BAL", "QB"],
  [28, "A.J. Brown", "NE", "WR"],
  [29, "Drake Maye", "NE", "QB"],
  [30, "Breece Hall", "NYJ", "RB"],
  [31, "Tee Higgins", "CIN", "WR"],
  [32, "Tetairoa McMillan", "CAR", "WR"],
  [33, "Jeremiyah Love", "ARI", "RB"],
  [34, "Travis Etienne Jr.", "NO", "RB"],
  [35, "Colston Loveland", "CHI", "TE"],
  [36, "Luther Burden III", "CHI", "WR"],
  [37, "Joe Burrow", "CIN", "QB"],
  [38, "Josh Jacobs", "GB", "RB"],
  [39, "Michael Wilson", "ARI", "WR"],
  [40, "Garrett Wilson", "NYJ", "WR"],
  [41, "Davante Adams", "LAR", "WR"],
  [42, "Derrick Henry", "BAL", "RB"],
  [43, "Jameson Williams", "DET", "WR"],
  [44, "Christian Watson", "GB", "WR"],
  [45, "Ladd McConkey", "LAC", "WR"],
  [46, "Javonte Williams", "DAL", "RB"],
  [47, "Kyren Williams", "LAR", "RB"],
  [48, "David Montgomery", "HOU", "RB"],
  [49, "Jaylen Waddle", "DEN", "WR"],
  [50, "Makai Lemon", "PHI", "WR"],
  [51, "Zay Flowers", "BAL", "WR"],
  [52, "Terry McLaurin", "WAS", "WR"],
  [53, "Bhayshul Tuten", "JAC", "RB"],
  [54, "Bucky Irving", "TB", "RB"],
  [55, "Jayden Daniels", "WAS", "QB"],
  [56, "Quinshon Judkins", "CLE", "RB"],
  [57, "Tucker Kraft", "GB", "TE"],
  [58, "Cam Skattebo", "NYG", "RB"],
  [59, "DeVonta Smith", "PHI", "WR"],
  [60, "Jalen Hurts", "PHI", "QB"],
  [61, "Mike Evans", "SF", "WR"],
  [62, "TreVeyon Henderson", "NE", "RB"],
  [63, "Jaxson Dart", "NYG", "QB"],
  [64, "Emeka Egbuka", "TB", "WR"],
  [65, "Tony Pollard", "TEN", "RB"],
  [66, "D'Andre Swift", "CHI", "RB"],
  [67, "Harold Fannin Jr.", "CLE", "TE"],
  [68, "J.K. Dobbins", "DEN", "RB"],
  [69, "DJ Moore", "BUF", "WR"],
  [70, "Justin Herbert", "LAC", "QB"],
  [71, "Parker Washington", "JAC", "WR"],
  [72, "Rico Dowdle", "PIT", "RB"],
  [73, "Chuba Hubbard", "CAR", "RB"],
  [74, "Trevor Lawrence", "JAC", "QB"],
  [75, "Courtland Sutton", "DEN", "WR"],
  [76, "Alec Pierce", "IND", "WR"],
  [77, "Tyler Warren", "IND", "TE"],
  [78, "Tyler Allgeier", "ARI", "RB"],
  [79, "Caleb Williams", "CHI", "QB"],
  [80, "RJ Harvey", "DEN", "RB"],
  [81, "Rome Odunze", "CHI", "WR"],
  [82, "DK Metcalf", "PIT", "WR"],
  [83, "Carnell Tate", "TEN", "WR"],
  [84, "Sam LaPorta", "DET", "TE"],
  [85, "Jaylen Warren", "PIT", "RB"],
  [86, "Kyle Pitts Sr.", "ATL", "TE"],
  [87, "Marvin Harrison Jr.", "ARI", "WR"],
  [88, "Kyle Monangai", "CHI", "RB"],
  [89, "Jakobi Meyers", "JAC", "WR"],
  [90, "Brock Purdy", "SF", "QB"],
  [91, "Chris Godwin Jr.", "TB", "WR"],
  [92, "Jadarian Price", "SEA", "RB"],
  [93, "Jordan Addison", "MIN", "WR"],
  [94, "Oronde Gadsden II", "LAC", "TE"],
  [95, "Brian Thomas Jr.", "JAC", "WR"],
  [96, "Jake Ferguson", "DAL", "TE"],
  [97, "Bo Nix", "DEN", "QB"],
  [98, "Rhamondre Stevenson", "NE", "RB"],
  [99, "Kenneth Gainwell", "TB", "RB"],
  [100, "Dak Prescott", "DAL", "QB"],
]

function extendRawWithFallback(primaryRaw: RawPlayer[], fallbackRaw: RawPlayer[]): RawPlayer[] {
  const primaryNames = new Set(primaryRaw.map(([, name]) => name))
  return [
    ...primaryRaw,
    ...fallbackRaw
      .filter(([, name]) => !primaryNames.has(name))
      .map(([, name, team, position], index): RawPlayer => [primaryRaw.length + index + 1, name, team, position]),
  ]
}

function buildHybridRaw(baseRaw: RawPlayer[], teRaw: RawPlayer[]): RawPlayer[] {
  const teByName = new Map(teRaw.map(([rank, name, team, position]) => [name, { rank, team, position }]))
  const baseNames = new Set(baseRaw.map(([, name]) => name))
  const hybridEntries: RawPlayer[] = [
    ...baseRaw.map(([rank, name, team, position]): RawPlayer => {
      const teOverride = teByName.get(name)
      return teOverride ? [teOverride.rank, name, teOverride.team || team, teOverride.position] : [rank, name, team, position]
    }),
    ...teRaw.filter(([, name]) => !baseNames.has(name)),
  ]

  return hybridEntries
    .sort(([rankA, nameA], [rankB, nameB]) => rankA - rankB || nameA.localeCompare(nameB))
    .map(([, name, team, position], index): RawPlayer => [index + 1, name, team, position])
}

const HYBRID_HALF_PPR_RAW: RawPlayer[] = buildHybridRaw(BOONE_RAW, EMRICK_WILSON_TE_RAW)
const HYBRID_FULL_PPR_RAW: RawPlayer[] = buildHybridRaw(DEL_DON_RAW, EMRICK_WILSON_TE_RAW)

export type AccuracyRanks = Partial<Record<"QB" | "RB" | "WR" | "TE" | "K" | "DST" | "IDP", number | "-">>

export type RankingPreset = {
  id: string
  analyst: string
  source: string
  updated: string
  accuracyRank: number
  accuracyType: "In-season" | "Draft" | "Hybrid"
  accuracyRanks?: AccuracyRanks
  accuracyNote: string
  methodology?: string
  sourceByPosition?: Partial<Record<"QB" | "RB" | "WR" | "TE" | "K" | "DST", string>>
  players: ReturnType<typeof buildPlayers>
}

export type ScoringGroup = {
  id: string
  label: string
  description: string
  presets: RankingPreset[]
}

export const RANKING_PRESET_GROUPS: ScoringGroup[] = [
  {
    id: "half-ppr",
    label: "Half PPR",
    description: "0.5 points per reception",
    presets: [
      {
        id: "hybrid-half-ppr",
        analyst: "Sage Rankings",
        source: "Best analyst by position",
        updated: "6/15",
        accuracyRank: 1,
        accuracyType: "Hybrid",
        accuracyRanks: { QB: 6, RB: 5, WR: 1, TE: 5, K: 11, DST: 28, IDP: "-" },
        accuracyNote: "Position-aware board: Boone baseline with James Emrick-Wilson's #5 TE accuracy input.",
        methodology:
          "Uses the strongest available position specialists: Justin Boone for QB/RB/WR and James Emrick-Wilson for TE, then re-sorts into one actionable draft board.",
        sourceByPosition: { QB: "Justin Boone", RB: "Justin Boone", WR: "Justin Boone", TE: "James Emrick-Wilson", K: "Justin Boone", DST: "Justin Boone" },
        players: buildPlayers("hybrid-half", HYBRID_HALF_PPR_RAW),
      },
      {
        id: "boone-half-ppr",
        analyst: "Justin Boone",
        source: "Yahoo Sports",
        updated: "6/3",
        accuracyRank: 1,
        accuracyType: "In-season",
        accuracyRanks: { QB: 6, RB: 5, WR: 1, TE: 18, K: 11, DST: 28, IDP: "-" },
        accuracyNote: "#1 in FantasyPros 2025 in-season accuracy",
        players: buildPlayers("boone", BOONE_RAW),
      },
      {
        id: "del-don-half-ppr",
        analyst: "Dalton Del Don",
        source: "The Deep Shot",
        updated: "6/15",
        accuracyRank: 6,
        accuracyType: "In-season",
        accuracyRanks: { QB: 9, RB: 12, WR: 13, TE: 10, K: 31, DST: 30, IDP: "-" },
        accuracyNote: "#6 in FantasyPros 2025 in-season accuracy",
        players: buildPlayers("del-don-half", DEL_DON_HALF_PPR_RAW),
      },
    ],
  },
  {
    id: "full-ppr",
    label: "Full PPR",
    description: "1 point per reception",
    presets: [
      {
        id: "hybrid-full-ppr",
        analyst: "Sage Rankings",
        source: "Hybrid: Dalton Del Don + James Emrick-Wilson TE",
        updated: "6/15",
        accuracyRank: 1,
        accuracyType: "Hybrid",
        accuracyRanks: { QB: 9, RB: 12, WR: 13, TE: 5, K: 31, DST: 30, IDP: "-" },
        accuracyNote: "Hybrid board: Dalton Del Don in-season baseline with James Emrick-Wilson's #5 TE accuracy input.",
        methodology:
          "Uses Dalton Del Don's in-season board for QB/RB/WR and James Emrick-Wilson's TE ordering, then re-sorts the board into one Sage draft list.",
        sourceByPosition: { QB: "Dalton Del Don", RB: "Dalton Del Don", WR: "Dalton Del Don", TE: "James Emrick-Wilson", K: "Dalton Del Don", DST: "Dalton Del Don" },
        players: buildPlayers("hybrid-full", HYBRID_FULL_PPR_RAW),
      },
      {
        id: "erickson-full-ppr",
        analyst: "Andrew Erickson",
        source: "FantasyPros",
        updated: "6/12",
        accuracyRank: 5,
        accuracyType: "Draft",
        accuracyNote: "#5 in FantasyPros 2024 draft accuracy",
        players: buildPlayers("erickson", ERICKSON_RAW),
      },
      {
        id: "del-don-full-ppr",
        analyst: "Dalton Del Don",
        source: "The Deep Shot",
        updated: "6/15",
        accuracyRank: 6,
        accuracyType: "In-season",
        accuracyRanks: { QB: 9, RB: 12, WR: 13, TE: 10, K: 31, DST: 30, IDP: "-" },
        accuracyNote: "#6 in FantasyPros 2025 in-season accuracy",
        players: buildPlayers("del-don", DEL_DON_RAW),
      },
    ],
  },
]

export function findPresetById(id: string): RankingPreset | undefined {
  for (const group of RANKING_PRESET_GROUPS) {
    const found = group.presets.find((p) => p.id === id)
    if (found) return found
  }
  return undefined
}
